/*
 Highcharts JS v8.0.4 (2020-04-22)

 Annotations module

 (c) 2009-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/annotations",["highcharts"],function(n){c(n);c.Highcharts=n;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function n(f,a,c,k){f.hasOwnProperty(a)||(f[a]=k.apply(null,c))}c=c?c._modules:{};n(c,"annotations/eventEmitterMixin.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(f,a){var c=a.addEvent,k=a.fireEvent,
x=a.inArray,e=a.objectEach,t=a.pick,u=a.removeEvent;return{addEvents:function(){var b=this,h=function(d){c(d,"mousedown",function(g){b.onMouseDown(g)})};h(this.graphic.element);(b.labels||[]).forEach(function(b){b.options.useHTML&&h(b.graphic.text.element)});e(b.options.events,function(d,g){var h=function(h){"click"===g&&b.cancelClick||d.call(b,b.chart.pointer.normalize(h),b.target)};if(-1===x(g,b.nonDOMEvents||[]))b.graphic.on(g,h);else c(b,g,h)});if(b.options.draggable&&(c(b,"drag",b.onDrag),!b.graphic.renderer.styledMode)){var a=
{cursor:{x:"ew-resize",y:"ns-resize",xy:"move"}[b.options.draggable]};b.graphic.css(a);(b.labels||[]).forEach(function(b){b.options.useHTML&&b.graphic.text.css(a)})}b.isUpdating||k(b,"add")},removeDocEvents:function(){this.removeDrag&&(this.removeDrag=this.removeDrag());this.removeMouseUp&&(this.removeMouseUp=this.removeMouseUp())},onMouseDown:function(b){var h=this,e=h.chart.pointer;b.preventDefault&&b.preventDefault();if(2!==b.button){b=e.normalize(b);var d=b.chartX;var g=b.chartY;h.cancelClick=
!1;h.chart.hasDraggedAnnotation=!0;h.removeDrag=c(f.doc,"mousemove",function(b){h.hasDragged=!0;b=e.normalize(b);b.prevChartX=d;b.prevChartY=g;k(h,"drag",b);d=b.chartX;g=b.chartY});h.removeMouseUp=c(f.doc,"mouseup",function(b){h.cancelClick=h.hasDragged;h.hasDragged=!1;h.chart.hasDraggedAnnotation=!1;k(t(h.target,h),"afterUpdate");h.onMouseUp(b)})}},onMouseUp:function(b){var h=this.chart;b=this.target||this;var e=h.options.annotations;h=h.annotations.indexOf(b);this.removeDocEvents();e[h]=b.options},
onDrag:function(b){if(this.chart.isInsidePlot(b.chartX-this.chart.plotLeft,b.chartY-this.chart.plotTop)){var h=this.mouseMoveToTranslation(b);"x"===this.options.draggable&&(h.y=0);"y"===this.options.draggable&&(h.x=0);this.points.length?this.translate(h.x,h.y):(this.shapes.forEach(function(b){b.translate(h.x,h.y)}),this.labels.forEach(function(b){b.translate(h.x,h.y)}));this.redraw(!1)}},mouseMoveToRadians:function(b,h,e){var d=b.prevChartY-e,g=b.prevChartX-h;e=b.chartY-e;b=b.chartX-h;this.chart.inverted&&
(h=g,g=d,d=h,h=b,b=e,e=h);return Math.atan2(e,b)-Math.atan2(d,g)},mouseMoveToTranslation:function(b){var h=b.chartX-b.prevChartX;b=b.chartY-b.prevChartY;if(this.chart.inverted){var e=b;b=h;h=e}return{x:h,y:b}},mouseMoveToScale:function(b,h,e){h=(b.chartX-h||1)/(b.prevChartX-h||1);b=(b.chartY-e||1)/(b.prevChartY-e||1);this.chart.inverted&&(e=b,b=h,h=e);return{x:h,y:b}},destroy:function(){this.removeDocEvents();u(this);this.hcEvents=null}}});n(c,"annotations/ControlPoint.js",[c["parts/Utilities.js"],
c["annotations/eventEmitterMixin.js"]],function(c,a){var f=c.merge,k=c.pick;return function(){function c(e,c,f,b){this.addEvents=a.addEvents;this.graphic=void 0;this.mouseMoveToRadians=a.mouseMoveToRadians;this.mouseMoveToScale=a.mouseMoveToScale;this.mouseMoveToTranslation=a.mouseMoveToTranslation;this.onDrag=a.onDrag;this.onMouseDown=a.onMouseDown;this.onMouseUp=a.onMouseUp;this.removeDocEvents=a.removeDocEvents;this.nonDOMEvents=["drag"];this.chart=e;this.target=c;this.options=f;this.index=k(f.index,
b)}c.prototype.setVisibility=function(e){this.graphic.attr("visibility",e?"visible":"hidden");this.options.visible=e};c.prototype.render=function(){var e=this.chart,a=this.options;this.graphic=e.renderer.symbol(a.symbol,0,0,a.width,a.height).add(e.controlPointsGroup).css(a.style);this.setVisibility(a.visible);this.addEvents()};c.prototype.redraw=function(e){this.graphic[e?"animate":"attr"](this.options.positioner.call(this,this.target))};c.prototype.destroy=function(){a.destroy.call(this);this.graphic&&
(this.graphic=this.graphic.destroy());this.options=this.target=this.chart=null};c.prototype.update=function(e){var a=this.chart,c=this.target,b=this.index;e=f(!0,this.options,e);this.destroy();this.constructor(a,c,e,b);this.render(a.controlPointsGroup);this.redraw()};return c}()});n(c,"annotations/MockPoint.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,a){var f=a.defined,k=a.fireEvent;return function(){function a(e,a,f){this.y=this.x=this.plotY=this.plotX=this.isInside=void 0;this.mock=
!0;this.series={visible:!0,chart:e,getPlotBox:c.Series.prototype.getPlotBox};this.target=a||null;this.options=f;this.applyOptions(this.getOptions())}a.fromPoint=function(e){return new a(e.series.chart,null,{x:e.x,y:e.y,xAxis:e.series.xAxis,yAxis:e.series.yAxis})};a.pointToPixels=function(e,a){var c=e.series,b=c.chart,h=e.plotX,f=e.plotY;b.inverted&&(e.mock?(h=e.plotY,f=e.plotX):(h=b.plotWidth-e.plotY,f=b.plotHeight-e.plotX));c&&!a&&(e=c.getPlotBox(),h+=e.translateX,f+=e.translateY);return{x:h,y:f}};
a.pointToOptions=function(e){return{x:e.x,y:e.y,xAxis:e.series.xAxis,yAxis:e.series.yAxis}};a.prototype.hasDynamicOptions=function(){return"function"===typeof this.options};a.prototype.getOptions=function(){return this.hasDynamicOptions()?this.options(this.target):this.options};a.prototype.applyOptions=function(e){this.command=e.command;this.setAxis(e,"x");this.setAxis(e,"y");this.refresh()};a.prototype.setAxis=function(e,a){a+="Axis";e=e[a];var k=this.series.chart;this.series[a]=e instanceof c.Axis?
e:f(e)?k[a][e]||k.get(e):null};a.prototype.toAnchor=function(){var a=[this.plotX,this.plotY,0,0];this.series.chart.inverted&&(a[0]=this.plotY,a[1]=this.plotX);return a};a.prototype.getLabelConfig=function(){return{x:this.x,y:this.y,point:this}};a.prototype.isInsidePlot=function(){var a=this.plotX,c=this.plotY,u=this.series.xAxis,b=this.series.yAxis,h={x:a,y:c,isInsidePlot:!0};u&&(h.isInsidePlot=f(a)&&0<=a&&a<=u.len);b&&(h.isInsidePlot=h.isInsidePlot&&f(c)&&0<=c&&c<=b.len);k(this.series.chart,"afterIsInsidePlot",
h);return h.isInsidePlot};a.prototype.refresh=function(){var a=this.series,c=a.xAxis;a=a.yAxis;var f=this.getOptions();c?(this.x=f.x,this.plotX=c.toPixels(f.x,!0)):(this.x=null,this.plotX=f.x);a?(this.y=f.y,this.plotY=a.toPixels(f.y,!0)):(this.y=null,this.plotY=f.y);this.isInside=this.isInsidePlot()};a.prototype.translate=function(a,c,f,b){this.hasDynamicOptions()||(this.plotX+=f,this.plotY+=b,this.refreshOptions())};a.prototype.scale=function(a,c,f,b){if(!this.hasDynamicOptions()){var h=this.plotY*
b;this.plotX=(1-f)*a+this.plotX*f;this.plotY=(1-b)*c+h;this.refreshOptions()}};a.prototype.rotate=function(a,c,f){if(!this.hasDynamicOptions()){var b=Math.cos(f);f=Math.sin(f);var h=this.plotX,e=this.plotY;h-=a;e-=c;this.plotX=h*b-e*f+a;this.plotY=h*f+e*b+c;this.refreshOptions()}};a.prototype.refreshOptions=function(){var a=this.series,c=a.xAxis;a=a.yAxis;this.x=this.options.x=c?this.options.x=c.toValue(this.plotX,!0):this.plotX;this.y=this.options.y=a?a.toValue(this.plotY,!0):this.plotY};return a}()});
n(c,"annotations/controllable/controllableMixin.js",[c["parts/Utilities.js"],c["annotations/ControlPoint.js"],c["annotations/MockPoint.js"],c["parts/Tooltip.js"]],function(c,a,p,k){var f=c.isObject,e=c.isString,t=c.merge,u=c.splat;return{init:function(b,a,c){this.annotation=b;this.chart=b.chart;this.options=a;this.points=[];this.controlPoints=[];this.index=c;this.linkPoints();this.addControlPoints()},attr:function(){this.graphic.attr.apply(this.graphic,arguments)},getPointsOptions:function(){var b=
this.options;return b.points||b.point&&u(b.point)},attrsFromOptions:function(b){var a=this.constructor.attrsMap,c={},d,g=this.chart.styledMode;for(d in b){var l=a[d];!l||g&&-1!==["fill","stroke","stroke-width"].indexOf(l)||(c[l]=b[d])}return c},anchor:function(b){var a=b.series.getPlotBox();b=b.mock?b.toAnchor():k.prototype.getAnchor.call({chart:b.series.chart},b);b={x:b[0]+(this.options.x||0),y:b[1]+(this.options.y||0),height:b[2]||0,width:b[3]||0};return{relativePosition:b,absolutePosition:t(b,
{x:b.x+a.translateX,y:b.y+a.translateY})}},point:function(b,a){if(b&&b.series)return b;a&&null!==a.series||(f(b)?a=new p(this.chart,this,b):e(b)?a=this.chart.get(b)||null:"function"===typeof b&&(a=b.call(a,this),a=a.series?a:new p(this.chart,this,b)));return a},linkPoints:function(){var b=this.getPointsOptions(),a=this.points,c=b&&b.length||0,d;for(d=0;d<c;d++){var g=this.point(b[d],a[d]);if(!g){a.length=0;return}g.mock&&g.refresh();a[d]=g}return a},addControlPoints:function(){var b=this.options.controlPoints;
(b||[]).forEach(function(h,c){h=t(this.options.controlPointOptions,h);h.index||(h.index=c);b[c]=h;this.controlPoints.push(new a(this.chart,this,h))},this)},shouldBeDrawn:function(){return!!this.points.length},render:function(b){this.controlPoints.forEach(function(b){b.render()})},redraw:function(b){this.controlPoints.forEach(function(a){a.redraw(b)})},transform:function(b,a,c,d,g){if(this.chart.inverted){var l=a;a=c;c=l}this.points.forEach(function(l,h){this.transformPoint(b,a,c,d,g,h)},this)},transformPoint:function(b,
a,c,d,g,l){var h=this.points[l];h.mock||(h=this.points[l]=p.fromPoint(h));h[b](a,c,d,g)},translate:function(b,a){this.transform("translate",null,null,b,a)},translatePoint:function(b,a,c){this.transformPoint("translate",null,null,b,a,c)},translateShape:function(b,a){var c=this.annotation.chart,d=this.annotation.userOptions,g=c.annotations.indexOf(this.annotation);c=c.options.annotations[g];this.translatePoint(b,a,0);c[this.collection][this.index].point=this.options.point;d[this.collection][this.index].point=
this.options.point},rotate:function(b,a,c){this.transform("rotate",b,a,c)},scale:function(b,a,c,d){this.transform("scale",b,a,c,d)},setControlPointsVisibility:function(b){this.controlPoints.forEach(function(a){a.setVisibility(b)})},destroy:function(){this.graphic&&(this.graphic=this.graphic.destroy());this.tracker&&(this.tracker=this.tracker.destroy());this.controlPoints.forEach(function(b){b.destroy()});this.options=this.controlPoints=this.points=this.chart=null;this.annotation&&(this.annotation=
null)},update:function(b){var a=this.annotation;b=t(!0,this.options,b);var c=this.graphic.parentGroup;this.destroy();this.constructor(a,b);this.render(c);this.redraw()}}});n(c,"annotations/controllable/markerMixin.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,a){var f=a.addEvent,k=a.defined,x=a.merge,e=a.objectEach,t=a.uniqueKey,u={arrow:{tagName:"marker",render:!1,id:"arrow",refY:5,refX:9,markerWidth:10,markerHeight:10,children:[{tagName:"path",d:"M 0 0 L 10 5 L 0 10 Z",strokeWidth:0}]},
"reverse-arrow":{tagName:"marker",render:!1,id:"reverse-arrow",refY:5,refX:1,markerWidth:10,markerHeight:10,children:[{tagName:"path",d:"M 0 5 L 10 0 L 10 10 Z",strokeWidth:0}]}};c.SVGRenderer.prototype.addMarker=function(b,a){var c={id:b},d={stroke:a.color||"none",fill:a.color||"rgba(0, 0, 0, 0.75)"};c.children=a.children.map(function(a){return x(d,a)});a=this.definition(x(!0,{markerWidth:20,markerHeight:20,refX:0,refY:0,orient:"auto"},a,c));a.id=b;return a};a=function(a){return function(b){this.attr(a,
"url(#"+b+")")}};a={markerEndSetter:a("marker-end"),markerStartSetter:a("marker-start"),setItemMarkers:function(a){var b=a.options,c=a.chart,d=c.options.defs,g=b.fill,l=k(g)&&"none"!==g?g:b.stroke;["markerStart","markerEnd"].forEach(function(g){var e=b[g],q;if(e){for(q in d){var f=d[q];if(e===f.id&&"marker"===f.tagName){var m=f;break}}m&&(e=a[g]=c.renderer.addMarker((b.id||t())+"-"+m.id,x(m,{color:l})),a.attr(g,e.attr("id")))}})}};f(c.Chart,"afterGetContainer",function(){this.options.defs=x(u,this.options.defs||
{});e(this.options.defs,function(a){"marker"===a.tagName&&!1!==a.render&&this.renderer.addMarker(a.id,a)},this)});return a});n(c,"annotations/controllable/ControllablePath.js",[c["parts/Globals.js"],c["parts/Utilities.js"],c["annotations/controllable/controllableMixin.js"],c["annotations/controllable/markerMixin.js"]],function(c,a,p,k){var f=a.extend;a=a.merge;var e="rgba(192,192,192,"+(c.svg?.0001:.002)+")";c=function(a,c,b){this.init(a,c,b);this.collection="shapes"};c.attrsMap={dashStyle:"dashstyle",
strokeWidth:"stroke-width",stroke:"stroke",fill:"fill",zIndex:"zIndex"};a(!0,c.prototype,p,{type:"path",setMarkers:k.setItemMarkers,toD:function(){var a=this.options.d;if(a)return"function"===typeof a?a.call(this):a;a=this.points;var c=a.length,b=c,e=a[0],f=b&&this.anchor(e).absolutePosition,d=0,g=[];if(f)for(g.push(["M",f.x,f.y]);++d<c&&b;)e=a[d],b=e.command||"L",f=this.anchor(e).absolutePosition,"M"===b?g.push([b,f.x,f.y]):"L"===b?g.push([b,f.x,f.y]):"Z"===b&&g.push([b]),b=e.series.visible;return b?
this.chart.renderer.crispLine(g,this.graphic.strokeWidth()):null},shouldBeDrawn:function(){return p.shouldBeDrawn.call(this)||!!this.options.d},render:function(a){var c=this.options,b=this.attrsFromOptions(c);this.graphic=this.annotation.chart.renderer.path([["M",0,0]]).attr(b).add(a);c.className&&this.graphic.addClass(c.className);this.tracker=this.annotation.chart.renderer.path([["M",0,0]]).addClass("highcharts-tracker-line").attr({zIndex:2}).add(a);this.annotation.chart.styledMode||this.tracker.attr({"stroke-linejoin":"round",
stroke:e,fill:e,"stroke-width":this.graphic.strokeWidth()+2*c.snap});p.render.call(this);f(this.graphic,{markerStartSetter:k.markerStartSetter,markerEndSetter:k.markerEndSetter});this.setMarkers(this)},redraw:function(a){var c=this.toD(),b=a?"animate":"attr";c?(this.graphic[b]({d:c}),this.tracker[b]({d:c})):(this.graphic.attr({d:"M 0 -9000000000"}),this.tracker.attr({d:"M 0 -9000000000"}));this.graphic.placed=this.tracker.placed=!!c;p.redraw.call(this,a)}});return c});n(c,"annotations/controllable/ControllableRect.js",
[c["parts/Utilities.js"],c["annotations/controllable/controllableMixin.js"],c["annotations/controllable/ControllablePath.js"]],function(c,a,p){c=c.merge;var f=function(a,c,f){this.init(a,c,f);this.collection="shapes"};f.attrsMap=c(p.attrsMap,{width:"width",height:"height"});c(!0,f.prototype,a,{type:"rect",translate:a.translateShape,render:function(c){var e=this.attrsFromOptions(this.options);this.graphic=this.annotation.chart.renderer.rect(0,-9E9,0,0).attr(e).add(c);a.render.call(this)},redraw:function(c){var e=
this.anchor(this.points[0]).absolutePosition;if(e)this.graphic[c?"animate":"attr"]({x:e.x,y:e.y,width:this.options.width,height:this.options.height});else this.attr({x:0,y:-9E9});this.graphic.placed=!!e;a.redraw.call(this,c)}});return f});n(c,"annotations/controllable/ControllableCircle.js",[c["parts/Utilities.js"],c["annotations/controllable/controllableMixin.js"],c["annotations/controllable/ControllablePath.js"]],function(c,a,p){c=c.merge;var f=function(a,c,f){this.init(a,c,f);this.collection="shapes"};
f.attrsMap=c(p.attrsMap,{r:"r"});c(!0,f.prototype,a,{type:"circle",translate:a.translateShape,render:function(c){var e=this.attrsFromOptions(this.options);this.graphic=this.annotation.chart.renderer.circle(0,-9E9,0).attr(e).add(c);a.render.call(this)},redraw:function(c){var e=this.anchor(this.points[0]).absolutePosition;if(e)this.graphic[c?"animate":"attr"]({x:e.x,y:e.y,r:this.options.r});else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!e;a.redraw.call(this,c)},setRadius:function(a){this.options.r=
a}});return f});n(c,"annotations/controllable/ControllableLabel.js",[c["parts/Globals.js"],c["parts/Utilities.js"],c["annotations/controllable/controllableMixin.js"],c["annotations/MockPoint.js"],c["parts/Tooltip.js"]],function(c,a,p,k,x){var e=a.extend,f=a.format,n=a.isNumber,b=a.merge,h=a.pick,r=function(a,b,c){this.init(a,b,c);this.collection="labels"};r.shapesWithoutBackground=["connector"];r.alignedPosition=function(a,b){var c=a.align,g=a.verticalAlign,d=(b.x||0)+(a.x||0),e=(b.y||0)+(a.y||0),
f,m;"right"===c?f=1:"center"===c&&(f=2);f&&(d+=(b.width-(a.width||0))/f);"bottom"===g?m=1:"middle"===g&&(m=2);m&&(e+=(b.height-(a.height||0))/m);return{x:Math.round(d),y:Math.round(e)}};r.justifiedOptions=function(a,b,c,e){var g=c.align,d=c.verticalAlign,f=b.box?0:b.padding||0,m=b.getBBox();b={align:g,verticalAlign:d,x:c.x,y:c.y,width:b.width,height:b.height};c=e.x-a.plotLeft;var l=e.y-a.plotTop;e=c+f;0>e&&("right"===g?b.align="left":b.x=-e);e=c+m.width-f;e>a.plotWidth&&("left"===g?b.align="right":
b.x=a.plotWidth-e);e=l+f;0>e&&("bottom"===d?b.verticalAlign="top":b.y=-e);e=l+m.height-f;e>a.plotHeight&&("top"===d?b.verticalAlign="bottom":b.y=a.plotHeight-e);return b};r.attrsMap={backgroundColor:"fill",borderColor:"stroke",borderWidth:"stroke-width",zIndex:"zIndex",borderRadius:"r",padding:"padding"};b(!0,r.prototype,p,{translatePoint:function(a,b){p.translatePoint.call(this,a,b,0)},translate:function(a,b){var c=this.annotation.chart,g=this.annotation.userOptions,d=c.annotations.indexOf(this.annotation);
d=c.options.annotations[d];c.inverted&&(c=a,a=b,b=c);this.options.x+=a;this.options.y+=b;d[this.collection][this.index].x=this.options.x;d[this.collection][this.index].y=this.options.y;g[this.collection][this.index].x=this.options.x;g[this.collection][this.index].y=this.options.y},render:function(a){var b=this.options,c=this.attrsFromOptions(b),d=b.style;this.graphic=this.annotation.chart.renderer.label("",0,-9999,b.shape,null,null,b.useHTML,null,"annotation-label").attr(c).add(a);this.annotation.chart.styledMode||
("contrast"===d.color&&(d.color=this.annotation.chart.renderer.getContrast(-1<r.shapesWithoutBackground.indexOf(b.shape)?"#FFFFFF":b.backgroundColor)),this.graphic.css(b.style).shadow(b.shadow));b.className&&this.graphic.addClass(b.className);this.graphic.labelrank=b.labelrank;p.render.call(this)},redraw:function(a){var b=this.options,c=this.text||b.format||b.text,d=this.graphic,e=this.points[0];d.attr({text:c?f(c,e.getLabelConfig(),this.annotation.chart):b.formatter.call(e,this)});b=this.anchor(e);
(c=this.position(b))?(d.alignAttr=c,c.anchorX=b.absolutePosition.x,c.anchorY=b.absolutePosition.y,d[a?"animate":"attr"](c)):d.attr({x:0,y:-9999});d.placed=!!c;p.redraw.call(this,a)},anchor:function(){var a=p.anchor.apply(this,arguments),b=this.options.x||0,c=this.options.y||0;a.absolutePosition.x-=b;a.absolutePosition.y-=c;a.relativePosition.x-=b;a.relativePosition.y-=c;return a},position:function(a){var b=this.graphic,c=this.annotation.chart,d=this.points[0],f=this.options,v=a.absolutePosition,p=
a.relativePosition;if(a=d.series.visible&&k.prototype.isInsidePlot.call(d)){if(f.distance)var m=x.prototype.getPosition.call({chart:c,distance:h(f.distance,16)},b.width,b.height,{plotX:p.x,plotY:p.y,negative:d.negative,ttBelow:d.ttBelow,h:p.height||p.width});else f.positioner?m=f.positioner.call(this):(d={x:v.x,y:v.y,width:0,height:0},m=r.alignedPosition(e(f,{width:b.width,height:b.height}),d),"justify"===this.options.overflow&&(m=r.alignedPosition(r.justifiedOptions(c,b,f,m),d)));f.crop&&(f=m.x-
c.plotLeft,d=m.y-c.plotTop,a=c.isInsidePlot(f,d)&&c.isInsidePlot(f+b.width,d+b.height))}return a?m:null}});c.SVGRenderer.prototype.symbols.connector=function(a,b,c,e,f){var d=f&&f.anchorX;f=f&&f.anchorY;var g=c/2;if(n(d)&&n(f)){var m=[["M",d,f]];var h=b-f;0>h&&(h=-e-h);h<c&&(g=d<a+c/2?h:c-h);f>b+e?m.push(["L",a+g,b+e]):f<b?m.push(["L",a+g,b]):d<a?m.push(["L",a,b+e/2]):d>a+c&&m.push(["L",a+c,b+e/2])}return m||[]};return r});n(c,"annotations/controllable/ControllableImage.js",[c["parts/Utilities.js"],
c["annotations/controllable/controllableMixin.js"],c["annotations/controllable/ControllableLabel.js"]],function(c,a,p){c=c.merge;var f=function(a,c,f){this.init(a,c,f);this.collection="shapes"};f.attrsMap={width:"width",height:"height",zIndex:"zIndex"};c(!0,f.prototype,a,{type:"image",translate:a.translateShape,render:function(c){var e=this.attrsFromOptions(this.options),f=this.options;this.graphic=this.annotation.chart.renderer.image(f.src,0,-9E9,f.width,f.height).attr(e).add(c);this.graphic.width=
f.width;this.graphic.height=f.height;a.render.call(this)},redraw:function(c){var f=this.anchor(this.points[0]);if(f=p.prototype.position.call(this,f))this.graphic[c?"animate":"attr"]({x:f.x,y:f.y});else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!f;a.redraw.call(this,c)}});return f});n(c,"annotations/annotations.src.js",[c["parts/Globals.js"],c["parts/Utilities.js"],c["annotations/controllable/controllableMixin.js"],c["annotations/controllable/ControllableRect.js"],c["annotations/controllable/ControllableCircle.js"],
c["annotations/controllable/ControllablePath.js"],c["annotations/controllable/ControllableImage.js"],c["annotations/controllable/ControllableLabel.js"],c["annotations/eventEmitterMixin.js"],c["annotations/MockPoint.js"],c["annotations/ControlPoint.js"]],function(c,a,p,k,n,e,t,u,b,h,r){var d=a.addEvent,g=a.defined,f=a.destroyObjectProperties,q=a.erase,y=a.extend,v=a.find,A=a.fireEvent,m=a.merge,B=a.pick,C=a.splat;a=a.wrap;var z=c.Chart.prototype,w=c.Annotation=function(a,b){this.chart=a;this.points=
[];this.controlPoints=[];this.coll="annotations";this.labels=[];this.shapes=[];this.options=m(this.defaultOptions,b);this.userOptions=b;b=this.getLabelsAndShapesOptions(this.options,b);this.options.labels=b.labels;this.options.shapes=b.shapes;this.init(a,this.options)};m(!0,w.prototype,p,b,{nonDOMEvents:["add","afterUpdate","drag","remove"],defaultOptions:{visible:!0,draggable:"xy",labelOptions:{align:"center",allowOverlap:!1,backgroundColor:"rgba(0, 0, 0, 0.75)",borderColor:"black",borderRadius:3,
borderWidth:1,className:"",crop:!1,formatter:function(){return g(this.y)?this.y:"Annotation label"},overflow:"justify",padding:5,shadow:!1,shape:"callout",style:{fontSize:"11px",fontWeight:"normal",color:"contrast"},useHTML:!1,verticalAlign:"bottom",x:0,y:-16},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1,fill:"rgba(0, 0, 0, 0.75)",r:0,snap:2},controlPointOptions:{symbol:"circle",width:10,height:10,style:{stroke:"black","stroke-width":2,fill:"white"},visible:!1,events:{}},events:{},zIndex:6},
init:function(){this.linkPoints();this.addControlPoints();this.addShapes();this.addLabels();this.setLabelCollector()},getLabelsAndShapesOptions:function(a,b){var c={};["labels","shapes"].forEach(function(d){a[d]&&(c[d]=C(b[d]).map(function(b,c){return m(a[d][c],b)}))});return c},addShapes:function(){(this.options.shapes||[]).forEach(function(a,b){a=this.initShape(a,b);m(!0,this.options.shapes[b],a.options)},this)},addLabels:function(){(this.options.labels||[]).forEach(function(a,b){a=this.initLabel(a,
b);m(!0,this.options.labels[b],a.options)},this)},addClipPaths:function(){this.setClipAxes();this.clipXAxis&&this.clipYAxis&&(this.clipRect=this.chart.renderer.clipRect(this.getClipBox()))},setClipAxes:function(){var a=this.chart.xAxis,b=this.chart.yAxis,c=(this.options.labels||[]).concat(this.options.shapes||[]).reduce(function(c,d){return[a[d&&d.point&&d.point.xAxis]||c[0],b[d&&d.point&&d.point.yAxis]||c[1]]},[]);this.clipXAxis=c[0];this.clipYAxis=c[1]},getClipBox:function(){if(this.clipXAxis&&
this.clipYAxis)return{x:this.clipXAxis.left,y:this.clipYAxis.top,width:this.clipXAxis.width,height:this.clipYAxis.height}},setLabelCollector:function(){var a=this;a.labelCollector=function(){return a.labels.reduce(function(a,b){b.options.allowOverlap||a.push(b.graphic);return a},[])};a.chart.labelCollectors.push(a.labelCollector)},setOptions:function(a){this.options=m(this.defaultOptions,a)},redraw:function(a){this.linkPoints();this.graphic||this.render();this.clipRect&&this.clipRect.animate(this.getClipBox());
this.redrawItems(this.shapes,a);this.redrawItems(this.labels,a);p.redraw.call(this,a)},redrawItems:function(a,b){for(var c=a.length;c--;)this.redrawItem(a[c],b)},renderItems:function(a){for(var b=a.length;b--;)this.renderItem(a[b])},render:function(){var a=this.chart.renderer;this.graphic=a.g("annotation").attr({zIndex:this.options.zIndex,visibility:this.options.visible?"visible":"hidden"}).add();this.shapesGroup=a.g("annotation-shapes").add(this.graphic).clip(this.chart.plotBoxClip);this.labelsGroup=
a.g("annotation-labels").attr({translateX:0,translateY:0}).add(this.graphic);this.addClipPaths();this.clipRect&&this.graphic.clip(this.clipRect);this.renderItems(this.shapes);this.renderItems(this.labels);this.addEvents();p.render.call(this)},setVisibility:function(a){var b=this.options;a=B(a,!b.visible);this.graphic.attr("visibility",a?"visible":"hidden");a||this.setControlPointsVisibility(!1);b.visible=a},setControlPointsVisibility:function(a){var b=function(b){b.setControlPointsVisibility(a)};
p.setControlPointsVisibility.call(this,a);this.shapes.forEach(b);this.labels.forEach(b)},destroy:function(){var a=this.chart,c=function(a){a.destroy()};this.labels.forEach(c);this.shapes.forEach(c);this.clipYAxis=this.clipXAxis=null;q(a.labelCollectors,this.labelCollector);b.destroy.call(this);p.destroy.call(this);f(this,a)},remove:function(){return this.chart.removeAnnotation(this)},update:function(a,b){var c=this.chart,d=this.getLabelsAndShapesOptions(this.userOptions,a),g=c.annotations.indexOf(this);
a=m(!0,this.userOptions,a);a.labels=d.labels;a.shapes=d.shapes;this.destroy();this.constructor(c,a);c.options.annotations[g]=a;this.isUpdating=!0;B(b,!0)&&c.redraw();A(this,"afterUpdate");this.isUpdating=!1},initShape:function(a,b){a=m(this.options.shapeOptions,{controlPointOptions:this.options.controlPointOptions},a);b=new w.shapesMap[a.type](this,a,b);b.itemType="shape";this.shapes.push(b);return b},initLabel:function(a,b){a=m(this.options.labelOptions,{controlPointOptions:this.options.controlPointOptions},
a);b=new u(this,a,b);b.itemType="label";this.labels.push(b);return b},redrawItem:function(a,b){a.linkPoints();a.shouldBeDrawn()?(a.graphic||this.renderItem(a),a.redraw(B(b,!0)&&a.graphic.placed),a.points.length&&this.adjustVisibility(a)):this.destroyItem(a)},adjustVisibility:function(a){var b=!1,c=a.graphic;a.points.forEach(function(a){!1!==a.series.visible&&!1!==a.visible&&(b=!0)});b?"hidden"===c.visibility&&c.show():c.hide()},destroyItem:function(a){q(this[a.itemType+"s"],a);a.destroy()},renderItem:function(a){a.render("label"===
a.itemType?this.labelsGroup:this.shapesGroup)}});w.shapesMap={rect:k,circle:n,path:e,image:t};w.types={};w.MockPoint=h;w.ControlPoint=r;c.extendAnnotation=function(a,b,c,d){b=b||w;m(!0,a.prototype,b.prototype,c);a.prototype.defaultOptions=m(a.prototype.defaultOptions,d||{})};y(z,{initAnnotation:function(a){a=new (w.types[a.type]||w)(this,a);this.annotations.push(a);return a},addAnnotation:function(a,b){a=this.initAnnotation(a);this.options.annotations.push(a.options);B(b,!0)&&a.redraw();return a},
removeAnnotation:function(a){var b=this.annotations,c="annotations"===a.coll?a:v(b,function(b){return b.options.id===a});c&&(A(c,"remove"),q(this.options.annotations,c.options),q(b,c),c.destroy())},drawAnnotations:function(){this.plotBoxClip.attr(this.plotBox);this.annotations.forEach(function(a){a.redraw()})}});z.collectionsWithUpdate.push("annotations");z.collectionsWithInit.annotations=[z.addAnnotation];z.callbacks.push(function(a){a.annotations=[];a.options.annotations||(a.options.annotations=
[]);a.plotBoxClip=this.renderer.clipRect(this.plotBox);a.controlPointsGroup=a.renderer.g("control-points").attr({zIndex:99}).clip(a.plotBoxClip).add();a.options.annotations.forEach(function(b,c){b=a.initAnnotation(b);a.options.annotations[c]=b.options});a.drawAnnotations();d(a,"redraw",a.drawAnnotations);d(a,"destroy",function(){a.plotBoxClip.destroy();a.controlPointsGroup.destroy()})});a(c.Pointer.prototype,"onContainerMouseDown",function(a){this.chart.hasDraggedAnnotation||a.apply(this,Array.prototype.slice.call(arguments,
1))})});n(c,"mixins/navigation.js",[],function(){return{initUpdate:function(c){c.navigation||(c.navigation={updates:[],update:function(a,c){this.updates.forEach(function(f){f.update.call(f.context,a,c)})}})},addUpdate:function(c,a){a.navigation||this.initUpdate(a);a.navigation.updates.push({update:c,context:a})}}});n(c,"annotations/navigationBindings.js",[c["parts/Globals.js"],c["parts/Utilities.js"],c["mixins/navigation.js"]],function(c,a,p){function f(a){var c=a.prototype.defaultOptions.events&&
a.prototype.defaultOptions.events.click;l(!0,a.prototype.defaultOptions.events,{click:function(a){var d=this,g=d.chart.navigationBindings,e=g.activeAnnotation;c&&c.click.call(d,a);e!==d?(g.deselectAnnotation(),g.activeAnnotation=d,d.setControlPointsVisibility(!0),b(g,"showPopup",{annotation:d,formType:"annotation-toolbar",options:g.annotationToFields(d),onSubmit:function(a){var b={};"remove"===a.actionType?(g.activeAnnotation=!1,g.chart.removeAnnotation(d)):(g.fieldsToOptions(a.fields,b),g.deselectAnnotation(),
a=b.typeOptions,"measure"===d.options.type&&(a.crosshairY.enabled=0!==a.crosshairY.strokeWidth,a.crosshairX.enabled=0!==a.crosshairX.strokeWidth),d.update(b))}})):(g.deselectAnnotation(),b(g,"closePopup"));a.activeAnnotation=!0}})}var n=a.addEvent,e=a.attr,t=a.extend,u=a.format,b=a.fireEvent,h=a.isArray,r=a.isFunction,d=a.isNumber,g=a.isObject,l=a.merge,q=a.objectEach,y=a.pick,v=c.doc,A=c.win;c.NavigationBindings=function(a,b){this.chart=a;this.options=b;this.eventsToUnbind=[];this.container=v.getElementsByClassName(this.options.bindingsClassName)};
c.NavigationBindings.annotationsEditable={nestedOptions:{labelOptions:["style","format","backgroundColor"],labels:["style"],label:["style"],style:["fontSize","color"],background:["fill","strokeWidth","stroke"],innerBackground:["fill","strokeWidth","stroke"],outerBackground:["fill","strokeWidth","stroke"],shapeOptions:["fill","strokeWidth","stroke"],shapes:["fill","strokeWidth","stroke"],line:["strokeWidth","stroke"],backgroundColors:[!0],connector:["fill","strokeWidth","stroke"],crosshairX:["strokeWidth",
"stroke"],crosshairY:["strokeWidth","stroke"]},circle:["shapes"],verticalLine:[],label:["labelOptions"],measure:["background","crosshairY","crosshairX"],fibonacci:[],tunnel:["background","line","height"],pitchfork:["innerBackground","outerBackground"],rect:["shapes"],crookedLine:[],basicAnnotation:[]};c.NavigationBindings.annotationsNonEditable={rectangle:["crosshairX","crosshairY","label"]};t(c.NavigationBindings.prototype,{initEvents:function(){var a=this,b=a.chart,c=a.container,d=a.options;a.boundClassNames=
{};q(d.bindings,function(b){a.boundClassNames[b.className]=b});[].forEach.call(c,function(b){a.eventsToUnbind.push(n(b,"click",function(b){var d=a.getButtonEvents(c,b);d&&a.bindingsButtonClick(d.button,d.events,b)}))});q(d.events||{},function(b,c){r(b)&&a.eventsToUnbind.push(n(a,c,b))});a.eventsToUnbind.push(n(b.container,"click",function(c){!b.cancelClick&&b.isInsidePlot(c.chartX-b.plotLeft,c.chartY-b.plotTop)&&a.bindingsChartClick(this,c)}));a.eventsToUnbind.push(n(b.container,"mousemove",function(b){a.bindingsContainerMouseMove(this,
b)}))},initUpdate:function(){var a=this;p.addUpdate(function(b){a.update(b)},this.chart)},bindingsButtonClick:function(a,c,d){var g=this.chart;this.selectedButtonElement&&(b(this,"deselectButton",{button:this.selectedButtonElement}),this.nextEvent&&(this.currentUserDetails&&"annotations"===this.currentUserDetails.coll&&g.removeAnnotation(this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1));this.selectedButton=c;this.selectedButtonElement=a;b(this,"selectButton",{button:a});c.init&&c.init.call(this,
a,d);(c.start||c.steps)&&g.renderer.boxWrapper.addClass("highcharts-draw-mode")},bindingsChartClick:function(a,c){a=this.chart;var d=this.selectedButton;a=a.renderer.boxWrapper;var g;if(g=this.activeAnnotation&&!c.activeAnnotation&&c.target.parentNode){a:{g=c.target;var e=A.Element.prototype,f=e.matches||e.msMatchesSelector||e.webkitMatchesSelector,m=null;if(e.closest)m=e.closest.call(g,".highcharts-popup");else{do{if(f.call(g,".highcharts-popup"))break a;g=g.parentElement||g.parentNode}while(null!==
g&&1===g.nodeType)}g=m}g=!g}g&&(b(this,"closePopup"),this.deselectAnnotation());d&&d.start&&(this.nextEvent?(this.nextEvent(c,this.currentUserDetails),this.steps&&(this.stepIndex++,d.steps[this.stepIndex]?this.mouseMoveEvent=this.nextEvent=d.steps[this.stepIndex]:(b(this,"deselectButton",{button:this.selectedButtonElement}),a.removeClass("highcharts-draw-mode"),d.end&&d.end.call(this,c,this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1,this.selectedButton=null))):(this.currentUserDetails=
d.start.call(this,c),d.steps?(this.stepIndex=0,this.steps=!0,this.mouseMoveEvent=this.nextEvent=d.steps[this.stepIndex]):(b(this,"deselectButton",{button:this.selectedButtonElement}),a.removeClass("highcharts-draw-mode"),this.steps=!1,this.selectedButton=null,d.end&&d.end.call(this,c,this.currentUserDetails))))},bindingsContainerMouseMove:function(a,b){this.mouseMoveEvent&&this.mouseMoveEvent(b,this.currentUserDetails)},fieldsToOptions:function(a,b){q(a,function(a,c){var g=parseFloat(a),e=c.split("."),
f=b,m=e.length-1;!d(g)||a.match(/px/g)||c.match(/format/g)||(a=g);""!==a&&"undefined"!==a&&e.forEach(function(b,c){var d=y(e[c+1],"");m===c?f[b]=a:(f[b]||(f[b]=d.match(/\d/g)?[]:{}),f=f[b])})});return b},deselectAnnotation:function(){this.activeAnnotation&&(this.activeAnnotation.setControlPointsVisibility(!1),this.activeAnnotation=!1)},annotationToFields:function(a){function b(c,d,e,l){if(e&&-1===v.indexOf(d)&&(0<=(e.indexOf&&e.indexOf(d))||e[d]||!0===e))if(h(c))l[d]=[],c.forEach(function(a,c){g(a)?
(l[d][c]={},q(a,function(a,g){b(a,g,f[d],l[d][c])})):b(a,0,f[d],l[d])});else if(g(c)){var k={};h(l)?(l.push(k),k[d]={},k=k[d]):l[d]=k;q(c,function(a,c){b(a,c,0===d?e:f[d],k)})}else"format"===d?l[d]=[u(c,a.labels[0].points[0]).toString(),"text"]:h(l)?l.push([c,m(c)]):l[d]=[c,m(c)]}var d=a.options,e=c.NavigationBindings.annotationsEditable,f=e.nestedOptions,m=this.utils.getFieldType,l=y(d.type,d.shapes&&d.shapes[0]&&d.shapes[0].type,d.labels&&d.labels[0]&&d.labels[0].itemType,"label"),v=c.NavigationBindings.annotationsNonEditable[d.langKey]||
[],k={langKey:d.langKey,type:l};q(d,function(a,c){"typeOptions"===c?(k[c]={},q(d[c],function(a,d){b(a,d,f,k[c],!0)})):b(a,c,e[l],k)});return k},getClickedClassNames:function(a,b){var c=b.target;b=[];for(var d;c&&((d=e(c,"class"))&&(b=b.concat(d.split(" ").map(function(a){return[a,c]}))),c=c.parentNode,c!==a););return b},getButtonEvents:function(a,b){var c=this,d;this.getClickedClassNames(a,b).forEach(function(a){c.boundClassNames[a[0]]&&!d&&(d={events:c.boundClassNames[a[0]],button:a[1]})});return d},
update:function(a){this.options=l(!0,this.options,a);this.removeEvents();this.initEvents()},removeEvents:function(){this.eventsToUnbind.forEach(function(a){a()})},destroy:function(){this.removeEvents()},utils:{updateRectSize:function(a,b){var c=b.chart,d=b.options.typeOptions,g=c.pointer.getCoordinates(a);a=g.xAxis[0].value-d.point.x;d=d.point.y-g.yAxis[0].value;b.update({typeOptions:{background:{width:c.inverted?d:a,height:c.inverted?a:d}}})},getFieldType:function(a){return{string:"text",number:"number",
"boolean":"checkbox"}[typeof a]}}});c.Chart.prototype.initNavigationBindings=function(){var a=this.options;a&&a.navigation&&a.navigation.bindings&&(this.navigationBindings=new c.NavigationBindings(this,a.navigation),this.navigationBindings.initEvents(),this.navigationBindings.initUpdate())};n(c.Chart,"load",function(){this.initNavigationBindings()});n(c.Chart,"destroy",function(){this.navigationBindings&&this.navigationBindings.destroy()});n(c.NavigationBindings,"deselectButton",function(){this.selectedButtonElement=
null});n(c.Annotation,"remove",function(){this.chart.navigationBindings&&this.chart.navigationBindings.deselectAnnotation()});c.Annotation&&(f(c.Annotation),q(c.Annotation.types,function(a){f(a)}));c.setOptions({lang:{navigation:{popup:{simpleShapes:"Simple shapes",lines:"Lines",circle:"Circle",rectangle:"Rectangle",label:"Label",shapeOptions:"Shape options",typeOptions:"Details",fill:"Fill",format:"Text",strokeWidth:"Line width",stroke:"Line color",title:"Title",name:"Name",labelOptions:"Label options",
labels:"Labels",backgroundColor:"Background color",backgroundColors:"Background colors",borderColor:"Border color",borderRadius:"Border radius",borderWidth:"Border width",style:"Style",padding:"Padding",fontSize:"Font size",color:"Color",height:"Height",shapes:"Shape options"}}},navigation:{bindingsClassName:"highcharts-bindings-container",bindings:{circleAnnotation:{className:"highcharts-circle-annotation",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;
return this.chart.addAnnotation(l({langKey:"circle",type:"basicAnnotation",shapes:[{type:"circle",point:{xAxis:0,yAxis:0,x:a.xAxis[0].value,y:a.yAxis[0].value},r:5}]},b.annotationsOptions,b.bindings.circleAnnotation.annotationsOptions))},steps:[function(a,b){var c=b.options.shapes[0].point,d=this.chart.xAxis[0].toPixels(c.x);c=this.chart.yAxis[0].toPixels(c.y);var g=this.chart.inverted;b.update({shapes:[{r:Math.max(Math.sqrt(Math.pow(g?c-a.chartX:d-a.chartX,2)+Math.pow(g?d-a.chartY:c-a.chartY,2)),
5)}]})}]},rectangleAnnotation:{className:"highcharts-rectangle-annotation",start:function(a){var b=this.chart.pointer.getCoordinates(a);a=this.chart.options.navigation;var c=b.xAxis[0].value;b=b.yAxis[0].value;return this.chart.addAnnotation(l({langKey:"rectangle",type:"basicAnnotation",shapes:[{type:"path",points:[{xAxis:0,yAxis:0,x:c,y:b},{xAxis:0,yAxis:0,x:c,y:b},{xAxis:0,yAxis:0,x:c,y:b},{xAxis:0,yAxis:0,x:c,y:b}]}]},a.annotationsOptions,a.bindings.rectangleAnnotation.annotationsOptions))},steps:[function(a,
b){var c=b.options.shapes[0].points,d=this.chart.pointer.getCoordinates(a);a=d.xAxis[0].value;d=d.yAxis[0].value;c[1].x=a;c[2].x=a;c[2].y=d;c[3].y=d;b.update({shapes:[{points:c}]})}]},labelAnnotation:{className:"highcharts-label-annotation",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;return this.chart.addAnnotation(l({langKey:"label",type:"basicAnnotation",labelOptions:{format:"{y:.2f}"},labels:[{point:{xAxis:0,yAxis:0,x:a.xAxis[0].value,y:a.yAxis[0].value},
overflow:"none",crop:!0}]},b.annotationsOptions,b.bindings.labelAnnotation.annotationsOptions))}}},events:{},annotationsOptions:{}}})});n(c,"annotations/popup.js",[c["parts/Globals.js"],c["parts/Utilities.js"]],function(c,a){var f=a.addEvent,k=a.createElement,n=a.defined,e=a.isArray,t=a.isObject,u=a.isString,b=a.objectEach,h=a.pick;a=a.wrap;var r=/\d/g;a(c.Pointer.prototype,"onContainerMouseDown",function(a,b){var c=b.target&&b.target.className;u(c)&&0<=c.indexOf("highcharts-popup-field")||a.apply(this,
Array.prototype.slice.call(arguments,1))});c.Popup=function(a,b){this.init(a,b)};c.Popup.prototype={init:function(a,b){this.container=k("div",{className:"highcharts-popup"},null,a);this.lang=this.getLangpack();this.iconsURL=b;this.addCloseBtn()},addCloseBtn:function(){var a=this;var b=k("div",{className:"highcharts-popup-close"},null,this.container);b.style["background-image"]="url("+this.iconsURL+"close.svg)";["click","touchstart"].forEach(function(c){f(b,c,function(){a.closePopup()})})},addColsContainer:function(a){var b=
k("div",{className:"highcharts-popup-lhs-col"},null,a);a=k("div",{className:"highcharts-popup-rhs-col"},null,a);k("div",{className:"highcharts-popup-rhs-col-wrapper"},null,a);return{lhsCol:b,rhsCol:a}},addInput:function(a,b,c,e){var d=a.split(".");d=d[d.length-1];var g=this.lang;b="highcharts-"+b+"-"+d;b.match(r)||k("label",{innerHTML:g[d]||d,htmlFor:b},null,c);k("input",{name:b,value:e[0],type:e[1],className:"highcharts-popup-field"},null,c).setAttribute("highcharts-data-name",a)},addButton:function(a,
b,c,e,h){var d=this,g=this.closePopup,l=this.getFields;var q=k("button",{innerHTML:b},null,a);["click","touchstart"].forEach(function(a){f(q,a,function(){g.call(d);return e(l(h,c))})});return q},getFields:function(a,b){var c=a.querySelectorAll("input"),d=a.querySelectorAll("#highcharts-select-series > option:checked")[0];a=a.querySelectorAll("#highcharts-select-volume > option:checked")[0];var g,e;var f={actionType:b,linkedTo:d&&d.getAttribute("value"),fields:{}};[].forEach.call(c,function(a){e=a.getAttribute("highcharts-data-name");
(g=a.getAttribute("highcharts-data-series-id"))?f.seriesId=a.value:e?f.fields[e]=a.value:f.type=a.value});a&&(f.fields["params.volumeSeriesID"]=a.getAttribute("value"));return f},showPopup:function(){var a=this.container,b=a.querySelectorAll(".highcharts-popup-close")[0];a.innerHTML="";0<=a.className.indexOf("highcharts-annotation-toolbar")&&(a.classList.remove("highcharts-annotation-toolbar"),a.removeAttribute("style"));a.appendChild(b);a.style.display="block"},closePopup:function(){this.popup.container.style.display=
"none"},showForm:function(a,b,c,e){this.popup=b.navigationBindings.popup;this.showPopup();"indicators"===a&&this.indicators.addForm.call(this,b,c,e);"annotation-toolbar"===a&&this.annotations.addToolbar.call(this,b,c,e);"annotation-edit"===a&&this.annotations.addForm.call(this,b,c,e);"flag"===a&&this.annotations.addForm.call(this,b,c,e,!0)},getLangpack:function(){return c.getOptions().lang.navigation.popup},annotations:{addToolbar:function(a,b,c){var d=this,e=this.lang,g=this.popup.container,f=this.showForm;
-1===g.className.indexOf("highcharts-annotation-toolbar")&&(g.className+=" highcharts-annotation-toolbar");g.style.top=a.plotTop+10+"px";k("span",{innerHTML:h(e[b.langKey]||b.langKey,b.shapes&&b.shapes[0].type)},null,g);var l=this.addButton(g,e.removeButton||"remove","remove",c,g);l.className+=" highcharts-annotation-remove-button";l.style["background-image"]="url("+this.iconsURL+"destroy.svg)";l=this.addButton(g,e.editButton||"edit","edit",function(){f.call(d,"annotation-edit",a,b,c)},g);l.className+=
" highcharts-annotation-edit-button";l.style["background-image"]="url("+this.iconsURL+"edit.svg)"},addForm:function(a,b,c,e){var d=this.popup.container,g=this.lang;k("h2",{innerHTML:g[b.langKey]||b.langKey,className:"highcharts-popup-main-title"},null,d);var f=k("div",{className:"highcharts-popup-lhs-col highcharts-popup-lhs-full"},null,d);var h=k("div",{className:"highcharts-popup-bottom-row"},null,d);this.annotations.addFormFields.call(this,f,a,"",b,[],!0);this.addButton(h,e?g.addButton||"add":
g.saveButton||"save",e?"add":"save",c,d)},addFormFields:function(a,c,f,h,n,v){var d=this,g=this.annotations.addFormFields,l=this.addInput,q=this.lang,p,y;b(h,function(b,h){p=""!==f?f+"."+h:h;t(b)&&(!e(b)||e(b)&&t(b[0])?(y=q[h]||h,y.match(r)||n.push([!0,y,a]),g.call(d,a,c,p,b,n,!1)):n.push([d,p,"annotation",a,b]))});v&&(n=n.sort(function(a){return a[1].match(/format/g)?-1:1}),n.forEach(function(a){!0===a[0]?k("span",{className:"highcharts-annotation-title",innerHTML:a[1]},null,a[2]):l.apply(a[0],a.splice(1))}))}},
indicators:{addForm:function(a,b,c){var d=this.indicators,e=this.lang;this.tabs.init.call(this,a);b=this.popup.container.querySelectorAll(".highcharts-tab-item-content");this.addColsContainer(b[0]);d.addIndicatorList.call(this,a,b[0],"add");var g=b[0].querySelectorAll(".highcharts-popup-rhs-col")[0];this.addButton(g,e.addButton||"add","add",c,g);this.addColsContainer(b[1]);d.addIndicatorList.call(this,a,b[1],"edit");g=b[1].querySelectorAll(".highcharts-popup-rhs-col")[0];this.addButton(g,e.saveButton||
"save","edit",c,g);this.addButton(g,e.removeButton||"remove","remove",c,g)},addIndicatorList:function(a,c,e){var d=this,g=c.querySelectorAll(".highcharts-popup-lhs-col")[0];c=c.querySelectorAll(".highcharts-popup-rhs-col")[0];var h="edit"===e,l=h?a.series:a.options.plotOptions,m=this.indicators.addFormFields,n;var p=k("ul",{className:"highcharts-indicator-list"},null,g);var r=c.querySelectorAll(".highcharts-popup-rhs-col-wrapper")[0];b(l,function(b,c){var e=b.options;if(b.params||e&&e.params){var g=
d.indicators.getNameType(b,c),q=g.type;n=k("li",{className:"highcharts-indicator-list",innerHTML:g.name},null,p);["click","touchstart"].forEach(function(c){f(n,c,function(){m.call(d,a,h?b:l[q],g.type,r);h&&b.options&&k("input",{type:"hidden",name:"highcharts-id-"+q,value:b.options.id},null,r).setAttribute("highcharts-data-series-id",b.options.id)})})}});0<p.childNodes.length&&p.childNodes[0].click()},getNameType:function(a,b){var d=a.options,e=c.seriesTypes;e=e[b]&&e[b].prototype.nameBase||b.toUpperCase();
d&&d.type&&(b=a.options.type,e=a.name);return{name:e,type:b}},listAllSeries:function(a,b,c,e,f){a="highcharts-"+b+"-type-"+a;var d;k("label",{innerHTML:this.lang[b]||b,htmlFor:a},null,e);var g=k("select",{name:a,className:"highcharts-popup-field"},null,e);g.setAttribute("id","highcharts-select-"+b);c.series.forEach(function(a){d=a.options;!d.params&&d.id&&"highcharts-navigator-series"!==d.id&&k("option",{innerHTML:d.name||d.id,value:d.id},null,g)});n(f)&&(g.value=f)},addFormFields:function(a,b,c,
e){var d=b.params||b.options.params,g=this.indicators.getNameType;e.innerHTML="";k("h3",{className:"highcharts-indicator-title",innerHTML:g(b,c).name},null,e);k("input",{type:"hidden",name:"highcharts-type-"+c,value:c},null,e);this.indicators.listAllSeries.call(this,c,"series",a,e,b.linkedParent&&d.volumeSeriesID);d.volumeSeriesID&&this.indicators.listAllSeries.call(this,c,"volume",a,e,b.linkedParent&&b.linkedParent.options.id);this.indicators.addParamInputs.call(this,a,"params",d,c,e)},addParamInputs:function(a,
c,e,f,h){var d=this,g=this.indicators.addParamInputs,l=this.addInput,k;b(e,function(b,e){k=c+"."+e;t(b)?g.call(d,a,k,b,f,h):"params.volumeSeriesID"!==k&&l.call(d,k,f,h,[b,"text"])})},getAmount:function(){var a=0;b(this.series,function(b){var c=b.options;(b.params||c&&c.params)&&a++});return a}},tabs:{init:function(a){var b=this.tabs;a=this.indicators.getAmount.call(a);var c=b.addMenuItem.call(this,"add");b.addMenuItem.call(this,"edit",a);b.addContentItem.call(this,"add");b.addContentItem.call(this,
"edit");b.switchTabs.call(this,a);b.selectTab.call(this,c,0)},addMenuItem:function(a,b){var c=this.popup.container,d="highcharts-tab-item",e=this.lang;0===b&&(d+=" highcharts-tab-disabled");b=k("span",{innerHTML:e[a+"Button"]||a,className:d},null,c);b.setAttribute("highcharts-data-tab-type",a);return b},addContentItem:function(){return k("div",{className:"highcharts-tab-item-content"},null,this.popup.container)},switchTabs:function(a){var b=this,c;this.popup.container.querySelectorAll(".highcharts-tab-item").forEach(function(d,
e){c=d.getAttribute("highcharts-data-tab-type");"edit"===c&&0===a||["click","touchstart"].forEach(function(a){f(d,a,function(){b.tabs.deselectAll.call(b);b.tabs.selectTab.call(b,this,e)})})})},selectTab:function(a,b){var c=this.popup.container.querySelectorAll(".highcharts-tab-item-content");a.className+=" highcharts-tab-item-active";c[b].className+=" highcharts-tab-item-show"},deselectAll:function(){var a=this.popup.container,b=a.querySelectorAll(".highcharts-tab-item");a=a.querySelectorAll(".highcharts-tab-item-content");
var c;for(c=0;c<b.length;c++)b[c].classList.remove("highcharts-tab-item-active"),a[c].classList.remove("highcharts-tab-item-show")}}};f(c.NavigationBindings,"showPopup",function(a){this.popup||(this.popup=new c.Popup(this.chart.container,this.chart.options.navigation.iconsURL||this.chart.options.stockTools&&this.chart.options.stockTools.gui.iconsURL||"https://code.highcharts.com/8.0.4/gfx/stock-icons/"));this.popup.showForm(a.formType,this.chart,a.options,a.onSubmit)});f(c.NavigationBindings,"closePopup",
function(){this.popup&&this.popup.closePopup()})});n(c,"masters/modules/annotations.src.js",[],function(){})});
//# sourceMappingURL=annotations.js.map