/*
 Highcharts Gantt JS v8.0.4 (2020-04-22)

 Gantt series

 (c) 2016-2019 Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
(function(h){"object"===typeof module&&module.exports?(h["default"]=h,module.exports=h):"function"===typeof define&&define.amd?define("highcharts/modules/gantt",["highcharts"],function(G){h(G);h.Highcharts=G;return h}):h("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(h){function G(A,a,u,m){A.hasOwnProperty(a)||(A[a]=m.apply(null,u))}h=h?h._modules:{};G(h,"parts-gantt/CurrentDateIndicator.js",[h["parts/Globals.js"],h["parts/Utilities.js"],h["parts/PlotLineOrBand.js"]],function(A,a,u){var m=
a.addEvent,w=a.merge;a=a.wrap;var v={currentDateIndicator:!0,color:"#ccd6eb",width:2,label:{format:"%a, %b %d %Y, %H:%M",formatter:function(a,m){return A.dateFormat(m,a)},rotation:0,style:{fontSize:"10px"}}};m(A.Axis,"afterSetOptions",function(){var a=this.options,m=a.currentDateIndicator;m&&(m="object"===typeof m?w(v,m):w(v),m.value=new Date,a.plotLines||(a.plotLines=[]),a.plotLines.push(m))});m(u,"render",function(){this.label&&this.label.attr({text:this.getLabelText(this.options.label)})});a(u.prototype,
"getLabelText",function(a,m){var x=this.options;return x.currentDateIndicator&&x.label&&"function"===typeof x.label.formatter?(x.value=new Date,x.label.formatter.call(this,x.value,x.label.format)):a.call(this,m)})});G(h,"parts-gantt/GridAxis.js",[h["parts/Axis.js"],h["parts/Globals.js"],h["parts/Tick.js"],h["parts/Utilities.js"]],function(A,a,u,m){var w=m.addEvent,v=m.defined,K=m.erase,z=m.find,x=m.isArray,e=m.isNumber,f=m.merge,l=m.pick,r=m.timeUnits,E=m.wrap,F=a.dateFormat,C=a.Chart,q=function(d){var c=
d.options;c.labels||(c.labels={});c.labels.align=l(c.labels.align,"center");d.categories||(c.showLastLabel=!1);d.labelRotation=0;c.labels.rotation=0};"";A.prototype.getMaxLabelDimensions=function(d,c){var b={width:0,height:0};c.forEach(function(c){c=d[c];if(m.isObject(c,!0)){var n=m.isObject(c.label,!0)?c.label:{};c=n.getBBox?n.getBBox().height:0;n.textStr&&!e(n.textPxLength)&&(n.textPxLength=n.getBBox().width);n=e(n.textPxLength)?Math.round(n.textPxLength):0;b.height=Math.max(c,b.height);b.width=
Math.max(n,b.width)}});return b};a.dateFormats.W=function(d){d=new this.Date(d);var c=(this.get("Day",d)+6)%7,b=new this.Date(d.valueOf());this.set("Date",b,this.get("Date",d)-c+3);c=new this.Date(this.get("FullYear",b),0,1);4!==this.get("Day",c)&&(this.set("Month",d,0),this.set("Date",d,1+(11-this.get("Day",c))%7));return(1+Math.floor((b.valueOf()-c.valueOf())/6048E5)).toString()};a.dateFormats.E=function(d){return F("%a",d,!0).charAt(0)};w(C,"afterSetChartSize",function(){this.axes.forEach(function(d){(d.grid&&
d.grid.columns||[]).forEach(function(c){c.setAxisSize();c.setAxisTranslation()})})});w(u,"afterGetLabelPosition",function(d){var c=this.label,b=this.axis,n=b.reversed,g=b.chart,H=b.options.grid||{},f=b.options.labels,B=f.align,y=t.Side[b.side],k=d.tickmarkOffset,p=b.tickPositions,D=this.pos-k;p=e(p[d.index+1])?p[d.index+1]-k:b.max+k;var J=b.tickSize("tick",!0);k=x(J)?J[0]:0;J=J&&J[1]/2;if(!0===H.enabled){if("top"===y){H=b.top+b.offset;var I=H-k}else"bottom"===y?(I=g.chartHeight-b.bottom+b.offset,
H=I+k):(H=b.top+b.len-b.translate(n?p:D),I=b.top+b.len-b.translate(n?D:p));"right"===y?(y=g.chartWidth-b.right+b.offset,n=y+k):"left"===y?(n=b.left+b.offset,y=n-k):(y=Math.round(b.left+b.translate(n?p:D))-J,n=Math.round(b.left+b.translate(n?D:p))-J);this.slotWidth=n-y;d.pos.x="left"===B?y:"right"===B?n:y+(n-y)/2;d.pos.y=I+(H-I)/2;g=g.renderer.fontMetrics(f.style.fontSize,c.element);c=c.getBBox().height;f.useHTML?d.pos.y+=g.b+-(c/2):(c=Math.round(c/g.h),d.pos.y+=(g.b-(g.h-g.f))/2+-((c-1)*g.h/2));d.pos.x+=
b.horiz&&f.x||0}});var g=function(){function d(c){this.axis=c}d.prototype.isOuterAxis=function(){var c=this.axis,b=c.grid.columnIndex,d=c.linkedParent&&c.linkedParent.grid.columns||c.grid.columns,g=b?c.linkedParent:c,H=-1,t=0;c.chart[c.coll].forEach(function(b,d){b.side!==c.side||b.options.isInternal||(t=d,b===g&&(H=d))});return t===H&&(e(b)?d.length===b:!0)};return d}(),t=function(){function d(){}d.compose=function(c){A.keepProps.push("grid");E(c.prototype,"unsquish",d.wrapUnsquish);w(c,"init",d.onInit);
w(c,"afterGetOffset",d.onAfterGetOffset);w(c,"afterGetTitlePosition",d.onAfterGetTitlePosition);w(c,"afterInit",d.onAfterInit);w(c,"afterRender",d.onAfterRender);w(c,"afterSetAxisTranslation",d.onAfterSetAxisTranslation);w(c,"afterSetOptions",d.onAfterSetOptions);w(c,"afterSetOptions",d.onAfterSetOptions2);w(c,"afterSetScale",d.onAfterSetScale);w(c,"afterTickSize",d.onAfterTickSize);w(c,"trimTicks",d.onTrimTicks);w(c,"destroy",d.onDestroy)};d.onAfterGetOffset=function(){var c=this.grid;(c&&c.columns||
[]).forEach(function(b){b.getOffset()})};d.onAfterGetTitlePosition=function(c){if(!0===(this.options.grid||{}).enabled){var b=this.axisTitle,n=this.height,g=this.horiz,H=this.left,t=this.offset,B=this.opposite,y=this.options.title,k=void 0===y?{}:y;y=this.top;var p=this.width,D=this.tickSize(),J=b&&b.getBBox().width,I=k.x||0,e=k.y||0,f=l(k.margin,g?5:10);b=this.chart.renderer.fontMetrics(k.style&&k.style.fontSize,b).f;D=(g?y+n:H)+D[0]/2*(B?-1:1)*(g?1:-1)+(this.side===d.Side.bottom?b:0);c.titlePosition.x=
g?H-J/2-f+I:D+(B?p:0)+t+I;c.titlePosition.y=g?D-(B?n:0)+(B?b:-b)/2+t+e:y-f+e}};d.onAfterInit=function(){var c=this.chart,b=this.options.grid;b=void 0===b?{}:b;var d=this.userOptions;b.enabled&&(q(this),E(this,"labelFormatter",function(b){var c=this.axis,k=this.value,d=c.tickPositions,n=(c.isLinked?c.linkedParent:c).series[0],g=k===d[0];d=k===d[d.length-1];n=n&&z(n.options.data,function(b){return b[c.isXAxis?"x":"y"]===k});this.isFirst=g;this.isLast=d;this.point=n;return b.call(this)}));if(b.columns)for(var g=
this.grid.columns=[],t=this.grid.columnIndex=0;++t<b.columns.length;){var e=f(d,b.columns[b.columns.length-t-1],{linkedTo:0,type:"category"});delete e.grid.columns;e=new A(this.chart,e);e.grid.isColumn=!0;e.grid.columnIndex=t;K(c.axes,e);K(c[this.coll],e);g.push(e)}};d.onAfterRender=function(){var c=this.grid,b=this.options,n=this.chart.renderer;if(!0===(b.grid||{}).enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,this.tickPositions);this.rightWall&&this.rightWall.destroy();
if(this.grid&&this.grid.isOuterAxis()&&this.axisLine){var g=b.lineWidth;if(g){var t=this.getLinePath(g),e=t[0],B=t[1],y=(this.tickSize("tick")[0]-1)*(this.side===d.Side.top||this.side===d.Side.left?-1:1);"M"===e[0]&&"L"===B[0]&&(this.horiz?(e[2]+=y,B[2]+=y):(e[1]+=y,B[1]+=y));this.grid.axisLineExtra?this.grid.axisLineExtra.animate({d:t}):(this.grid.axisLineExtra=n.path(t).attr({zIndex:7}).addClass("highcharts-axis-line").add(this.axisGroup),n.styledMode||this.grid.axisLineExtra.attr({stroke:b.lineColor,
"stroke-width":g}));this.axisLine[this.showAxis?"show":"hide"](!0)}}(c&&c.columns||[]).forEach(function(b){b.render()})}};d.onAfterSetAxisTranslation=function(){var c=this.tickPositions&&this.tickPositions.info,b=this.options,d=b.grid||{},g=this.userOptions.labels||{};this.horiz&&(!0===d.enabled&&this.series.forEach(function(b){b.options.pointRange=0}),c&&b.dateTimeLabelFormats&&b.labels&&!v(g.align)&&(!1===b.dateTimeLabelFormats[c.unitName].range||1<c.count)&&(b.labels.align="left",v(g.x)||(b.labels.x=
3)))};d.onAfterSetOptions=function(c){var b=this.options;c=c.userOptions;var d=b&&m.isObject(b.grid,!0)?b.grid:{};if(!0===d.enabled){var g=f(!0,{className:"highcharts-grid-axis "+(c.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],
["second",[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},c);"xAxis"===this.coll&&(v(c.linkedTo)&&!v(c.tickPixelInterval)&&(g.tickPixelInterval=350),v(c.tickPixelInterval)||!v(c.linkedTo)||v(c.tickPositioner)||v(c.tickInterval)||(g.tickPositioner=function(b,c){var d=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(d){var n,k=g.units;for(n=0;n<k.length;n++)if(k[n][0]===d.unitName){var p=n;break}if(k[p+1]){var D=
k[p+1][0];var J=(k[p+1][1]||[1])[0]}else"year"===d.unitName&&(D="year",J=10*d.count);d=r[D];this.tickInterval=d*J;return this.getTimeTicks({unitRange:d,count:J,unitName:D},b,c,this.options.startOfWeek)}}));f(!0,this.options,g);this.horiz&&(b.minPadding=l(c.minPadding,0),b.maxPadding=l(c.maxPadding,0));e(b.grid.borderWidth)&&(b.tickWidth=b.lineWidth=d.borderWidth)}};d.onAfterSetOptions2=function(c){c=(c=c.userOptions)&&c.grid||{};var b=c.columns;c.enabled&&b&&f(!0,this.options,b[b.length-1])};d.onAfterSetScale=
function(){(this.grid.columns||[]).forEach(function(c){c.setScale()})};d.onAfterTickSize=function(c){var b=A.defaultLeftAxisOptions,d=this.horiz,g=this.maxLabelDimensions,t=this.options.grid;t=void 0===t?{}:t;t.enabled&&g&&(b=2*Math.abs(b.labels.x),d=d?t.cellHeight||b+g.height:b+g.width,x(c.tickSize)?c.tickSize[0]=d:c.tickSize=[d])};d.onDestroy=function(c){var b=this.grid;(b.columns||[]).forEach(function(b){b.destroy(c.keepEvents)});b.columns=void 0};d.onInit=function(c){c=c.userOptions||{};var b=
c.grid||{};b.enabled&&v(b.borderColor)&&(c.tickColor=c.lineColor=b.borderColor);this.grid||(this.grid=new g(this))};d.onTrimTicks=function(){var c=this.options,b=this.categories,d=this.tickPositions,g=d[0],t=d[d.length-1],e=this.linkedParent&&this.linkedParent.min||this.min,B=this.linkedParent&&this.linkedParent.max||this.max,y=this.tickInterval;!0!==(c.grid||{}).enabled||b||!this.horiz&&!this.isLinked||(g<e&&g+y>e&&!c.startOnTick&&(d[0]=e),t>B&&t-y<B&&!c.endOnTick&&(d[d.length-1]=B))};d.wrapUnsquish=
function(c){var b=this.options.grid;return!0===(void 0===b?{}:b).enabled&&this.categories?this.tickInterval:c.apply(this,Array.prototype.slice.call(arguments,1))};return d}();(function(d){d=d.Side||(d.Side={});d[d.top=0]="top";d[d.right=1]="right";d[d.bottom=2]="bottom";d[d.left=3]="left"})(t||(t={}));t.compose(A);return t});G(h,"modules/static-scale.src.js",[h["parts/Globals.js"],h["parts/Utilities.js"]],function(A,a){var u=a.addEvent,m=a.defined,w=a.isNumber,v=a.pick;a=A.Chart;u(A.Axis,"afterSetOptions",
function(){var a=this.chart.options&&this.chart.options.chart;!this.horiz&&w(this.options.staticScale)&&(!a.height||a.scrollablePlotArea&&a.scrollablePlotArea.minHeight)&&(this.staticScale=this.options.staticScale)});a.prototype.adjustHeight=function(){"adjustHeight"!==this.redrawTrigger&&((this.axes||[]).forEach(function(a){var u=a.chart,x=!!u.initiatedScale&&u.options.animation,e=a.options.staticScale;if(a.staticScale&&m(a.min)){var f=v(a.brokenAxis&&a.brokenAxis.unitLength,a.max+a.tickInterval-
a.min)*e;f=Math.max(f,e);e=f-u.plotHeight;1<=Math.abs(e)&&(u.plotHeight=f,u.redrawTrigger="adjustHeight",u.setSize(void 0,u.chartHeight+e,x));a.series.forEach(function(e){(e=e.sharedClipKey&&u[e.sharedClipKey])&&e.attr({height:u.plotHeight})})}}),this.initiatedScale=!0);this.redrawTrigger=null};u(a,"render",a.prototype.adjustHeight)});G(h,"mixins/tree-series.js",[h["parts/Color.js"],h["parts/Utilities.js"]],function(A,a){var u=a.extend,m=a.isArray,w=a.isNumber,v=a.isObject,h=a.merge,z=a.pick;return{getColor:function(a,
e){var f=e.index,l=e.mapOptionsToLevel,r=e.parentColor,E=e.parentColorIndex,x=e.series,C=e.colors,q=e.siblings,g=x.points,t=x.chart.options.chart,d;if(a){g=g[a.i];a=l[a.level]||{};if(l=g&&a.colorByPoint){var c=g.index%(C?C.length:t.colorCount);var b=C&&C[c]}if(!x.chart.styledMode){C=g&&g.options.color;t=a&&a.color;if(d=r)d=(d=a&&a.colorVariation)&&"brightness"===d.key?A.parse(r).brighten(f/q*d.to).get():r;d=z(C,t,b,d,x.color)}var n=z(g&&g.options.colorIndex,a&&a.colorIndex,c,E,e.colorIndex)}return{color:d,
colorIndex:n}},getLevelOptions:function(a){var e=null;if(v(a)){e={};var f=w(a.from)?a.from:1;var l=a.levels;var r={};var E=v(a.defaults)?a.defaults:{};m(l)&&(r=l.reduce(function(e,a){if(v(a)&&w(a.level)){var q=h({},a);var g="boolean"===typeof q.levelIsConstant?q.levelIsConstant:E.levelIsConstant;delete q.levelIsConstant;delete q.level;a=a.level+(g?0:f-1);v(e[a])?u(e[a],q):e[a]=q}return e},{}));l=w(a.to)?a.to:1;for(a=0;a<=l;a++)e[a]=h({},E,v(r[a])?r[a]:{})}return e},setTreeValues:function l(e,a){var f=
a.before,E=a.idRoot,m=a.mapIdToNode[E],C=a.points[e.i],q=C&&C.options||{},g=0,t=[];u(e,{levelDynamic:e.level-(("boolean"===typeof a.levelIsConstant?a.levelIsConstant:1)?0:m.level),name:z(C&&C.name,""),visible:E===e.id||("boolean"===typeof a.visible?a.visible:!1)});"function"===typeof f&&(e=f(e,a));e.children.forEach(function(d,c){var b=u({},a);u(b,{index:c,siblings:e.children.length,visible:e.visible});d=l(d,b);t.push(d);d.visible&&(g+=d.val)});e.visible=0<g||e.visible;f=z(q.value,g);u(e,{children:t,
childrenTotal:g,isLeaf:e.visible&&!g,val:f});return e},updateRootId:function(e){if(v(e)){var a=v(e.options)?e.options:{};a=z(e.rootNode,a.rootId,"");v(e.userOptions)&&(e.userOptions.rootId=a);e.rootNode=a}return a}}});G(h,"parts-gantt/Tree.js",[h["parts/Utilities.js"]],function(h){var a=h.extend,u=h.isNumber,m=h.pick,w=function(a,u){var x=a.reduce(function(e,a){var f=m(a.parent,"");"undefined"===typeof e[f]&&(e[f]=[]);e[f].push(a);return e},{});Object.keys(x).forEach(function(e,a){var f=x[e];""!==
e&&-1===u.indexOf(e)&&(f.forEach(function(e){a[""].push(e)}),delete a[e])});return x},v=function(w,h,x,e,f,l){var r=0,E=0,F=l&&l.after,C=l&&l.before;h={data:e,depth:x-1,id:w,level:x,parent:h};var q,g;"function"===typeof C&&C(h,l);C=(f[w]||[]).map(function(t){var d=v(t.id,w,x+1,t,f,l),c=t.start;t=!0===t.milestone?c:t.end;q=!u(q)||c<q?c:q;g=!u(g)||t>g?t:g;r=r+1+d.descendants;E=Math.max(d.height+1,E);return d});e&&(e.start=m(e.start,q),e.end=m(e.end,g));a(h,{children:C,descendants:r,height:E});"function"===
typeof F&&F(h,l);return h};return{getListOfParents:w,getNode:v,getTree:function(a,m){var x=a.map(function(a){return a.id});a=w(a,x);return v("",null,1,null,a,m)}}});G(h,"modules/broken-axis.src.js",[h["parts/Axis.js"],h["parts/Globals.js"],h["parts/Utilities.js"],h["parts/Stacking.js"]],function(h,a,u,m){var w=u.addEvent,v=u.find,A=u.fireEvent,z=u.isArray,x=u.isNumber,e=u.pick,f=a.Series,l=function(){function a(a){this.hasBreaks=!1;this.axis=a}a.isInBreak=function(a,e){var f=a.repeat||Infinity,q=
a.from,g=a.to-a.from;e=e>=q?(e-q)%f:f-(q-e)%f;return a.inclusive?e<=g:e<g&&0!==e};a.lin2Val=function(e){var f=this.brokenAxis;f=f&&f.breakArray;if(!f)return e;var l;for(l=0;l<f.length;l++){var q=f[l];if(q.from>=e)break;else q.to<e?e+=q.len:a.isInBreak(q,e)&&(e+=q.len)}return e};a.val2Lin=function(e){var f=this.brokenAxis;f=f&&f.breakArray;if(!f)return e;var l=e,q;for(q=0;q<f.length;q++){var g=f[q];if(g.to<=e)l-=g.len;else if(g.from>=e)break;else if(a.isInBreak(g,e)){l-=e-g.from;break}}return l};a.prototype.findBreakAt=
function(a,e){return v(e,function(e){return e.from<a&&a<e.to})};a.prototype.isInAnyBreak=function(f,l){var r=this.axis,q=r.options.breaks,g=q&&q.length,t;if(g){for(;g--;)if(a.isInBreak(q[g],f)){var d=!0;t||(t=e(q[g].showPoints,!r.isXAxis))}var c=d&&l?d&&!t:d}return c};a.prototype.setBreaks=function(f,l){var r=this,q=r.axis,g=z(f)&&!!f.length;q.isDirty=r.hasBreaks!==g;r.hasBreaks=g;q.options.breaks=q.userOptions.breaks=f;q.forceRedraw=!0;q.series.forEach(function(g){g.isDirty=!0});g||q.val2lin!==a.val2Lin||
(delete q.val2lin,delete q.lin2val);g&&(q.userOptions.ordinal=!1,q.lin2val=a.lin2Val,q.val2lin=a.val2Lin,q.setExtremes=function(g,d,c,b,n){if(r.hasBreaks){for(var a,e=this.options.breaks;a=r.findBreakAt(g,e);)g=a.to;for(;a=r.findBreakAt(d,e);)d=a.from;d<g&&(d=g)}h.prototype.setExtremes.call(this,g,d,c,b,n)},q.setAxisTranslation=function(g){h.prototype.setAxisTranslation.call(this,g);r.unitLength=null;if(r.hasBreaks){g=q.options.breaks||[];var d=[],c=[],b=0,n,t=q.userMin||q.min,f=q.userMax||q.max,
l=e(q.pointRangePadding,0),B;g.forEach(function(b){n=b.repeat||Infinity;a.isInBreak(b,t)&&(t+=b.to%n-t%n);a.isInBreak(b,f)&&(f-=f%n-b.from%n)});g.forEach(function(b){k=b.from;for(n=b.repeat||Infinity;k-n>t;)k-=n;for(;k<t;)k+=n;for(B=k;B<f;B+=n)d.push({value:B,move:"in"}),d.push({value:B+(b.to-b.from),move:"out",size:b.breakSize})});d.sort(function(b,c){return b.value===c.value?("in"===b.move?0:1)-("in"===c.move?0:1):b.value-c.value});var y=0;var k=t;d.forEach(function(d){y+="in"===d.move?1:-1;1===
y&&"in"===d.move&&(k=d.value);0===y&&(c.push({from:k,to:d.value,len:d.value-k-(d.size||0)}),b+=d.value-k-(d.size||0))});q.breakArray=r.breakArray=c;r.unitLength=f-t-b+l;A(q,"afterBreaks");q.staticScale?q.transA=q.staticScale:r.unitLength&&(q.transA*=(f-q.min+l)/r.unitLength);l&&(q.minPixelPadding=q.transA*q.minPointOffset);q.min=t;q.max=f}});e(l,!0)&&q.chart.redraw()};return a}();a=function(){function a(){}a.compose=function(a,r){a.keepProps.push("brokenAxis");var u=f.prototype;u.drawBreaks=function(a,
g){var t=this,d=t.points,c,b,n,f;if(a&&a.brokenAxis&&a.brokenAxis.hasBreaks){var l=a.brokenAxis;g.forEach(function(g){c=l&&l.breakArray||[];b=a.isXAxis?a.min:e(t.options.threshold,a.min);d.forEach(function(d){f=e(d["stack"+g.toUpperCase()],d[g]);c.forEach(function(c){if(x(b)&&x(f)){n=!1;if(b<c.from&&f>c.to||b>c.from&&f<c.from)n="pointBreak";else if(b<c.from&&f>c.from&&f<c.to||b>c.from&&f>c.to&&f<c.from)n="pointInBreak";n&&A(a,n,{point:d,brk:c})}})})})}};u.gappedPath=function(){var a=this.currentDataGrouping,
g=a&&a.gapSize;a=this.options.gapSize;var e=this.points.slice(),d=e.length-1,c=this.yAxis,b;if(a&&0<d)for("value"!==this.options.gapUnit&&(a*=this.basePointRange),g&&g>a&&g>=this.basePointRange&&(a=g),b=void 0;d--;)b&&!1!==b.visible||(b=e[d+1]),g=e[d],!1!==b.visible&&!1!==g.visible&&(b.x-g.x>a&&(b=(g.x+b.x)/2,e.splice(d+1,0,{isNull:!0,x:b}),c.stacking&&this.options.stacking&&(b=c.stacking.stacks[this.stackKey][b]=new m(c,c.options.stackLabels,!1,b,this.stack),b.total=0)),b=g);return this.getGraphPath(e)};
w(a,"init",function(){this.brokenAxis||(this.brokenAxis=new l(this))});w(a,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)});w(a,"afterSetTickPositions",function(){var a=this.brokenAxis;if(a&&a.hasBreaks){var g=this.tickPositions,e=this.tickPositions.info,d=[],c;for(c=0;c<g.length;c++)a.isInAnyBreak(g[c])||d.push(g[c]);this.tickPositions=d;this.tickPositions.info=e}});w(a,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&
(this.options.ordinal=!1)});w(r,"afterGeneratePoints",function(){var a=this.options.connectNulls,g=this.points,e=this.xAxis,d=this.yAxis;if(this.isDirty)for(var c=g.length;c--;){var b=g[c],n=!(null===b.y&&!1===a)&&(e&&e.brokenAxis&&e.brokenAxis.isInAnyBreak(b.x,!0)||d&&d.brokenAxis&&d.brokenAxis.isInAnyBreak(b.y,!0));b.visible=n?!1:!1!==b.options.visible}});w(r,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,e(this.pointArrayMap,["y"]))})};return a}();a.compose(h,
f);return a});G(h,"parts-gantt/TreeGrid.js",[h["parts/Globals.js"],h["mixins/tree-series.js"],h["parts/Tick.js"],h["parts-gantt/Tree.js"],h["parts/Utilities.js"]],function(h,a,u,m,w){var v=w.addEvent,A=w.defined,z=w.fireEvent,x=w.extend,e=w.isNumber,f=w.isString,l=w.merge,r=w.pick,E=w.wrap,F=function(b){return Array.prototype.slice.call(b,1)},C=w.find,q=a.getLevelOptions,g=function(b){return w.isObject(b,!0)};h=h.Axis;a=function(b,c){var d;for(d in c)if(Object.hasOwnProperty.call(c,d)){var p=c[d];
E(b,d,p)}};var t=function(b,c){var d=b.collapseStart;b=b.collapseEnd;b>=c&&(d-=.5);return{from:d,to:b,showPoints:!1}},d=function(b){return Object.keys(b.mapOfPosToGridNode).reduce(function(c,d){d=+d;!(b.min<=d&&b.max>=d)||b.brokenAxis&&b.brokenAxis.isInAnyBreak(d)||c.push(d);return c},[])},c=function(b,c){var d=b.options.breaks||[],p=t(c,b.max);return d.some(function(b){return b.from===p.from&&b.to===p.to})},b=function(b,c){var d=b.options.breaks||[];b=t(c,b.max);d.push(b);return d},n=function(b,
c){var d=b.options.breaks||[],p=t(c,b.max);return d.reduce(function(b,c){c.to===p.to&&c.from===p.from||b.push(c);return b},[])},L=function(b,c){var d=b.labelIcon,p=!d,g=c.renderer,n=c.xy,a=c.options,y=a.width,f=a.height,t=n.x-y/2-a.padding;n=n.y-f/2;var l=c.collapsed?90:180,L=c.show&&e(n);p&&(b.labelIcon=d=g.path(g.symbols[a.type](a.x,a.y,y,f)).addClass("highcharts-label-icon").add(c.group));L||d.attr({y:-9999});g.styledMode||d.attr({"stroke-width":1,fill:r(c.color,"#666666")}).css({cursor:"pointer",
stroke:a.lineColor,strokeWidth:a.lineWidth});d[p?"attr":"animate"]({translateX:t,translateY:n,rotation:l})},H=function(b,c,d){var k=[],n=[],a={},e={},y=-1,t="boolean"===typeof c?c:!1;b=m.getTree(b,{after:function(b){b=e[b.pos];var c=0,d=0;b.children.forEach(function(b){d+=b.descendants+1;c=Math.max(b.height+1,c)});b.descendants=d;b.height=c;b.collapsed&&n.push(b)},before:function(b){var c=g(b.data)?b.data:{},d=f(c.name)?c.name:"",p=a[b.parent];p=g(p)?e[p.pos]:null;var n=function(b){return b.name===
d},D;t&&g(p)&&(D=C(p.children,n))?(n=D.pos,D.nodes.push(b)):n=y++;e[n]||(e[n]=D={depth:p?p.depth+1:0,name:d,nodes:[b],children:[],pos:n},-1!==n&&k.push(d),g(p)&&p.children.push(D));f(b.id)&&(a[b.id]=b);!0===c.collapsed&&(D.collapsed=!0);b.pos=n}});e=function(b,c){var d=function(b,k,p){var n=k+(-1===k?0:c-1),a=(n-k)/2,e=k+a;b.nodes.forEach(function(b){var c=b.data;g(c)&&(c.y=k+c.seriesIndex,delete c.seriesIndex);b.pos=e});p[e]=b;b.pos=e;b.tickmarkOffset=a+.5;b.collapseStart=n+.5;b.children.forEach(function(b){d(b,
n+1,p);n=b.collapseEnd-.5});b.collapseEnd=n+.5;return p};return d(b["-1"],-1,{})}(e,d);return{categories:k,mapOfIdToNode:a,mapOfPosToGridNode:e,collapsedNodes:n,tree:b}},O=function(c){c.target.axes.filter(function(b){return"treegrid"===b.options.type}).forEach(function(d){var k=d.options||{},p=k.labels,n,a=k.uniqueNames,e=0;if(!d.mapOfPosToGridNode||d.series.some(function(b){return!b.hasRendered||b.isDirtyData||b.isDirty})){k=d.series.reduce(function(b,c){c.visible&&(c.options.data.forEach(function(c){g(c)&&
(c.seriesIndex=e,b.push(c))}),!0===a&&e++);return b},[]);var y=H(k,a,!0===a?e:1);d.categories=y.categories;d.mapOfPosToGridNode=y.mapOfPosToGridNode;d.hasNames=!0;d.tree=y.tree;d.series.forEach(function(b){var c=b.options.data.map(function(b){return g(b)?l(b):b});b.visible&&b.setData(c,!1)});d.mapOptionsToLevel=q({defaults:p,from:1,levels:p.levels,to:d.tree.height});"beforeRender"===c.type&&(n=v(d,"foundExtremes",function(){y.collapsedNodes.forEach(function(c){c=b(d,c);d.brokenAxis&&d.brokenAxis.setBreaks(c,
!1)});n()}))}})};a(h.prototype,{init:function(b,c,d){var k="treegrid"===d.type;k&&(v(c,"beforeRender",O),v(c,"beforeRedraw",O),d=l({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},d,{reversed:!0,grid:{columns:void 0}}));b.apply(this,[c,d]);k&&(this.hasNames=!0,this.options.showLastLabel=!0)},getMaxLabelDimensions:function(b){var c=this.options,d=c&&c.labels;c=d&&e(d.indentation)?
c.labels.indentation:0;d=b.apply(this,F(arguments));if("treegrid"===this.options.type&&this.mapOfPosToGridNode){var p=this.mapOfPosToGridNode[-1].height;d.width+=c*(p-1)}return d},generateTick:function(b,c){var d=g(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},p=this.ticks,n=p[c],a;if("treegrid"===this.options.type){var e=this.mapOfPosToGridNode[c];(d=d[e.depth])&&(a={labels:d});n?(n.parameters.category=e.name,n.options=a,n.addLabel()):p[c]=new u(this,c,null,void 0,{category:e.name,tickmarkOffset:e.tickmarkOffset,
options:a})}else b.apply(this,F(arguments))},setTickInterval:function(b){var c=this.options;"treegrid"===c.type?(this.min=r(this.userMin,c.min,this.dataMin),this.max=r(this.userMax,c.max,this.dataMax),z(this,"foundExtremes"),this.setAxisTranslation(!0),this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.mapOfPosToGridNode?d(this):[]):b.apply(this,F(arguments))}});a(u.prototype,{getLabelPosition:function(b,c,d,n,a,f,t,l,L){var k=r(this.options&&this.options.labels,f);f=this.pos;var p=
this.axis,D="treegrid"===p.options.type;b=b.apply(this,[c,d,n,a,k,t,l,L]);D&&(c=k&&g(k.symbol)?k.symbol:{},k=k&&e(k.indentation)?k.indentation:0,f=(f=(p=p.mapOfPosToGridNode)&&p[f])&&f.depth||1,b.x+=c.width+2*c.padding+(f-1)*k);return b},renderLabel:function(b){var d=this,k=d.pos,n=d.axis,a=d.label,e=n.mapOfPosToGridNode,f=n.options,t=r(d.options&&d.options.labels,f&&f.labels),l=t&&g(t.symbol)?t.symbol:{},H=(e=e&&e[k])&&e.depth;f="treegrid"===f.type;var q=!(!a||!a.element),B=-1<n.tickPositions.indexOf(k);
k=n.chart.styledMode;f&&e&&q&&a.addClass("highcharts-treegrid-node-level-"+H);b.apply(d,F(arguments));f&&e&&q&&0<e.descendants&&(n=c(n,e),L(d,{color:!k&&a.styles.color,collapsed:n,group:a.parentGroup,options:l,renderer:a.renderer,show:B,xy:a.xy}),l="highcharts-treegrid-node-"+(n?"expanded":"collapsed"),a.addClass("highcharts-treegrid-node-"+(n?"collapsed":"expanded")).removeClass(l),k||a.css({cursor:"pointer"}),[a,d.labelIcon].forEach(function(b){b.attachedTreeGridEvents||(v(b.element,"mouseover",
function(){a.addClass("highcharts-treegrid-node-active");a.renderer.styledMode||a.css({textDecoration:"underline"})}),v(b.element,"mouseout",function(){var b=A(t.style)?t.style:{};a.removeClass("highcharts-treegrid-node-active");a.renderer.styledMode||a.css({textDecoration:b.textDecoration})}),v(b.element,"click",function(){d.toggleCollapse()}),b.attachedTreeGridEvents=!0)}))}});x(u.prototype,{collapse:function(c){var d=this.axis,k=d.brokenAxis;d=b(d,d.mapOfPosToGridNode[this.pos]);k&&k.setBreaks(d,
r(c,!0))},expand:function(b){var c=this.axis,d=c.brokenAxis;c=n(c,c.mapOfPosToGridNode[this.pos]);d&&d.setBreaks(c,r(b,!0))},toggleCollapse:function(d){var g=this.axis,k=g.brokenAxis,p=g.mapOfPosToGridNode[this.pos];g=c(g,p)?n(g,p):b(g,p);k&&k.setBreaks(g,r(d,!0))}});h.prototype.utils={getNode:m.getNode}});G(h,"parts-gantt/PathfinderAlgorithms.js",[h["parts/Utilities.js"]],function(h){function a(a,e,r){r=r||0;var f=a.length-1;e-=1e-7;for(var l,m;r<=f;)if(l=f+r>>1,m=e-a[l].xMin,0<m)r=l+1;else if(0>
m)f=l-1;else return l;return 0<r?r-1:0}function u(e,l){for(var f=a(e,l.x+1)+1;f--;){var m;if(m=e[f].xMax>=l.x)m=e[f],m=l.x<=m.xMax&&l.x>=m.xMin&&l.y<=m.yMax&&l.y>=m.yMin;if(m)return f}return-1}function m(a){var e=[];if(a.length){e.push(["M",a[0].start.x,a[0].start.y]);for(var f=0;f<a.length;++f)e.push(["L",a[f].end.x,a[f].end.y])}return e}function w(a,e){a.yMin=x(a.yMin,e.yMin);a.yMax=z(a.yMax,e.yMax);a.xMin=x(a.xMin,e.xMin);a.xMax=z(a.xMax,e.xMax)}var v=h.extend,A=h.pick,z=Math.min,x=Math.max,e=
Math.abs;return{straight:function(a,e){return{path:[["M",a.x,a.y],["L",e.x,e.y]],obstacles:[{start:a,end:e}]}},simpleConnect:v(function(a,l,r){function f(b,c,d,a,g){b={x:b.x,y:b.y};b[c]=d[a||c]+(g||0);return b}function x(b,c,d){var a=e(c[d]-b[d+"Min"])>e(c[d]-b[d+"Max"]);return f(c,d,b,d+(a?"Max":"Min"),a?1:-1)}var h=[],q=A(r.startDirectionX,e(l.x-a.x)>e(l.y-a.y))?"x":"y",g=r.chartObstacles,t=u(g,a);r=u(g,l);if(-1<r){var d=g[r];r=x(d,l,q);d={start:r,end:l};var c=r}else c=l;-1<t&&(g=g[t],r=x(g,a,q),
h.push({start:a,end:r}),r[q]>=a[q]===r[q]>=c[q]&&(q="y"===q?"x":"y",l=a[q]<l[q],h.push({start:r,end:f(r,q,g,q+(l?"Max":"Min"),l?1:-1)}),q="y"===q?"x":"y"));a=h.length?h[h.length-1].end:a;r=f(a,q,c);h.push({start:a,end:r});q=f(r,"y"===q?"x":"y",c);h.push({start:r,end:q});h.push(d);return{path:m(h),obstacles:h}},{requiresObstacles:!0}),fastAvoid:v(function(f,l,r){function h(b,c,d){var k,n=b.x<c.x?1:-1;if(b.x<c.x){var g=b;var p=c}else g=c,p=b;if(b.y<c.y){var e=b;var D=c}else e=c,D=b;for(k=0>n?z(a(B,
p.x),B.length-1):0;B[k]&&(0<n&&B[k].xMin<=p.x||0>n&&B[k].xMax>=g.x);){if(B[k].xMin<=p.x&&B[k].xMax>=g.x&&B[k].yMin<=D.y&&B[k].yMax>=e.y)return d?{y:b.y,x:b.x<c.x?B[k].xMin-1:B[k].xMax+1,obstacle:B[k]}:{x:b.x,y:b.y<c.y?B[k].yMin-1:B[k].yMax+1,obstacle:B[k]};k+=n}return c}function v(b,c,d,k,a){var n=a.soft,g=a.hard,p=k?"x":"y",t={x:c.x,y:c.y},D={x:c.x,y:c.y};a=b[p+"Max"]>=n[p+"Max"];n=b[p+"Min"]<=n[p+"Min"];var f=b[p+"Max"]>=g[p+"Max"];g=b[p+"Min"]<=g[p+"Min"];var y=e(b[p+"Min"]-c[p]),l=e(b[p+"Max"]-
c[p]);d=10>e(y-l)?c[p]<d[p]:l<y;D[p]=b[p+"Min"];t[p]=b[p+"Max"];b=h(c,D,k)[p]!==D[p];c=h(c,t,k)[p]!==t[p];d=b?c?d:!0:c?!1:d;d=n?a?d:!0:a?!1:d;return g?f?d:!0:f?!1:d}function C(b,d,k){if(b.x===d.x&&b.y===d.y)return[];var a=k?"x":"y",g=r.obstacleOptions.margin;var p={soft:{xMin:n,xMax:L,yMin:H,yMax:O},hard:r.hardBounds};var e=u(B,b);if(-1<e){e=B[e];p=v(e,b,d,k,p);w(e,r.hardBounds);var t=k?{y:b.y,x:e[p?"xMax":"xMin"]+(p?1:-1)}:{x:b.x,y:e[p?"yMax":"yMin"]+(p?1:-1)};var f=u(B,t);-1<f&&(f=B[f],w(f,r.hardBounds),
t[a]=p?x(e[a+"Max"]-g+1,(f[a+"Min"]+e[a+"Max"])/2):z(e[a+"Min"]+g-1,(f[a+"Max"]+e[a+"Min"])/2),b.x===t.x&&b.y===t.y?(c&&(t[a]=p?x(e[a+"Max"],f[a+"Max"])+1:z(e[a+"Min"],f[a+"Min"])-1),c=!c):c=!1);b=[{start:b,end:t}]}else a=h(b,{x:k?d.x:b.x,y:k?b.y:d.y},k),b=[{start:b,end:{x:a.x,y:a.y}}],a[k?"x":"y"]!==d[k?"x":"y"]&&(p=v(a.obstacle,a,d,!k,p),w(a.obstacle,r.hardBounds),p={x:k?a.x:a.obstacle[p?"xMax":"xMin"]+(p?1:-1),y:k?a.obstacle[p?"yMax":"yMin"]+(p?1:-1):a.y},k=!k,b=b.concat(C({x:a.x,y:a.y},p,k)));
return b=b.concat(C(b[b.length-1].end,d,!k))}function q(b,c,d){var k=z(b.xMax-c.x,c.x-b.xMin)<z(b.yMax-c.y,c.y-b.yMin);d=v(b,c,d,k,{soft:r.hardBounds,hard:r.hardBounds});return k?{y:c.y,x:b[d?"xMax":"xMin"]+(d?1:-1)}:{x:c.x,y:b[d?"yMax":"yMin"]+(d?1:-1)}}var g=A(r.startDirectionX,e(l.x-f.x)>e(l.y-f.y)),t=g?"x":"y",d=[],c=!1,b=r.obstacleMetrics,n=z(f.x,l.x)-b.maxWidth-10,L=x(f.x,l.x)+b.maxWidth+10,H=z(f.y,l.y)-b.maxHeight-10,O=x(f.y,l.y)+b.maxHeight+10,B=r.chartObstacles;var y=a(B,n);b=a(B,L);B=B.slice(y,
b+1);if(-1<(b=u(B,l))){var k=q(B[b],l,f);d.push({end:l,start:k});l=k}for(;-1<(b=u(B,l));)y=0>l[t]-f[t],k={x:l.x,y:l.y},k[t]=B[b][y?t+"Max":t+"Min"]+(y?1:-1),d.push({end:l,start:k}),l=k;f=C(f,l,g);f=f.concat(d.reverse());return{path:m(f),obstacles:f}},{requiresObstacles:!0})}});G(h,"parts-gantt/ArrowSymbols.js",[h["parts/Globals.js"]],function(h){h.SVGRenderer.prototype.symbols.arrow=function(a,h,m,w){return[["M",a,h+w/2],["L",a+m,h],["L",a,h+w/2],["L",a+m,h+w]]};h.SVGRenderer.prototype.symbols["arrow-half"]=
function(a,u,m,w){return h.SVGRenderer.prototype.symbols.arrow(a,u,m/2,w)};h.SVGRenderer.prototype.symbols["triangle-left"]=function(a,h,m,w){return[["M",a+m,h],["L",a,h+w/2],["L",a+m,h+w],["Z"]]};h.SVGRenderer.prototype.symbols["arrow-filled"]=h.SVGRenderer.prototype.symbols["triangle-left"];h.SVGRenderer.prototype.symbols["triangle-left-half"]=function(a,u,m,w){return h.SVGRenderer.prototype.symbols["triangle-left"](a,u,m/2,w)};h.SVGRenderer.prototype.symbols["arrow-filled-half"]=h.SVGRenderer.prototype.symbols["triangle-left-half"]});
G(h,"parts-gantt/Pathfinder.js",[h["parts/Globals.js"],h["parts/Point.js"],h["parts/Utilities.js"],h["parts-gantt/PathfinderAlgorithms.js"]],function(h,a,u,m){function w(c){var b=c.shapeArgs;return b?{xMin:b.x,xMax:b.x+b.width,yMin:b.y,yMax:b.y+b.height}:(b=c.graphic&&c.graphic.getBBox())?{xMin:c.plotX-b.width/2,xMax:c.plotX+b.width/2,yMin:c.plotY-b.height/2,yMax:c.plotY+b.height/2}:null}function v(c){for(var b=c.length,a=0,g,e,f=[],l=function(b,c,a){a=C(a,10);var k=b.yMax+a>c.yMin-a&&b.yMin-a<c.yMax+
a,n=b.xMax+a>c.xMin-a&&b.xMin-a<c.xMax+a,g=k?b.xMin>c.xMax?b.xMin-c.xMax:c.xMin-b.xMax:Infinity,e=n?b.yMin>c.yMax?b.yMin-c.yMax:c.yMin-b.yMax:Infinity;return n&&k?a?l(b,c,Math.floor(a/2)):Infinity:d(g,e)};a<b;++a)for(g=a+1;g<b;++g)e=l(c[a],c[g]),80>e&&f.push(e);f.push(80);return t(Math.floor(f.sort(function(b,c){return b-c})[Math.floor(f.length/10)]/2-1),1)}function A(c,b,d){this.init(c,b,d)}function z(c){this.init(c)}function x(c){if(c.options.pathfinder||c.series.reduce(function(b,c){c.options&&
E(!0,c.options.connectors=c.options.connectors||{},c.options.pathfinder);return b||c.options&&c.options.pathfinder},!1))E(!0,c.options.connectors=c.options.connectors||{},c.options.pathfinder),l('WARNING: Pathfinder options have been renamed. Use "chart.connectors" or "series.connectors" instead.')}"";var e=u.addEvent,f=u.defined,l=u.error,r=u.extend,E=u.merge,F=u.objectEach,C=u.pick,q=u.splat,g=h.deg2rad,t=Math.max,d=Math.min;r(h.defaultOptions,{connectors:{type:"straight",lineWidth:1,marker:{enabled:!1,
align:"center",verticalAlign:"middle",inside:!1,lineWidth:1},startMarker:{symbol:"diamond"},endMarker:{symbol:"arrow-filled"}}});A.prototype={init:function(c,b,d){this.fromPoint=c;this.toPoint=b;this.options=d;this.chart=c.series.chart;this.pathfinder=this.chart.pathfinder},renderPath:function(c,b,d){var a=this.chart,g=a.styledMode,n=a.pathfinder,e=!a.options.chart.forExport&&!1!==d,f=this.graphics&&this.graphics.path;n.group||(n.group=a.renderer.g().addClass("highcharts-pathfinder-group").attr({zIndex:-1}).add(a.seriesGroup));
n.group.translate(a.plotLeft,a.plotTop);f&&f.renderer||(f=a.renderer.path().add(n.group),g||f.attr({opacity:0}));f.attr(b);c={d:c};g||(c.opacity=1);f[e?"animate":"attr"](c,d);this.graphics=this.graphics||{};this.graphics.path=f},addMarker:function(c,b,d){var a=this.fromPoint.series.chart,n=a.pathfinder;a=a.renderer;var e="start"===c?this.fromPoint:this.toPoint,f=e.getPathfinderAnchorPoint(b);if(b.enabled&&((d="start"===c?d[1]:d[d.length-2])&&"M"===d[0]||"L"===d[0])){d={x:d[1],y:d[2]};d=e.getRadiansToVector(d,
f);f=e.getMarkerVector(d,b.radius,f);d=-d/g;if(b.width&&b.height){var t=b.width;var k=b.height}else t=k=2*b.radius;this.graphics=this.graphics||{};f={x:f.x-t/2,y:f.y-k/2,width:t,height:k,rotation:d,rotationOriginX:f.x,rotationOriginY:f.y};this.graphics[c]?this.graphics[c].animate(f):(this.graphics[c]=a.symbol(b.symbol).addClass("highcharts-point-connecting-path-"+c+"-marker").attr(f).add(n.group),a.styledMode||this.graphics[c].attr({fill:b.color||this.fromPoint.color,stroke:b.lineColor,"stroke-width":b.lineWidth,
opacity:0}).animate({opacity:1},e.series.options.animation))}},getPath:function(c){var b=this.pathfinder,d=this.chart,a=b.algorithms[c.type],g=b.chartObstacles;if("function"!==typeof a)l('"'+c.type+'" is not a Pathfinder algorithm.');else return a.requiresObstacles&&!g&&(g=b.chartObstacles=b.getChartObstacles(c),d.options.connectors.algorithmMargin=c.algorithmMargin,b.chartObstacleMetrics=b.getObstacleMetrics(g)),a(this.fromPoint.getPathfinderAnchorPoint(c.startMarker),this.toPoint.getPathfinderAnchorPoint(c.endMarker),
E({chartObstacles:g,lineObstacles:b.lineObstacles||[],obstacleMetrics:b.chartObstacleMetrics,hardBounds:{xMin:0,xMax:d.plotWidth,yMin:0,yMax:d.plotHeight},obstacleOptions:{margin:c.algorithmMargin},startDirectionX:b.getAlgorithmStartDirection(c.startMarker)},c))},render:function(){var c=this.fromPoint,b=c.series,a=b.chart,g=a.pathfinder,e=E(a.options.connectors,b.options.connectors,c.options.connectors,this.options),l={};a.styledMode||(l.stroke=e.lineColor||c.color,l["stroke-width"]=e.lineWidth,e.dashStyle&&
(l.dashstyle=e.dashStyle));l["class"]="highcharts-point-connecting-path highcharts-color-"+c.colorIndex;e=E(l,e);f(e.marker.radius)||(e.marker.radius=d(t(Math.ceil((e.algorithmMargin||8)/2)-1,1),5));c=this.getPath(e);a=c.path;c.obstacles&&(g.lineObstacles=g.lineObstacles||[],g.lineObstacles=g.lineObstacles.concat(c.obstacles));this.renderPath(a,l,b.options.animation);this.addMarker("start",E(e.marker,e.startMarker),a);this.addMarker("end",E(e.marker,e.endMarker),a)},destroy:function(){this.graphics&&
(F(this.graphics,function(c){c.destroy()}),delete this.graphics)}};z.prototype={algorithms:m,init:function(c){this.chart=c;this.connections=[];e(c,"redraw",function(){this.pathfinder.update()})},update:function(c){var b=this.chart,d=this,g=d.connections;d.connections=[];b.series.forEach(function(c){c.visible&&!c.options.isInternal&&c.points.forEach(function(c){var k,g=c.options&&c.options.connect&&q(c.options.connect);c.visible&&!1!==c.isInside&&g&&g.forEach(function(g){k=b.get("string"===typeof g?
g:g.to);k instanceof a&&k.series.visible&&k.visible&&!1!==k.isInside&&d.connections.push(new A(c,k,"string"===typeof g?{}:g))})})});for(var e=0,f,t,l=g.length,k=d.connections.length;e<l;++e){t=!1;for(f=0;f<k;++f)if(g[e].fromPoint===d.connections[f].fromPoint&&g[e].toPoint===d.connections[f].toPoint){d.connections[f].graphics=g[e].graphics;t=!0;break}t||g[e].destroy()}delete this.chartObstacles;delete this.lineObstacles;d.renderConnections(c)},renderConnections:function(c){c?this.chart.series.forEach(function(b){var c=
function(){var c=b.chart.pathfinder;(c&&c.connections||[]).forEach(function(c){c.fromPoint&&c.fromPoint.series===b&&c.render()});b.pathfinderRemoveRenderEvent&&(b.pathfinderRemoveRenderEvent(),delete b.pathfinderRemoveRenderEvent)};!1===b.options.animation?c():b.pathfinderRemoveRenderEvent=e(b,"afterAnimate",c)}):this.connections.forEach(function(b){b.render()})},getChartObstacles:function(c){for(var b=[],d=this.chart.series,a=C(c.algorithmMargin,0),g,e=0,t=d.length;e<t;++e)if(d[e].visible&&!d[e].options.isInternal)for(var l=
0,k=d[e].points.length,p;l<k;++l)p=d[e].points[l],p.visible&&(p=w(p))&&b.push({xMin:p.xMin-a,xMax:p.xMax+a,yMin:p.yMin-a,yMax:p.yMax+a});b=b.sort(function(b,c){return b.xMin-c.xMin});f(c.algorithmMargin)||(g=c.algorithmMargin=v(b),b.forEach(function(b){b.xMin-=g;b.xMax+=g;b.yMin-=g;b.yMax+=g}));return b},getObstacleMetrics:function(c){for(var b=0,d=0,a,g,e=c.length;e--;)a=c[e].xMax-c[e].xMin,g=c[e].yMax-c[e].yMin,b<a&&(b=a),d<g&&(d=g);return{maxHeight:d,maxWidth:b}},getAlgorithmStartDirection:function(c){var b=
"top"!==c.verticalAlign&&"bottom"!==c.verticalAlign;return"left"!==c.align&&"right"!==c.align?b?void 0:!1:b?!0:void 0}};h.Connection=A;h.Pathfinder=z;r(a.prototype,{getPathfinderAnchorPoint:function(c){var b=w(this);switch(c.align){case "right":var d="xMax";break;case "left":d="xMin"}switch(c.verticalAlign){case "top":var a="yMin";break;case "bottom":a="yMax"}return{x:d?b[d]:(b.xMin+b.xMax)/2,y:a?b[a]:(b.yMin+b.yMax)/2}},getRadiansToVector:function(c,b){var d;f(b)||(d=w(this))&&(b={x:(d.xMin+d.xMax)/
2,y:(d.yMin+d.yMax)/2});return Math.atan2(b.y-c.y,c.x-b.x)},getMarkerVector:function(c,b,d){var a=2*Math.PI,g=w(this),e=g.xMax-g.xMin,n=g.yMax-g.yMin,f=Math.atan2(n,e),k=!1;e/=2;var p=n/2,t=g.xMin+e;g=g.yMin+p;for(var l=t,q=g,h={},r=1,m=1;c<-Math.PI;)c+=a;for(;c>Math.PI;)c-=a;a=Math.tan(c);c>-f&&c<=f?(m=-1,k=!0):c>f&&c<=Math.PI-f?m=-1:c>Math.PI-f||c<=-(Math.PI-f)?(r=-1,k=!0):r=-1;k?(l+=r*e,q+=m*e*a):(l+=n/(2*a)*r,q+=m*p);d.x!==t&&(l=d.x);d.y!==g&&(q=d.y);h.x=l+b*Math.cos(c);h.y=q-b*Math.sin(c);return h}});
h.Chart.prototype.callbacks.push(function(c){!1!==c.options.connectors.enabled&&(x(c),this.pathfinder=new z(this),this.pathfinder.update(!0))})});G(h,"modules/xrange.src.js",[h["parts/Globals.js"],h["parts/Color.js"],h["parts/Point.js"],h["parts/Utilities.js"]],function(h,a,u,m){var w=a.parse;a=m.addEvent;var v=m.clamp,A=m.correctFloat,z=m.defined,x=m.find,e=m.isNumber,f=m.isObject,l=m.merge,r=m.pick;m=m.seriesType;var E=h.seriesTypes.column,F=h.seriesTypes,C=h.Axis,q=h.Series;m("xrange","column",
{colorByPoint:!0,dataLabels:{formatter:function(){var a=this.point.partialFill;f(a)&&(a=a.amount);if(e(a)&&0<a)return A(100*a)+"%"},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:'<span style="font-size: 10px">{point.x} - {point.x2}</span><br/>',pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.yCategory}</b><br/>'},borderRadius:3,pointRange:0},{type:"xrange",parallelArrays:["x","x2","y"],requireSorting:!1,animate:F.line.prototype.animate,cropShoulder:1,
getExtremesFromAll:!0,autoIncrement:h.noop,buildKDTree:h.noop,init:function(){F.column.prototype.init.apply(this,arguments);this.options.stacking=void 0},getColumnMetrics:function(){function a(){e.series.forEach(function(c){var b=c.xAxis;c.xAxis=c.yAxis;c.yAxis=b})}var e=this.chart;a();var d=E.prototype.getColumnMetrics.call(this);a();return d},cropData:function(a,e,d,c){e=q.prototype.cropData.call(this,this.x2Data,e,d,c);e.xData=a.slice(e.start,e.end);return e},findPointIndex:function(a){var g=this.cropped,
d=this.cropStart,c=this.points,b=a.id;if(b)var n=(n=x(c,function(c){return c.id===b}))?n.index:void 0;"undefined"===typeof n&&(n=(n=x(c,function(b){return b.x===a.x&&b.x2===a.x2&&!b.touched}))?n.index:void 0);g&&e(n)&&e(d)&&n>=d&&(n-=d);return n},translatePoint:function(a){var g=this.xAxis,d=this.yAxis,c=this.columnMetrics,b=this.options,n=b.minPointLength||0,h=a.plotX,q=r(a.x2,a.x+(a.len||0)),m=g.translate(q,0,0,0,1);q=Math.abs(m-h);var x=this.chart.inverted,y=r(b.borderWidth,1)%2/2,k=c.offset,p=
Math.round(c.width);n&&(n-=q,0>n&&(n=0),h-=n/2,m+=n/2);h=Math.max(h,-10);m=v(m,-10,g.len+10);z(a.options.pointWidth)&&(k-=(Math.ceil(a.options.pointWidth)-p)/2,p=Math.ceil(a.options.pointWidth));b.pointPlacement&&e(a.plotY)&&d.categories&&(a.plotY=d.translate(a.y,0,1,0,1,b.pointPlacement));a.shapeArgs={x:Math.floor(Math.min(h,m))+y,y:Math.floor(a.plotY+k)+y,width:Math.round(Math.abs(m-h)),height:p,r:this.options.borderRadius};b=a.shapeArgs.x;n=b+a.shapeArgs.width;0>b||n>g.len?(b=v(b,0,g.len),n=v(n,
0,g.len),m=n-b,a.dlBox=l(a.shapeArgs,{x:b,width:n-b,centerX:m?m/2:null})):a.dlBox=null;b=a.tooltipPos;n=x?1:0;m=x?0:1;c=this.columnMetrics?this.columnMetrics.offset:-c.width/2;b[n]=v(b[n]+q/2*(g.reversed?-1:1)*(x?-1:1),0,g.len-1);b[m]=v(b[m]+(x?-1:1)*c,0,d.len-1);if(c=a.partialFill)f(c)&&(c=c.amount),e(c)||(c=0),d=a.shapeArgs,a.partShapeArgs={x:d.x,y:d.y,width:d.width,height:d.height,r:this.options.borderRadius},h=Math.max(Math.round(q*c+a.plotX-h),0),a.clipRectArgs={x:g.reversed?d.x+q-h:d.x,y:d.y,
width:h,height:d.height}},translate:function(){E.prototype.translate.apply(this,arguments);this.points.forEach(function(a){this.translatePoint(a)},this)},drawPoint:function(a,e){var d=this.options,c=this.chart.renderer,b=a.graphic,g=a.shapeType,t=a.shapeArgs,h=a.partShapeArgs,q=a.clipRectArgs,m=a.partialFill,y=d.stacking&&!d.borderRadius,k=a.state,p=d.states[k||"normal"]||{},D="undefined"===typeof k?"attr":e;k=this.pointAttribs(a,k);p=r(this.chart.options.chart.animation,p.animation);if(a.isNull||
!1===a.visible)b&&(a.graphic=b.destroy());else{if(b)b.rect[e](t);else a.graphic=b=c.g("point").addClass(a.getClassName()).add(a.group||this.group),b.rect=c[g](l(t)).addClass(a.getClassName()).addClass("highcharts-partfill-original").add(b);h&&(b.partRect?(b.partRect[e](l(h)),b.partialClipRect[e](l(q))):(b.partialClipRect=c.clipRect(q.x,q.y,q.width,q.height),b.partRect=c[g](h).addClass("highcharts-partfill-overlay").add(b).clip(b.partialClipRect)));this.chart.styledMode||(b.rect[e](k,p).shadow(d.shadow,
null,y),h&&(f(m)||(m={}),f(d.partialFill)&&(m=l(m,d.partialFill)),a=m.fill||w(k.fill).brighten(-.3).get()||w(a.color||this.color).brighten(-.3).get(),k.fill=a,b.partRect[D](k,p).shadow(d.shadow,null,y)))}},drawPoints:function(){var a=this,e=a.getAnimationVerb();a.points.forEach(function(d){a.drawPoint(d,e)})},getAnimationVerb:function(){return this.chart.pointCount<(this.options.animationLimit||250)?"animate":"attr"}},{resolveColor:function(){var a=this.series;if(a.options.colorByPoint&&!this.options.color){var e=
a.options.colors||a.chart.options.colors;var d=this.y%(e?e.length:a.chart.options.chart.colorCount);e=e&&e[d];a.chart.styledMode||(this.color=e);this.options.colorIndex||(this.colorIndex=d)}else this.color||(this.color=a.color)},init:function(){u.prototype.init.apply(this,arguments);this.y||(this.y=0);return this},setState:function(){u.prototype.setState.apply(this,arguments);this.series.drawPoint(this,this.series.getAnimationVerb())},getLabelConfig:function(){var a=u.prototype.getLabelConfig.call(this),
e=this.series.yAxis.categories;a.x2=this.x2;a.yCategory=this.yCategory=e&&e[this.y];return a},tooltipDateKeys:["x","x2"],isValid:function(){return"number"===typeof this.x&&"number"===typeof this.x2}});a(C,"afterGetSeriesExtremes",function(){var a=this.series,e;if(this.isXAxis){var d=r(this.dataMax,-Number.MAX_VALUE);a.forEach(function(c){c.x2Data&&c.x2Data.forEach(function(b){b>d&&(d=b,e=!0)})});e&&(this.dataMax=d)}});""});G(h,"parts-gantt/GanttSeries.js",[h["parts/Globals.js"],h["parts/Utilities.js"]],
function(h,a){var u=a.isNumber,m=a.merge,w=a.pick,v=a.seriesType,A=a.splat,z=h.dateFormat,x=h.seriesTypes.xrange;v("gantt","xrange",{grouping:!1,dataLabels:{enabled:!0},tooltip:{headerFormat:'<span style="font-size: 10px">{series.name}</span><br/>',pointFormat:null,pointFormatter:function(){var a=this.series,f=a.chart.tooltip,l=a.xAxis,h=a.tooltipOptions.dateTimeLabelFormats,m=l.options.startOfWeek,x=a.tooltipOptions,u=x.xDateFormat;a=this.options.milestone;var q="<b>"+(this.name||this.yCategory)+
"</b>";if(x.pointFormat)return this.tooltipFormatter(x.pointFormat);u||(u=A(f.getDateFormat(l.closestPointRange,this.start,m,h))[0]);f=z(u,this.start);l=z(u,this.end);q+="<br/>";return a?q+(f+"<br/>"):q+("Start: "+f+"<br/>End: ")+(l+"<br/>")}},connectors:{type:"simpleConnect",animation:{reversed:!0},startMarker:{enabled:!0,symbol:"arrow-filled",radius:4,fill:"#fa0",align:"left"},endMarker:{enabled:!1,align:"right"}}},{pointArrayMap:["start","end","y"],keyboardMoveVertical:!1,translatePoint:function(a){x.prototype.translatePoint.call(this,
a);if(a.options.milestone){var e=a.shapeArgs;var l=e.height;a.shapeArgs={x:e.x-l/2,y:e.y,width:l,height:l}}},drawPoint:function(a,f){var e=this.options,h=this.chart.renderer,m=a.shapeArgs,v=a.plotY,w=a.graphic,q=a.selected&&"select",g=e.stacking&&!e.borderRadius;if(a.options.milestone)if(u(v)&&null!==a.y&&!1!==a.visible){m=h.symbols.diamond(m.x,m.y,m.width,m.height);if(w)w[f]({d:m});else a.graphic=h.path(m).addClass(a.getClassName(),!0).add(a.group||this.group);this.chart.styledMode||a.graphic.attr(this.pointAttribs(a,
q)).shadow(e.shadow,null,g)}else w&&(a.graphic=w.destroy());else x.prototype.drawPoint.call(this,a,f)},setData:h.Series.prototype.setData,setGanttPointAliases:function(a){function e(e,f){"undefined"!==typeof f&&(a[e]=f)}e("x",w(a.start,a.x));e("x2",w(a.end,a.x2));e("partialFill",w(a.completed,a.partialFill));e("connect",w(a.dependency,a.connect))}},m(x.prototype.pointClass.prototype,{applyOptions:function(a,f){a=m(a);h.seriesTypes.gantt.prototype.setGanttPointAliases(a);return a=x.prototype.pointClass.prototype.applyOptions.call(this,
a,f)},isValid:function(){return("number"===typeof this.start||"number"===typeof this.x)&&("number"===typeof this.end||"number"===typeof this.x2||this.milestone)}}));""});G(h,"parts-gantt/GanttChart.js",[h["parts/Globals.js"],h["parts/Utilities.js"]],function(h,a){var u=a.isArray,m=a.merge,w=a.splat,v=h.Chart;h.ganttChart=function(a,z,x){var e="string"===typeof a||a.nodeName,f=z.series,l=h.getOptions(),r,E=z;z=arguments[e?1:0];u(z.xAxis)||(z.xAxis=[z.xAxis||{},{}]);z.xAxis=z.xAxis.map(function(a,e){1===
e&&(r=0);return m(l.xAxis,{grid:{enabled:!0},opposite:!0,linkedTo:r},a,{type:"datetime"})});z.yAxis=w(z.yAxis||{}).map(function(a){return m(l.yAxis,{grid:{enabled:!0},staticScale:50,reversed:!0,type:a.categories?a.type:"treegrid"},a)});z.series=null;z=m(!0,{chart:{type:"gantt"},title:{text:null},legend:{enabled:!1}},z,{isGantt:!0});z.series=E.series=f;z.series.forEach(function(a){a.data.forEach(function(a){h.seriesTypes.gantt.prototype.setGanttPointAliases(a)})});return e?new v(a,z,x):new v(z,z)}});
G(h,"parts/ScrollbarAxis.js",[h["parts/Globals.js"],h["parts/Utilities.js"]],function(h,a){var u=a.addEvent,m=a.defined,w=a.pick;return function(){function a(){}a.compose=function(a,v){u(a,"afterInit",function(){var a=this;a.options&&a.options.scrollbar&&a.options.scrollbar.enabled&&(a.options.scrollbar.vertical=!a.horiz,a.options.startOnTick=a.options.endOnTick=!1,a.scrollbar=new v(a.chart.renderer,a.options.scrollbar,a.chart),u(a.scrollbar,"changed",function(e){var f=w(a.options&&a.options.min,
a.min),l=w(a.options&&a.options.max,a.max),r=m(a.dataMin)?Math.min(f,a.min,a.dataMin):f,u=(m(a.dataMax)?Math.max(l,a.max,a.dataMax):l)-r;m(f)&&m(l)&&(a.horiz&&!a.reversed||!a.horiz&&a.reversed?(f=r+u*this.to,r+=u*this.from):(f=r+u*(1-this.from),r+=u*(1-this.to)),w(this.options.liveRedraw,h.svg&&!h.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===e.DOMType||!m(e.DOMType)?a.setExtremes(r,f,!0,"mousemove"!==e.DOMType,e):this.setRange(this.from,this.to))}))});u(a,"afterRender",function(){var a=Math.min(w(this.options.min,
this.min),this.min,w(this.dataMin,this.min)),e=Math.max(w(this.options.max,this.max),this.max,w(this.dataMax,this.max)),f=this.scrollbar,h=this.axisTitleMargin+(this.titleOffset||0),r=this.chart.scrollbarsOffsets,u=this.options.margin||0;f&&(this.horiz?(this.opposite||(r[1]+=h),f.position(this.left,this.top+this.height+2+r[1]-(this.opposite?u:0),this.width,this.height),this.opposite||(r[1]+=u),h=1):(this.opposite&&(r[0]+=h),f.position(this.left+this.width+2+r[0]-(this.opposite?0:u),this.top,this.width,
this.height),this.opposite&&(r[0]+=u),h=0),r[h]+=f.size+f.options.margin,isNaN(a)||isNaN(e)||!m(this.min)||!m(this.max)||this.min===this.max?f.setRange(0,1):(r=(this.min-a)/(e-a),a=(this.max-a)/(e-a),this.horiz&&!this.reversed||!this.horiz&&this.reversed?f.setRange(r,a):f.setRange(1-a,1-r)))});u(a,"afterGetOffset",function(){var a=this.horiz?2:1,e=this.scrollbar;e&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[a]+=e.size+e.options.margin)})};return a}()});G(h,"parts/Scrollbar.js",[h["parts/Axis.js"],
h["parts/Globals.js"],h["parts/ScrollbarAxis.js"],h["parts/Utilities.js"]],function(h,a,u,m){var w=m.addEvent,v=m.correctFloat,A=m.defined,z=m.destroyObjectProperties,x=m.fireEvent,e=m.merge,f=m.pick,l=m.removeEvent;m=a.defaultOptions;var r=a.hasTouch,E=a.isTouchDevice,F=a.swapXY=function(a,e){e&&a.forEach(function(a){for(var d=a.length,c,b=0;b<d;b+=2)c=a[b+1],"number"===typeof c&&(a[b+1]=a[b+2],a[b+2]=c)});return a},C=function(){function a(a,e,d){this._events=[];this.from=this.chartY=this.chartX=
0;this.scrollbar=this.group=void 0;this.scrollbarButtons=[];this.scrollbarGroup=void 0;this.scrollbarLeft=0;this.scrollbarRifles=void 0;this.scrollbarStrokeWidth=1;this.to=this.size=this.scrollbarTop=0;this.track=void 0;this.trackBorderWidth=1;this.userOptions={};this.y=this.x=0;this.chart=d;this.options=e;this.renderer=d.renderer;this.init(a,e,d)}a.prototype.addEvents=function(){var a=this.options.inverted?[1,0]:[0,1],e=this.scrollbarButtons,d=this.scrollbarGroup.element,c=this.track.element,b=this.mouseDownHandler.bind(this),
n=this.mouseMoveHandler.bind(this),f=this.mouseUpHandler.bind(this);a=[[e[a[0]].element,"click",this.buttonToMinClick.bind(this)],[e[a[1]].element,"click",this.buttonToMaxClick.bind(this)],[c,"click",this.trackClick.bind(this)],[d,"mousedown",b],[d.ownerDocument,"mousemove",n],[d.ownerDocument,"mouseup",f]];r&&a.push([d,"touchstart",b],[d.ownerDocument,"touchmove",n],[d.ownerDocument,"touchend",f]);a.forEach(function(b){w.apply(null,b)});this._events=a};a.prototype.buttonToMaxClick=function(a){var e=
(this.to-this.from)*f(this.options.step,.2);this.updatePosition(this.from+e,this.to+e);x(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:a})};a.prototype.buttonToMinClick=function(a){var e=v(this.to-this.from)*f(this.options.step,.2);this.updatePosition(v(this.from-e),v(this.to-e));x(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:a})};a.prototype.cursorToScrollbarPosition=function(a){var e=this.options;e=e.minWidth>this.calculatedWidth?e.minWidth:0;return{chartX:(a.chartX-
this.x-this.xOffset)/(this.barWidth-e),chartY:(a.chartY-this.y-this.yOffset)/(this.barWidth-e)}};a.prototype.destroy=function(){var a=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(a){this[a]&&this[a].destroy&&(this[a]=this[a].destroy())},this);a&&this===a.scrollbar&&(a.scrollbar=null,z(a.scrollbarButtons))};a.prototype.drawScrollbarButton=function(a){var e=this.renderer,d=this.scrollbarButtons,c=this.options,b=this.size;var g=
e.g().add(this.group);d.push(g);g=e.rect().addClass("highcharts-scrollbar-button").add(g);this.chart.styledMode||g.attr({stroke:c.buttonBorderColor,"stroke-width":c.buttonBorderWidth,fill:c.buttonBackgroundColor});g.attr(g.crisp({x:-.5,y:-.5,width:b+1,height:b+1,r:c.buttonBorderRadius},g.strokeWidth()));g=e.path(F([["M",b/2+(a?-1:1),b/2-3],["L",b/2+(a?-1:1),b/2+3],["L",b/2+(a?2:-2),b/2]],c.vertical)).addClass("highcharts-scrollbar-arrow").add(d[a]);this.chart.styledMode||g.attr({fill:c.buttonArrowColor})};
a.prototype.init=function(g,h,d){this.scrollbarButtons=[];this.renderer=g;this.userOptions=h;this.options=e(a.defaultOptions,h);this.chart=d;this.size=f(this.options.size,this.options.height);h.enabled&&(this.render(),this.addEvents())};a.prototype.mouseDownHandler=function(a){a=this.chart.pointer.normalize(a);a=this.cursorToScrollbarPosition(a);this.chartX=a.chartX;this.chartY=a.chartY;this.initPositions=[this.from,this.to];this.grabbedCenter=!0};a.prototype.mouseMoveHandler=function(a){var e=this.chart.pointer.normalize(a),
d=this.options.vertical?"chartY":"chartX",c=this.initPositions||[];!this.grabbedCenter||a.touches&&0===a.touches[0][d]||(e=this.cursorToScrollbarPosition(e)[d],d=this[d],d=e-d,this.hasDragged=!0,this.updatePosition(c[0]+d,c[1]+d),this.hasDragged&&x(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:a.type,DOMEvent:a}))};a.prototype.mouseUpHandler=function(a){this.hasDragged&&x(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:a.type,DOMEvent:a});this.grabbedCenter=
this.hasDragged=this.chartX=this.chartY=null};a.prototype.position=function(a,e,d,c){var b=this.options.vertical,g=0,f=this.rendered?"animate":"attr";this.x=a;this.y=e+this.trackBorderWidth;this.width=d;this.xOffset=this.height=c;this.yOffset=g;b?(this.width=this.yOffset=d=g=this.size,this.xOffset=e=0,this.barWidth=c-2*d,this.x=a+=this.options.margin):(this.height=this.xOffset=c=e=this.size,this.barWidth=d-2*c,this.y+=this.options.margin);this.group[f]({translateX:a,translateY:this.y});this.track[f]({width:d,
height:c});this.scrollbarButtons[1][f]({translateX:b?0:d-e,translateY:b?c-g:0})};a.prototype.removeEvents=function(){this._events.forEach(function(a){l.apply(null,a)});this._events.length=0};a.prototype.render=function(){var a=this.renderer,e=this.options,d=this.size,c=this.chart.styledMode,b;this.group=b=a.g("scrollbar").attr({zIndex:e.zIndex,translateY:-99999}).add();this.track=a.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:e.trackBorderRadius||0,height:d,width:d}).add(b);c||this.track.attr({fill:e.trackBackgroundColor,
stroke:e.trackBorderColor,"stroke-width":e.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=a.g().add(b);this.scrollbar=a.rect().addClass("highcharts-scrollbar-thumb").attr({height:d,width:d,r:e.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=a.path(F([["M",-3,d/4],["L",-3,2*d/3],["M",0,d/4],["L",0,2*d/3],["M",3,d/4],["L",3,2*d/3]],e.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);
c||(this.scrollbar.attr({fill:e.barBackgroundColor,stroke:e.barBorderColor,"stroke-width":e.barBorderWidth}),this.scrollbarRifles.attr({stroke:e.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)};a.prototype.setRange=function(a,e){var d=this.options,c=d.vertical,b=d.minWidth,g=this.barWidth,f,h=!this.rendered||this.hasDragged||
this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(A(g)){a=Math.max(a,0);var l=Math.ceil(g*a);this.calculatedWidth=f=v(g*Math.min(e,1)-l);f<b&&(l=(g-b+f)*a,f=b);b=Math.floor(l+this.xOffset+this.yOffset);g=f/2-.5;this.from=a;this.to=e;c?(this.scrollbarGroup[h]({translateY:b}),this.scrollbar[h]({height:f}),this.scrollbarRifles[h]({translateY:g}),this.scrollbarTop=b,this.scrollbarLeft=0):(this.scrollbarGroup[h]({translateX:b}),this.scrollbar[h]({width:f}),this.scrollbarRifles[h]({translateX:g}),
this.scrollbarLeft=b,this.scrollbarTop=0);12>=f?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===d.showFull&&(0>=a&&1<=e?this.group.hide():this.group.show());this.rendered=!0}};a.prototype.trackClick=function(a){var e=this.chart.pointer.normalize(a),d=this.to-this.from,c=this.y+this.scrollbarTop,b=this.x+this.scrollbarLeft;this.options.vertical&&e.chartY>c||!this.options.vertical&&e.chartX>b?this.updatePosition(this.from+d,this.to+d):this.updatePosition(this.from-d,this.to-d);x(this,
"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:a})};a.prototype.update=function(a){this.destroy();this.init(this.chart.renderer,e(!0,this.options,a),this.chart)};a.prototype.updatePosition=function(a,e){1<e&&(a=v(1-v(e-a)),e=1);0>a&&(e=v(e-a),a=0);this.from=a;this.to=e};a.defaultOptions={height:E?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",
buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",trackBorderColor:"#f2f2f2",trackBorderWidth:1};return a}();a.Scrollbar||(m.scrollbar=e(!0,C.defaultOptions,m.scrollbar),a.Scrollbar=C,u.compose(h,C));return a.Scrollbar});G(h,"parts/RangeSelector.js",[h["parts/Globals.js"],h["parts/Utilities.js"]],function(h,a){function u(a){this.init(a)}var m=a.addEvent,w=a.createElement,v=a.css,A=a.defined,z=a.destroyObjectProperties,
x=a.discardElement,e=a.extend,f=a.fireEvent,l=a.isNumber,r=a.merge,E=a.objectEach,F=a.pick,C=a.pInt,q=a.splat,g=h.Axis;a=h.Chart;var t=h.defaultOptions;e(t,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});t.lang=r(t.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});u.prototype={clickButton:function(a,
c){var b=this.chart,d=this.buttonOptions[a],e=b.xAxis[0],f=b.scroller&&b.scroller.getUnionExtremes()||e||{},h=f.dataMin,r=f.dataMax,y=e&&Math.round(Math.min(e.max,F(r,e.max))),k=d.type;f=d._range;var p,D=d.dataGrouping;if(null!==h&&null!==r){b.fixedRange=f;D&&(this.forcedDataGrouping=!0,g.prototype.setDataGrouping.call(e||{chart:this.chart},D,!1),this.frozenStates=d.preserveDataGrouping);if("month"===k||"year"===k)if(e){k={range:d,max:y,chart:b,dataMin:h,dataMax:r};var t=e.minFromRange.call(k);l(k.newMax)&&
(y=k.newMax)}else f=d;else if(f)t=Math.max(y-f,h),y=Math.min(t+f,r);else if("ytd"===k)if(e)"undefined"===typeof r&&(h=Number.MAX_VALUE,r=Number.MIN_VALUE,b.series.forEach(function(a){a=a.xData;h=Math.min(a[0],h);r=Math.max(a[a.length-1],r)}),c=!1),y=this.getYTDExtremes(r,h,b.time.useUTC),t=p=y.min,y=y.max;else{this.deferredYTDClick=a;return}else"all"===k&&e&&(t=h,y=r);t+=d._offsetMin;y+=d._offsetMax;this.setSelected(a);if(e)e.setExtremes(t,y,F(c,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:d});
else{var I=q(b.options.xAxis)[0];var u=I.range;I.range=f;var w=I.min;I.min=p;m(b,"load",function(){I.range=u;I.min=w})}}},setSelected:function(a){this.selected=this.options.selected=a},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(a){var c=this,b=a.options.rangeSelector,d=b.buttons||[].concat(c.defaultButtons),e=b.selected,g=function(){var a=
c.minInput,b=c.maxInput;a&&a.blur&&f(a,"blur");b&&b.blur&&f(b,"blur")};c.chart=a;c.options=b;c.buttons=[];c.buttonOptions=d;this.unMouseDown=m(a.container,"mousedown",g);this.unResize=m(a,"resize",g);d.forEach(c.computeButtonRange);"undefined"!==typeof e&&d[e]&&this.clickButton(e,!1);m(a,"load",function(){a.xAxis&&a.xAxis[0]&&m(a.xAxis[0],"setExtremes",function(b){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==b.trigger&&"updatedData"!==b.trigger&&c.forcedDataGrouping&&!c.frozenStates&&
this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var a=this,c=this.chart,b=c.xAxis[0],e=Math.round(b.max-b.min),g=!b.hasVisibleSeries,f=c.scroller&&c.scroller.getUnionExtremes()||b,h=f.dataMin,m=f.dataMax;c=a.getYTDExtremes(m,h,c.time.useUTC);var r=c.min,k=c.max,p=a.selected,D=l(p),q=a.options.allButtonsEnabled,t=a.buttons;a.buttonOptions.forEach(function(c,d){var f=c._range,n=c.type,l=c.count||1,y=t[d],I=0,u=c._offsetMax-c._offsetMin;c=d===p;var J=f>m-h,w=f<b.minRange,v=!1,T=!1;f=f===
e;("month"===n||"year"===n)&&e+36E5>=864E5*{month:28,year:365}[n]*l-u&&e-36E5<=864E5*{month:31,year:366}[n]*l+u?f=!0:"ytd"===n?(f=k-r+u===e,v=!c):"all"===n&&(f=b.max-b.min>=m-h,T=!c&&D&&f);n=!q&&(J||w||T||g);l=c&&f||f&&!D&&!v||c&&a.frozenStates;n?I=3:l&&(D=!0,I=2);y.state!==I&&(y.setState(I),0===I&&p===d&&a.setSelected(null))})},computeButtonRange:function(a){var c=a.type,b=a.count||1,d={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(d[c])a._range=d[c]*b;else if("month"===
c||"year"===c)a._range=864E5*{month:30,year:365}[c]*b;a._offsetMin=F(a.offsetMin,0);a._offsetMax=F(a.offsetMax,0);a._range+=a._offsetMax-a._offsetMin},setInputValue:function(a,c){var b=this.chart.options.rangeSelector,d=this.chart.time,e=this[a+"Input"];A(c)&&(e.previousValue=e.HCTime,e.HCTime=c);e.value=d.dateFormat(b.inputEditDateFormat||"%Y-%m-%d",e.HCTime);this[a+"DateBox"].attr({text:d.dateFormat(b.inputDateFormat||"%b %e, %Y",e.HCTime)})},showInput:function(a){var c=this.inputGroup,b=this[a+
"DateBox"];v(this[a+"Input"],{left:c.translateX+b.x+"px",top:c.translateY+"px",width:b.width-2+"px",height:b.height-2+"px",border:"2px solid silver"})},hideInput:function(a){v(this[a+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)},drawInput:function(a){function c(){var a=k.value,c=(m.inputDateParser||Date.parse)(a),e=d.xAxis[0],p=d.scroller&&d.scroller.xAxis?d.scroller.xAxis:e,f=p.dataMin;p=p.dataMax;c!==k.previousValue&&(k.previousValue=c,l(c)||(c=a.split("-"),c=Date.UTC(C(c[0]),
C(c[1])-1,C(c[2]))),l(c)&&(d.time.useUTC||(c+=6E4*(new Date).getTimezoneOffset()),y?c>b.maxInput.HCTime?c=void 0:c<f&&(c=f):c<b.minInput.HCTime?c=void 0:c>p&&(c=p),"undefined"!==typeof c&&e.setExtremes(y?c:e.min,y?e.max:c,void 0,void 0,{trigger:"rangeSelectorInput"})))}var b=this,d=b.chart,f=d.renderer.style||{},g=d.renderer,m=d.options.rangeSelector,q=b.div,y="min"===a,k,p,D=this.inputGroup;this[a+"Label"]=p=g.label(t.lang[y?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(D);
D.offset+=p.width+5;this[a+"DateBox"]=g=g.label("",D.offset).addClass("highcharts-range-input").attr({padding:2,width:m.inputBoxWidth||90,height:m.inputBoxHeight||17,"text-align":"center"}).on("click",function(){b.showInput(a);b[a+"Input"].focus()});d.styledMode||g.attr({stroke:m.inputBoxBorderColor||"#cccccc","stroke-width":1});g.add(D);D.offset+=g.width+(y?10:0);this[a+"Input"]=k=w("input",{name:a,className:"highcharts-range-selector",type:"text"},{top:d.plotTop+"px"},q);d.styledMode||(p.css(r(f,
m.labelStyle)),g.css(r({color:"#333333"},f,m.inputStyle)),v(k,e({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:f.fontSize,fontFamily:f.fontFamily,top:"-9999em"},m.inputStyle)));k.onfocus=function(){b.showInput(a)};k.onblur=function(){k===h.doc.activeElement&&c();b.hideInput(a);k.blur()};k.onchange=c;k.onkeypress=function(a){13===a.keyCode&&c()}},getPosition:function(){var a=this.chart,c=a.options.rangeSelector;a="top"===c.verticalAlign?a.plotTop-a.axisOffset[0]:
0;return{buttonTop:a+c.buttonPosition.y,inputTop:a+c.inputPosition.y-10}},getYTDExtremes:function(a,c,b){var d=this.chart.time,e=new d.Date(a),f=d.get("FullYear",e);b=b?d.Date.UTC(f,0,1):+new d.Date(f,0,1);c=Math.max(c||0,b);e=e.getTime();return{max:Math.min(a||e,e),min:c}},render:function(a,c){var b=this,d=b.chart,e=d.renderer,f=d.container,g=d.options,h=g.exporting&&!1!==g.exporting.enabled&&g.navigation&&g.navigation.buttonOptions,l=t.lang,k=b.div,p=g.rangeSelector,m=F(g.chart.style&&g.chart.style.zIndex,
0)+1;g=p.floating;var r=b.buttons;k=b.inputGroup;var q=p.buttonTheme,u=p.buttonPosition,v=p.inputPosition,R=p.inputEnabled,x=q&&q.states,z=d.plotLeft,C=b.buttonGroup,S,E=b.options.verticalAlign,A=d.legend,K=A&&A.options,G=u.y,P=v.y,Q=d.hasLoaded,U=Q?"animate":"attr",N=0,M=0;if(!1!==p.enabled){b.rendered||(b.group=S=e.g("range-selector-group").attr({zIndex:7}).add(),b.buttonGroup=C=e.g("range-selector-buttons").add(S),b.zoomText=e.text(l.rangeSelectorZoom,0,15).add(C),d.styledMode||(b.zoomText.css(p.labelStyle),
q["stroke-width"]=F(q["stroke-width"],0)),b.buttonOptions.forEach(function(a,c){r[c]=e.button(a.text,0,0,function(d){var e=a.events&&a.events.click,k;e&&(k=e.call(a,d));!1!==k&&b.clickButton(c);b.isActive=!0},q,x&&x.hover,x&&x.select,x&&x.disabled).attr({"text-align":"center"}).add(C)}),!1!==R&&(b.div=k=w("div",null,{position:"relative",height:0,zIndex:m}),f.parentNode.insertBefore(k,f),b.inputGroup=k=e.g("input-group").add(S),k.offset=0,b.drawInput("min"),b.drawInput("max")));b.zoomText[U]({x:F(z+
u.x,z)});var V=F(z+u.x,z)+b.zoomText.getBBox().width+5;b.buttonOptions.forEach(function(a,b){r[b][U]({x:V});V+=r[b].width+F(p.buttonSpacing,5)});z=d.plotLeft-d.spacing[3];b.updateButtonStates();h&&this.titleCollision(d)&&"top"===E&&"right"===u.align&&u.y+C.getBBox().height-12<(h.y||0)+h.height&&(N=-40);f=u.x-d.spacing[3];"right"===u.align?f+=N-z:"center"===u.align&&(f-=z/2);C.align({y:u.y,width:C.getBBox().width,align:u.align,x:f},!0,d.spacingBox);b.group.placed=Q;b.buttonGroup.placed=Q;!1!==R&&(N=
h&&this.titleCollision(d)&&"top"===E&&"right"===v.align&&v.y-k.getBBox().height-12<(h.y||0)+h.height+d.spacing[0]?-40:0,"left"===v.align?f=z:"right"===v.align&&(f=-Math.max(d.axisOffset[1],-N)),k.align({y:v.y,width:k.getBBox().width,align:v.align,x:v.x+f-2},!0,d.spacingBox),h=k.alignAttr.translateX+k.alignOptions.x-N+k.getBBox().x+2,f=k.alignOptions.width,l=C.alignAttr.translateX+C.getBBox().x,z=C.getBBox().width+20,(v.align===u.align||l+z>h&&h+f>l&&G<P+k.getBBox().height)&&k.attr({translateX:k.alignAttr.translateX+
(d.axisOffset[1]>=-N?0:-N),translateY:k.alignAttr.translateY+C.getBBox().height+10}),b.setInputValue("min",a),b.setInputValue("max",c),b.inputGroup.placed=Q);b.group.align({verticalAlign:E},!0,d.spacingBox);a=b.group.getBBox().height+20;c=b.group.alignAttr.translateY;"bottom"===E&&(A=K&&"bottom"===K.verticalAlign&&K.enabled&&!K.floating?A.legendHeight+F(K.margin,10):0,a=a+A-20,M=c-a-(g?0:p.y)-(d.titleOffset?d.titleOffset[2]:0)-10);if("top"===E)g&&(M=0),d.titleOffset&&d.titleOffset[0]&&(M=d.titleOffset[0]),
M+=d.margin[0]-d.spacing[0]||0;else if("middle"===E)if(P===G)M=0>P?c+void 0:c;else if(P||G)M=0>P||0>G?M-Math.min(P,G):c-a+NaN;b.group.translate(p.x,p.y+Math.floor(M));!1!==R&&(b.minInput.style.marginTop=b.group.translateY+"px",b.maxInput.style.marginTop=b.group.translateY+"px");b.rendered=!0}},getHeight:function(){var a=this.options,c=this.group,b=a.y,e=a.buttonPosition.y,f=a.inputPosition.y;if(a.height)return a.height;a=c?c.getBBox(!0).height+13+b:0;c=Math.min(f,e);if(0>f&&0>e||0<f&&0<e)a+=Math.abs(c);
return a},titleCollision:function(a){return!(a.options.title.text||a.options.subtitle.text)},update:function(a){var c=this.chart;r(!0,c.options.rangeSelector,a);this.destroy();this.init(c);c.rangeSelector.render()},destroy:function(){var a=this,c=a.minInput,b=a.maxInput;a.unMouseDown();a.unResize();z(a.buttons);c&&(c.onfocus=c.onblur=c.onchange=null);b&&(b.onfocus=b.onblur=b.onchange=null);E(a,function(b,c){b&&"chart"!==c&&(b.destroy?b.destroy():b.nodeType&&x(this[c]));b!==u.prototype[c]&&(a[c]=null)},
this)}};g.prototype.minFromRange=function(){var a=this.range,c=a.type,b=this.max,e=this.chart.time,f=function(a,b){var d="year"===c?"FullYear":"Month",k=new e.Date(a),f=e.get(d,k);e.set(d,k,f+b);f===e.get(d,k)&&e.set("Date",k,0);return k.getTime()-a};if(l(a)){var g=b-a;var h=a}else g=b+f(b,-a.count),this.chart&&(this.chart.fixedRange=b-g);var m=F(this.dataMin,Number.MIN_VALUE);l(g)||(g=m);g<=m&&(g=m,"undefined"===typeof h&&(h=f(g,a.count)),this.newMax=Math.min(g+h,this.dataMax));l(b)||(g=void 0);
return g};h.RangeSelector||(m(a,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new u(this))}),m(a,"beforeRender",function(){var a=this.axes,c=this.rangeSelector;c&&(l(c.deferredYTDClick)&&(c.clickButton(c.deferredYTDClick),delete c.deferredYTDClick),a.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),c.render(),a=c.options.verticalAlign,c.options.floating||("bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)))}),
m(a,"update",function(a){var c=a.options.rangeSelector;a=this.rangeSelector;var b=this.extraBottomMargin,d=this.extraTopMargin;c&&c.enabled&&!A(a)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new u(this));this.extraTopMargin=this.extraBottomMargin=!1;a&&(a.render(),c=c&&c.verticalAlign||a.options&&a.options.verticalAlign,a.options.floating||("bottom"===c?this.extraBottomMargin=!0:"middle"!==c&&(this.extraTopMargin=!0)),this.extraBottomMargin!==b||this.extraTopMargin!==d)&&(this.isDirtyBox=
!0)}),m(a,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),m(a,"getMargins",function(){var a=this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))}),a.prototype.callbacks.push(function(a){function c(){b=a.xAxis[0].getExtremes();e=a.legend;g=null===d||void 0===d?void 0:d.options.verticalAlign;
l(b.min)&&d.render(b.min,b.max);d&&e.display&&"top"===g&&g===e.options.verticalAlign&&(f=r(a.spacingBox),f.y="vertical"===e.options.layout?a.plotTop:f.y+d.getHeight(),e.group.placed=!1,e.align(f))}var b,d=a.rangeSelector,e,f,g;if(d){var h=m(a.xAxis[0],"afterSetExtremes",function(a){d.render(a.min,a.max)});var q=m(a,"redraw",c);c()}m(a,"destroy",function(){d&&(q(),h())})}),h.RangeSelector=u)});G(h,"parts/NavigatorAxis.js",[h["parts/Globals.js"],h["parts/Utilities.js"]],function(h,a){var u=h.isTouchDevice,
m=a.addEvent,w=a.correctFloat,v=a.defined,A=a.isNumber,z=a.pick,x=function(){function a(a){this.axis=a}a.prototype.destroy=function(){this.axis=void 0};a.prototype.toFixedRange=function(a,e,h,m){var f=this.axis,l=f.chart;l=l&&l.fixedRange;var q=(f.pointRange||0)/2;a=z(h,f.translate(a,!0,!f.horiz));e=z(m,f.translate(e,!0,!f.horiz));f=l&&(e-a)/l;v(h)||(a=w(a+q));v(m)||(e=w(e-q));.7<f&&1.3>f&&(m?a=e-l:e=a+l);A(a)&&A(e)||(a=e=void 0);return{min:a,max:e}};return a}();return function(){function a(){}a.compose=
function(a){a.keepProps.push("navigatorAxis");m(a,"init",function(){this.navigatorAxis||(this.navigatorAxis=new x(this))});m(a,"zoom",function(a){var e=this.chart.options,f=e.navigator,h=this.navigatorAxis,m=e.chart.pinchType,l=e.rangeSelector;e=e.chart.zoomType;this.isXAxis&&(f&&f.enabled||l&&l.enabled)&&("y"===e?a.zoomed=!1:(!u&&"xy"===e||u&&"xy"===m)&&this.options.range&&(f=h.previousZoom,v(a.newMin)?h.previousZoom=[this.min,this.max]:f&&(a.newMin=f[0],a.newMax=f[1],h.previousZoom=void 0)));"undefined"!==
typeof a.zoomed&&a.preventDefault()})};a.AdditionsClass=x;return a}()});G(h,"parts/Navigator.js",[h["parts/Axis.js"],h["parts/Color.js"],h["parts/Globals.js"],h["parts/NavigatorAxis.js"],h["parts/Scrollbar.js"],h["parts/Utilities.js"]],function(h,a,u,m,w,v){a=a.parse;var A=v.addEvent,z=v.clamp,x=v.correctFloat,e=v.defined,f=v.destroyObjectProperties,l=v.erase,r=v.extend,E=v.find,F=v.isArray,C=v.isNumber,q=v.merge,g=v.pick,t=v.removeEvent,d=v.splat;v=u.Chart;var c=u.defaultOptions,b=u.hasTouch,n=u.isTouchDevice,
G=u.Series,H=function(a){for(var b=[],c=1;c<arguments.length;c++)b[c-1]=arguments[c];b=[].filter.call(b,C);if(b.length)return Math[a].apply(0,b)};var O="undefined"===typeof u.seriesTypes.areaspline?"line":"areaspline";r(c,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:a("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:O,
fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,
className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:"#999999"},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});u.Renderer.prototype.symbols["navigator-handle"]=function(a,b,c,d,e){a=e.width/2;b=Math.round(a/3)+.5;e=e.height||
0;return[["M",-a-1,.5],["L",a,.5],["L",a,e+.5],["L",-a-1,e+.5],["L",-a-1,.5],["M",-b,4],["L",-b,e-3],["M",b-1,4],["L",b-1,e-3]]};var B=function(){function a(a){this.zoomedMin=this.zoomedMax=this.yAxis=this.xAxis=this.top=this.size=this.shades=this.rendered=this.range=this.outlineHeight=this.outline=this.opposite=this.navigatorSize=this.navigatorSeries=this.navigatorOptions=this.navigatorGroup=this.navigatorEnabled=this.left=this.height=this.handles=this.chart=this.baseSeries=void 0;this.init(a)}a.prototype.drawHandle=
function(a,b,c,d){var e=this.navigatorOptions.handles.height;this.handles[b][d](c?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(a,10)+.5-e)}:{translateX:Math.round(this.left+parseInt(a,10)),translateY:Math.round(this.top+this.height/2-e/2-1)})};a.prototype.drawOutline=function(a,b,c,d){var e=this.navigatorOptions.maskInside,k=this.outline.strokeWidth(),f=k/2,g=k%2/2;k=this.outlineHeight;var p=this.scrollbarHeight||0,h=this.size,m=this.left-p,l=this.top;c?
(m-=f,c=l+b+g,b=l+a+g,g=[["M",m+k,l-p-g],["L",m+k,c],["L",m,c],["L",m,b],["L",m+k,b],["L",m+k,l+h+p]],e&&g.push(["M",m+k,c-f],["L",m+k,b+f])):(a+=m+p-g,b+=m+p-g,l+=f,g=[["M",m,l],["L",a,l],["L",a,l+k],["L",b,l+k],["L",b,l],["L",m+h+2*p,l]],e&&g.push(["M",a-f,l],["L",b+f,l]));this.outline[d]({d:g})};a.prototype.drawMasks=function(a,b,c,d){var e=this.left,k=this.top,f=this.height;if(c){var g=[e,e,e];var p=[k,k+a,k+b];var h=[f,f,f];var m=[a,b-a,this.size-b]}else g=[e,e+a,e+b],p=[k,k,k],h=[a,b-a,this.size-
b],m=[f,f,f];this.shades.forEach(function(a,b){a[d]({x:g[b],y:p[b],width:h[b],height:m[b]})})};a.prototype.renderElements=function(){var a=this,b=a.navigatorOptions,c=b.maskInside,d=a.chart,e=d.renderer,f,g={cursor:d.inverted?"ns-resize":"ew-resize"};a.navigatorGroup=f=e.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!c,c,!c].forEach(function(c,k){a.shades[k]=e.rect().addClass("highcharts-navigator-mask"+(1===k?"-inside":"-outside")).add(f);d.styledMode||a.shades[k].attr({fill:c?b.maskFill:
"rgba(0,0,0,0)"}).css(1===k&&g)});a.outline=e.path().addClass("highcharts-navigator-outline").add(f);d.styledMode||a.outline.attr({"stroke-width":b.outlineWidth,stroke:b.outlineColor});b.handles.enabled&&[0,1].forEach(function(c){b.handles.inverted=d.inverted;a.handles[c]=e.symbol(b.handles.symbols[c],-b.handles.width/2-1,0,b.handles.width,b.handles.height,b.handles);a.handles[c].attr({zIndex:7-c}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][c]).add(f);if(!d.styledMode){var k=
b.handles;a.handles[c].attr({fill:k.backgroundColor,stroke:k.borderColor,"stroke-width":k.lineWidth}).css(g)}})};a.prototype.update=function(a){(this.series||[]).forEach(function(a){a.baseSeries&&delete a.baseSeries.navigatorSeries});this.destroy();q(!0,this.chart.options.navigator,this.options,a);this.init(this.chart)};a.prototype.render=function(a,b,c,d){var k=this.chart,f=this.scrollbarHeight,p,h=this.xAxis,m=h.pointRange||0;var l=h.navigatorAxis.fake?k.xAxis[0]:h;var n=this.navigatorEnabled,q,
r=this.rendered;var t=k.inverted;var u=k.xAxis[0].minRange,D=k.xAxis[0].options.maxRange;if(!this.hasDragged||e(c)){a=x(a-m/2);b=x(b+m/2);if(!C(a)||!C(b))if(r)c=0,d=g(h.width,l.width);else return;this.left=g(h.left,k.plotLeft+f+(t?k.plotWidth:0));this.size=q=p=g(h.len,(t?k.plotHeight:k.plotWidth)-2*f);k=t?f:p+2*f;c=g(c,h.toPixels(a,!0));d=g(d,h.toPixels(b,!0));C(c)&&Infinity!==Math.abs(c)||(c=0,d=k);a=h.toValue(c,!0);b=h.toValue(d,!0);var v=Math.abs(x(b-a));v<u?this.grabbedLeft?c=h.toPixels(b-u-m,
!0):this.grabbedRight&&(d=h.toPixels(a+u+m,!0)):e(D)&&x(v-m)>D&&(this.grabbedLeft?c=h.toPixels(b-D-m,!0):this.grabbedRight&&(d=h.toPixels(a+D+m,!0)));this.zoomedMax=z(Math.max(c,d),0,q);this.zoomedMin=z(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(c,d),0,q);this.range=this.zoomedMax-this.zoomedMin;q=Math.round(this.zoomedMax);c=Math.round(this.zoomedMin);n&&(this.navigatorGroup.attr({visibility:"visible"}),r=r&&!this.hasDragged?"animate":"attr",this.drawMasks(c,q,t,r),this.drawOutline(c,
q,t,r),this.navigatorOptions.handles.enabled&&(this.drawHandle(c,0,t,r),this.drawHandle(q,1,t,r)));this.scrollbar&&(t?(t=this.top-f,l=this.left-f+(n||!l.opposite?0:(l.titleOffset||0)+l.axisTitleMargin),f=p+2*f):(t=this.top+(n?this.height:-f),l=this.left-f),this.scrollbar.position(l,t,k,f),this.scrollbar.setRange(this.zoomedMin/(p||1),this.zoomedMax/(p||1)));this.rendered=!0}};a.prototype.addMouseEvents=function(){var a=this,c=a.chart,d=c.container,e=[],f,g;a.mouseMoveHandler=f=function(b){a.onMouseMove(b)};
a.mouseUpHandler=g=function(b){a.onMouseUp(b)};e=a.getPartsEvents("mousedown");e.push(A(c.renderTo,"mousemove",f),A(d.ownerDocument,"mouseup",g));b&&(e.push(A(c.renderTo,"touchmove",f),A(d.ownerDocument,"touchend",g)),e.concat(a.getPartsEvents("touchstart")));a.eventsToUnbind=e;a.series&&a.series[0]&&e.push(A(a.series[0].xAxis,"foundExtremes",function(){c.navigator.modifyNavigatorAxisExtremes()}))};a.prototype.getPartsEvents=function(a){var b=this,c=[];["shades","handles"].forEach(function(d){b[d].forEach(function(e,
k){c.push(A(e.element,a,function(a){b[d+"Mousedown"](a,k)}))})});return c};a.prototype.shadesMousedown=function(a,b){a=this.chart.pointer.normalize(a);var c=this.chart,d=this.xAxis,k=this.zoomedMin,f=this.left,g=this.size,h=this.range,p=a.chartX;c.inverted&&(p=a.chartY,f=this.top);if(1===b)this.grabbedCenter=p,this.fixedWidth=h,this.dragOffset=p-k;else{a=p-f-h/2;if(0===b)a=Math.max(0,a);else if(2===b&&a+h>=g)if(a=g-h,this.reversedExtremes){a-=h;var m=this.getUnionExtremes().dataMin}else var l=this.getUnionExtremes().dataMax;
a!==k&&(this.fixedWidth=h,b=d.navigatorAxis.toFixedRange(a,a+h,m,l),e(b.min)&&c.xAxis[0].setExtremes(Math.min(b.min,b.max),Math.max(b.min,b.max),!0,null,{trigger:"navigator"}))}};a.prototype.handlesMousedown=function(a,b){this.chart.pointer.normalize(a);a=this.chart;var c=a.xAxis[0],d=this.reversedExtremes;0===b?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=d?c.min:c.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=d?c.max:c.min);a.fixedRange=
null};a.prototype.onMouseMove=function(a){var b=this,c=b.chart,d=b.left,e=b.navigatorSize,k=b.range,f=b.dragOffset,h=c.inverted;a.touches&&0===a.touches[0].pageX||(a=c.pointer.normalize(a),c=a.chartX,h&&(d=b.top,c=a.chartY),b.grabbedLeft?(b.hasDragged=!0,b.render(0,0,c-d,b.otherHandlePos)):b.grabbedRight?(b.hasDragged=!0,b.render(0,0,b.otherHandlePos,c-d)):b.grabbedCenter&&(b.hasDragged=!0,c<f?c=f:c>e+f-k&&(c=e+f-k),b.render(0,0,c-f,c-f+k)),b.hasDragged&&b.scrollbar&&g(b.scrollbar.options.liveRedraw,
u.svg&&!n&&!this.chart.isBoosting)&&(a.DOMType=a.type,setTimeout(function(){b.onMouseUp(a)},0)))};a.prototype.onMouseUp=function(a){var b=this.chart,c=this.xAxis,d=this.scrollbar,f=a.DOMEvent||a,k=b.inverted,g=this.rendered&&!this.hasDragged?"animate":"attr",h=Math.round(this.zoomedMax),m=Math.round(this.zoomedMin);if(this.hasDragged&&(!d||!d.hasDragged)||"scrollbar"===a.trigger){d=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var l=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var n=
this.fixedExtreme;this.zoomedMax===this.size&&(n=this.reversedExtremes?d.dataMin:d.dataMax);0===this.zoomedMin&&(l=this.reversedExtremes?d.dataMax:d.dataMin);c=c.navigatorAxis.toFixedRange(this.zoomedMin,this.zoomedMax,l,n);e(c.min)&&b.xAxis[0].setExtremes(Math.min(c.min,c.max),Math.max(c.min,c.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:f})}"mousemove"!==a.DOMType&&"touchmove"!==a.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=
this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null);this.navigatorEnabled&&(this.shades&&this.drawMasks(m,h,k,g),this.outline&&this.drawOutline(m,h,k,g),this.navigatorOptions.handles.enabled&&Object.keys(this.handles).length===this.handles.length&&(this.drawHandle(m,0,k,g),this.drawHandle(h,1,k,g)))};a.prototype.removeEvents=function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(a){a()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()};a.prototype.removeBaseSeriesEvents=
function(){var a=this.baseSeries||[];this.navigatorEnabled&&a[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&a.forEach(function(a){t(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&t(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))};a.prototype.init=function(a){var b=a.options,c=b.navigator,d=c.enabled,e=b.scrollbar,f=e.enabled;b=d?c.height:0;var k=f?e.height:0;this.handles=[];this.shades=[];this.chart=a;this.setBaseSeries();this.height=b;this.scrollbarHeight=k;this.scrollbarEnabled=
f;this.navigatorEnabled=d;this.navigatorOptions=c;this.scrollbarOptions=e;this.outlineHeight=b+k;this.opposite=g(c.opposite,!(d||!a.inverted));var l=this;d=l.baseSeries;e=a.xAxis.length;f=a.yAxis.length;var n=d&&d[0]&&d[0].xAxis||a.xAxis[0]||{options:{}};a.isDirtyBox=!0;l.navigatorEnabled?(l.xAxis=new h(a,q({breaks:n.options.breaks,ordinal:n.options.ordinal},c.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:e,isInternal:!0,offset:0,keepOrdinalPadding:!0,startOnTick:!1,
endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},a.inverted?{offsets:[k,0,-k,0],width:b}:{offsets:[0,-k,0,k],height:b})),l.yAxis=new h(a,q(c.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:f,isInternal:!0,zoomEnabled:!1},a.inverted?{width:b}:{height:b})),d||c.series.data?l.updateNavigatorSeries(!1):0===a.series.length&&(l.unbindRedraw=A(a,"beforeRedraw",function(){0<a.series.length&&!l.series&&(l.setBaseSeries(),l.unbindRedraw())})),l.reversedExtremes=a.inverted&&!l.xAxis.reversed||
!a.inverted&&l.xAxis.reversed,l.renderElements(),l.addMouseEvents()):(l.xAxis={chart:a,navigatorAxis:{fake:!0},translate:function(b,c){var d=a.xAxis[0],e=d.getExtremes(),f=d.len-2*k,g=H("min",d.options.min,e.dataMin);d=H("max",d.options.max,e.dataMax)-g;return c?b*d/f+g:f*(b-g)/d},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,!0)}},l.xAxis.navigatorAxis.axis=l.xAxis,l.xAxis.navigatorAxis.toFixedRange=m.AdditionsClass.prototype.toFixedRange.bind(l.xAxis.navigatorAxis));
a.options.scrollbar.enabled&&(a.scrollbar=l.scrollbar=new w(a.renderer,q(a.options.scrollbar,{margin:l.navigatorEnabled?0:10,vertical:a.inverted}),a),A(l.scrollbar,"changed",function(b){var c=l.size,d=c*this.to;c*=this.from;l.hasDragged=l.scrollbar.hasDragged;l.render(0,0,c,d);(a.options.scrollbar.liveRedraw||"mousemove"!==b.DOMType&&"touchmove"!==b.DOMType)&&setTimeout(function(){l.onMouseUp(b)})}));l.addBaseSeriesEvents();l.addChartEvents()};a.prototype.getUnionExtremes=function(a){var b=this.chart.xAxis[0],
c=this.xAxis,d=c.options,e=b.options,f;a&&null===b.dataMin||(f={dataMin:g(d&&d.min,H("min",e.min,b.dataMin,c.dataMin,c.min)),dataMax:g(d&&d.max,H("max",e.max,b.dataMax,c.dataMax,c.max))});return f};a.prototype.setBaseSeries=function(a,b){var c=this.chart,d=this.baseSeries=[];a=a||c.options&&c.options.navigator.baseSeries||(c.series.length?E(c.series,function(a){return!a.options.isInternal}).index:0);(c.series||[]).forEach(function(b,c){b.options.isInternal||!b.options.showInNavigator&&(c!==a&&b.options.id!==
a||!1===b.options.showInNavigator)||d.push(b)});this.xAxis&&!this.xAxis.navigatorAxis.fake&&this.updateNavigatorSeries(!0,b)};a.prototype.updateNavigatorSeries=function(a,b){var e=this,f=e.chart,k=e.baseSeries,h,l,m=e.navigatorOptions.series,p,n={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:void 0,isInternal:!0,states:{inactive:{opacity:1}}},u=e.series=(e.series||[]).filter(function(a){var b=a.baseSeries;
return 0>k.indexOf(b)?(b&&(t(b,"updatedData",e.updatedDataHandler),delete b.navigatorSeries),a.chart&&a.destroy(),!1):!0});k&&k.length&&k.forEach(function(a){var d=a.navigatorSeries,t=r({color:a.color,visible:a.visible},F(m)?c.navigator.series:m);d&&!1===e.navigatorOptions.adaptToUpdatedData||(n.name="Navigator "+k.length,h=a.options||{},p=h.navigatorOptions||{},l=q(h,n,t,p),l.pointRange=g(t.pointRange,p.pointRange,c.plotOptions[l.type||"line"].pointRange),t=p.data||t.data,e.hasNavigatorData=e.hasNavigatorData||
!!t,l.data=t||h.data&&h.data.slice(0),d&&d.options?d.update(l,b):(a.navigatorSeries=f.initSeries(l),a.navigatorSeries.baseSeries=a,u.push(a.navigatorSeries)))});if(m.data&&(!k||!k.length)||F(m))e.hasNavigatorData=!1,m=d(m),m.forEach(function(a,b){n.name="Navigator "+(u.length+1);l=q(c.navigator.series,{color:f.series[b]&&!f.series[b].options.isInternal&&f.series[b].color||f.options.colors[b]||f.options.colors[0]},n,a);l.data=a.data;l.data&&(e.hasNavigatorData=!0,u.push(f.initSeries(l)))});a&&this.addBaseSeriesEvents()};
a.prototype.addBaseSeriesEvents=function(){var a=this,b=a.baseSeries||[];b[0]&&b[0].xAxis&&A(b[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);b.forEach(function(b){A(b,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});A(b,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&b.xAxis&&A(b,"updatedData",this.updatedDataHandler);A(b,"remove",function(){this.navigatorSeries&&(l(a.series,this.navigatorSeries),
e(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)};a.prototype.getBaseSeriesMin=function(a){return this.baseSeries.reduce(function(a,b){return Math.min(a,b.xData?b.xData[0]:a)},a)};a.prototype.modifyNavigatorAxisExtremes=function(){var a=this.xAxis,b;"undefined"!==typeof a.getExtremes&&(!(b=this.getUnionExtremes(!0))||b.dataMin===a.min&&b.dataMax===a.max||(a.min=b.dataMin,a.max=b.dataMax))};a.prototype.modifyBaseAxisExtremes=function(){var a=this.chart.navigator,
b=this.getExtremes(),c=b.dataMin,d=b.dataMax;b=b.max-b.min;var e=a.stickToMin,f=a.stickToMax,h=g(this.options.overscroll,0),l=a.series&&a.series[0],m=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(e){var n=c;var q=n+b}f&&(q=d+h,e||(n=Math.max(c,q-b,a.getBaseSeriesMin(l&&l.xData?l.xData[0]:-Number.MAX_VALUE))));m&&(e||f)&&C(n)&&(this.min=this.userMin=n,this.max=this.userMax=q)}a.stickToMin=a.stickToMax=null};a.prototype.updatedDataHandler=function(){var a=
this.chart.navigator,b=this.navigatorSeries,c=a.getBaseSeriesMin(this.xData[0]);a.stickToMax=a.reversedExtremes?0===Math.round(a.zoomedMin):Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=C(this.xAxis.min)&&this.xAxis.min<=c&&(!this.chart.fixedRange||!a.stickToMax);b&&!a.hasNavigatorData&&(b.options.pointStart=this.xData[0],b.setData(this.options.data,!1,null,!1))};a.prototype.addChartEvents=function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(A(this.chart,"redraw",
function(){var a=this.navigator,b=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||this.xAxis[0]);b&&a.render(b.min,b.max)}),A(this.chart,"getMargins",function(){var a=this.navigator,b=a.opposite?"plotTop":"marginBottom";this.inverted&&(b=a.opposite?"marginRight":"plotLeft");this[b]=(this[b]||0)+(a.navigatorEnabled||!this.inverted?a.outlineHeight:0)+a.navigatorOptions.margin}))};a.prototype.destroy=function(){this.removeEvents();this.xAxis&&(l(this.chart.xAxis,this.xAxis),l(this.chart.axes,
this.xAxis));this.yAxis&&(l(this.chart.yAxis,this.yAxis),l(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(a){a.destroy&&a.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(a){this[a]&&this[a].destroy&&this[a].destroy();this[a]=null},this);[this.handles].forEach(function(a){f(a)},this)};return a}();u.Navigator||(u.Navigator=B,m.compose(h),A(v,"beforeShowResetZoom",function(){var a=
this.options,b=a.navigator,c=a.rangeSelector;if((b&&b.enabled||c&&c.enabled)&&(!n&&"x"===a.chart.zoomType||n&&"x"===a.chart.pinchType))return!1}),A(v,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new B(this)}),A(v,"afterSetChartSize",function(){var a=this.legend,b=this.navigator;if(b){var c=a&&a.options;var d=b.xAxis;var e=b.yAxis;var f=b.scrollbarHeight;this.inverted?(b.left=b.opposite?this.chartWidth-f-b.height:this.spacing[3]+
f,b.top=this.plotTop+f):(b.left=this.plotLeft+f,b.top=b.navigatorOptions.top||this.chartHeight-b.height-f-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(c&&"bottom"===c.verticalAlign&&c.enabled&&!c.floating?a.legendHeight+g(c.margin,10):0)-(this.titleOffset?this.titleOffset[2]:0));d&&e&&(this.inverted?d.options.left=e.options.left=b.left:d.options.top=e.options.top=b.top,d.setAxisSize(),e.setAxisSize())}}),A(v,"update",function(a){var b=a.options.navigator||
{},c=a.options.scrollbar||{};this.navigator||this.scroller||!b.enabled&&!c.enabled||(q(!0,this.options.navigator,b),q(!0,this.options.scrollbar,c),delete a.options.navigator,delete a.options.scrollbar)}),A(v,"afterUpdate",function(a){this.navigator||this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new B(this),g(a.redraw,!0)&&this.redraw(a.animation))}),A(v,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),
A(G,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),v.prototype.callbacks.push(function(a){var b=a.navigator;b&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),b.render(a.min,a.max))}));u.Navigator=B;return u.Navigator});G(h,"masters/modules/gantt.src.js",[],function(){})});
//# sourceMappingURL=gantt.js.map