/*
 Highcharts Gantt JS v8.0.4 (2020-04-22)

 Tree Grid

 (c) 2016-2019 Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(f){"object"===typeof module&&module.exports?(f["default"]=f,module.exports=f):"function"===typeof define&&define.amd?define("highcharts/modules/treegrid",["highcharts"],function(A){f(A);f.Highcharts=A;return f}):f("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(f){function A(f,u,z,x){f.hasOwnProperty(u)||(f[u]=x.apply(null,z))}f=f?f._modules:{};A(f,"mixins/tree-series.js",[f["parts/Color.js"],f["parts/Utilities.js"]],function(f,u){var z=u.extend,x=u.isArray,c=u.isNumber,n=
u.isObject,F=u.merge,C=u.pick;return{getColor:function(l,d){var c=d.index,v=d.mapOptionsToLevel,w=d.parentColor,r=d.parentColorIndex,y=d.series,k=d.colors,e=d.siblings,h=y.points,t=y.chart.options.chart,a;if(l){h=h[l.i];l=v[l.level]||{};if(v=h&&l.colorByPoint){var b=h.index%(k?k.length:t.colorCount);var g=k&&k[b]}if(!y.chart.styledMode){k=h&&h.options.color;t=l&&l.color;if(a=w)a=(a=l&&l.colorVariation)&&"brightness"===a.key?f.parse(w).brighten(c/e*a.to).get():w;a=C(k,t,g,a,y.color)}var H=C(h&&h.options.colorIndex,
l&&l.colorIndex,b,r,d.colorIndex)}return{color:a,colorIndex:H}},getLevelOptions:function(l){var d=null;if(n(l)){d={};var f=c(l.from)?l.from:1;var v=l.levels;var w={};var r=n(l.defaults)?l.defaults:{};x(v)&&(w=v.reduce(function(d,k){if(n(k)&&c(k.level)){var e=F({},k);var h="boolean"===typeof e.levelIsConstant?e.levelIsConstant:r.levelIsConstant;delete e.levelIsConstant;delete e.level;k=k.level+(h?0:f-1);n(d[k])?z(d[k],e):d[k]=e}return d},{}));v=c(l.to)?l.to:1;for(l=0;l<=v;l++)d[l]=F({},r,n(w[l])?w[l]:
{})}return d},setTreeValues:function v(d,c){var w=c.before,r=c.idRoot,y=c.mapIdToNode[r],k=c.points[d.i],e=k&&k.options||{},h=0,t=[];z(d,{levelDynamic:d.level-(("boolean"===typeof c.levelIsConstant?c.levelIsConstant:1)?0:y.level),name:C(k&&k.name,""),visible:r===d.id||("boolean"===typeof c.visible?c.visible:!1)});"function"===typeof w&&(d=w(d,c));d.children.forEach(function(a,b){var g=z({},c);z(g,{index:b,siblings:d.children.length,visible:d.visible});a=v(a,g);t.push(a);a.visible&&(h+=a.val)});d.visible=
0<h||d.visible;w=C(e.value,h);z(d,{children:t,childrenTotal:h,isLeaf:d.visible&&!h,val:w});return d},updateRootId:function(d){if(n(d)){var c=n(d.options)?d.options:{};c=C(d.rootNode,c.rootId,"");n(d.userOptions)&&(d.userOptions.rootId=c);d.rootNode=c}return c}}});A(f,"parts-gantt/Tree.js",[f["parts/Utilities.js"]],function(f){var u=f.extend,z=f.isNumber,x=f.pick,c=function(c,f){var l=c.reduce(function(d,c){var f=x(c.parent,"");"undefined"===typeof d[f]&&(d[f]=[]);d[f].push(c);return d},{});Object.keys(l).forEach(function(d,
c){var n=l[d];""!==d&&-1===f.indexOf(d)&&(n.forEach(function(d){c[""].push(d)}),delete c[d])});return l},n=function(c,f,l,d,B,v){var w=0,r=0,y=v&&v.after,k=v&&v.before;f={data:d,depth:l-1,id:c,level:l,parent:f};var e,h;"function"===typeof k&&k(f,v);k=(B[c]||[]).map(function(d){var a=n(d.id,c,l+1,d,B,v),b=d.start;d=!0===d.milestone?b:d.end;e=!z(e)||b<e?b:e;h=!z(h)||d>h?d:h;w=w+1+a.descendants;r=Math.max(a.height+1,r);return a});d&&(d.start=x(d.start,e),d.end=x(d.end,h));u(f,{children:k,descendants:w,
height:r});"function"===typeof y&&y(f,v);return f};return{getListOfParents:c,getNode:n,getTree:function(f,u){var l=f.map(function(d){return d.id});f=c(f,l);return n("",null,1,null,f,u)}}});A(f,"parts-gantt/GridAxis.js",[f["parts/Axis.js"],f["parts/Globals.js"],f["parts/Tick.js"],f["parts/Utilities.js"]],function(f,u,z,x){var c=x.addEvent,n=x.defined,B=x.erase,C=x.find,l=x.isArray,d=x.isNumber,D=x.merge,v=x.pick,w=x.timeUnits,r=x.wrap,y=u.dateFormat,k=u.Chart,e=function(a){var b=a.options;b.labels||
(b.labels={});b.labels.align=v(b.labels.align,"center");a.categories||(b.showLastLabel=!1);a.labelRotation=0;b.labels.rotation=0};"";f.prototype.getMaxLabelDimensions=function(a,b){var g={width:0,height:0};b.forEach(function(b){b=a[b];if(x.isObject(b,!0)){var e=x.isObject(b.label,!0)?b.label:{};b=e.getBBox?e.getBBox().height:0;e.textStr&&!d(e.textPxLength)&&(e.textPxLength=e.getBBox().width);e=d(e.textPxLength)?Math.round(e.textPxLength):0;g.height=Math.max(b,g.height);g.width=Math.max(e,g.width)}});
return g};u.dateFormats.W=function(a){a=new this.Date(a);var b=(this.get("Day",a)+6)%7,g=new this.Date(a.valueOf());this.set("Date",g,this.get("Date",a)-b+3);b=new this.Date(this.get("FullYear",g),0,1);4!==this.get("Day",b)&&(this.set("Month",a,0),this.set("Date",a,1+(11-this.get("Day",b))%7));return(1+Math.floor((g.valueOf()-b.valueOf())/6048E5)).toString()};u.dateFormats.E=function(a){return y("%a",a,!0).charAt(0)};c(k,"afterSetChartSize",function(){this.axes.forEach(function(a){(a.grid&&a.grid.columns||
[]).forEach(function(b){b.setAxisSize();b.setAxisTranslation()})})});c(z,"afterGetLabelPosition",function(a){var b=this.label,g=this.axis,e=g.reversed,h=g.chart,c=g.options.grid||{},f=g.options.labels,p=f.align,m=t.Side[g.side],q=a.tickmarkOffset,E=g.tickPositions,k=this.pos-q;E=d(E[a.index+1])?E[a.index+1]-q:g.max+q;var r=g.tickSize("tick",!0);q=l(r)?r[0]:0;r=r&&r[1]/2;if(!0===c.enabled){if("top"===m){c=g.top+g.offset;var y=c-q}else"bottom"===m?(y=h.chartHeight-g.bottom+g.offset,c=y+q):(c=g.top+
g.len-g.translate(e?E:k),y=g.top+g.len-g.translate(e?k:E));"right"===m?(m=h.chartWidth-g.right+g.offset,e=m+q):"left"===m?(e=g.left+g.offset,m=e-q):(m=Math.round(g.left+g.translate(e?E:k))-r,e=Math.round(g.left+g.translate(e?k:E))-r);this.slotWidth=e-m;a.pos.x="left"===p?m:"right"===p?e:m+(e-m)/2;a.pos.y=y+(c-y)/2;h=h.renderer.fontMetrics(f.style.fontSize,b.element);b=b.getBBox().height;f.useHTML?a.pos.y+=h.b+-(b/2):(b=Math.round(b/h.h),a.pos.y+=(h.b-(h.h-h.f))/2+-((b-1)*h.h/2));a.pos.x+=g.horiz&&
f.x||0}});var h=function(){function a(b){this.axis=b}a.prototype.isOuterAxis=function(){var b=this.axis,g=b.grid.columnIndex,a=b.linkedParent&&b.linkedParent.grid.columns||b.grid.columns,e=g?b.linkedParent:b,h=-1,c=0;b.chart[b.coll].forEach(function(g,m){g.side!==b.side||g.options.isInternal||(c=m,g===e&&(h=m))});return c===h&&(d(g)?a.length===g:!0)};return a}(),t=function(){function a(){}a.compose=function(b){f.keepProps.push("grid");r(b.prototype,"unsquish",a.wrapUnsquish);c(b,"init",a.onInit);
c(b,"afterGetOffset",a.onAfterGetOffset);c(b,"afterGetTitlePosition",a.onAfterGetTitlePosition);c(b,"afterInit",a.onAfterInit);c(b,"afterRender",a.onAfterRender);c(b,"afterSetAxisTranslation",a.onAfterSetAxisTranslation);c(b,"afterSetOptions",a.onAfterSetOptions);c(b,"afterSetOptions",a.onAfterSetOptions2);c(b,"afterSetScale",a.onAfterSetScale);c(b,"afterTickSize",a.onAfterTickSize);c(b,"trimTicks",a.onTrimTicks);c(b,"destroy",a.onDestroy)};a.onAfterGetOffset=function(){var b=this.grid;(b&&b.columns||
[]).forEach(function(b){b.getOffset()})};a.onAfterGetTitlePosition=function(b){if(!0===(this.options.grid||{}).enabled){var g=this.axisTitle,e=this.height,d=this.horiz,h=this.left,c=this.offset,p=this.opposite,m=this.options.title,q=void 0===m?{}:m;m=this.top;var E=this.width,f=this.tickSize(),k=g&&g.getBBox().width,r=q.x||0,y=q.y||0,t=v(q.margin,d?5:10);g=this.chart.renderer.fontMetrics(q.style&&q.style.fontSize,g).f;f=(d?m+e:h)+f[0]/2*(p?-1:1)*(d?1:-1)+(this.side===a.Side.bottom?g:0);b.titlePosition.x=
d?h-k/2-t+r:f+(p?E:0)+c+r;b.titlePosition.y=d?f-(p?e:0)+(p?g:-g)/2+c+y:m-t+y}};a.onAfterInit=function(){var b=this.chart,g=this.options.grid;g=void 0===g?{}:g;var a=this.userOptions;g.enabled&&(e(this),r(this,"labelFormatter",function(b){var m=this.axis,g=this.value,a=m.tickPositions,e=(m.isLinked?m.linkedParent:m).series[0],p=g===a[0];a=g===a[a.length-1];e=e&&C(e.options.data,function(b){return b[m.isXAxis?"x":"y"]===g});this.isFirst=p;this.isLast=a;this.point=e;return b.call(this)}));if(g.columns)for(var d=
this.grid.columns=[],h=this.grid.columnIndex=0;++h<g.columns.length;){var c=D(a,g.columns[g.columns.length-h-1],{linkedTo:0,type:"category"});delete c.grid.columns;c=new f(this.chart,c);c.grid.isColumn=!0;c.grid.columnIndex=h;B(b.axes,c);B(b[this.coll],c);d.push(c)}};a.onAfterRender=function(){var b=this.grid,g=this.options,e=this.chart.renderer;if(!0===(g.grid||{}).enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,this.tickPositions);this.rightWall&&this.rightWall.destroy();
if(this.grid&&this.grid.isOuterAxis()&&this.axisLine){var d=g.lineWidth;if(d){var h=this.getLinePath(d),c=h[0],p=h[1],m=(this.tickSize("tick")[0]-1)*(this.side===a.Side.top||this.side===a.Side.left?-1:1);"M"===c[0]&&"L"===p[0]&&(this.horiz?(c[2]+=m,p[2]+=m):(c[1]+=m,p[1]+=m));this.grid.axisLineExtra?this.grid.axisLineExtra.animate({d:h}):(this.grid.axisLineExtra=e.path(h).attr({zIndex:7}).addClass("highcharts-axis-line").add(this.axisGroup),e.styledMode||this.grid.axisLineExtra.attr({stroke:g.lineColor,
"stroke-width":d}));this.axisLine[this.showAxis?"show":"hide"](!0)}}(b&&b.columns||[]).forEach(function(b){b.render()})}};a.onAfterSetAxisTranslation=function(){var b=this.tickPositions&&this.tickPositions.info,g=this.options,a=g.grid||{},e=this.userOptions.labels||{};this.horiz&&(!0===a.enabled&&this.series.forEach(function(b){b.options.pointRange=0}),b&&g.dateTimeLabelFormats&&g.labels&&!n(e.align)&&(!1===g.dateTimeLabelFormats[b.unitName].range||1<b.count)&&(g.labels.align="left",n(e.x)||(g.labels.x=
3)))};a.onAfterSetOptions=function(b){var g=this.options;b=b.userOptions;var a=g&&x.isObject(g.grid,!0)?g.grid:{};if(!0===a.enabled){var e=D(!0,{className:"highcharts-grid-axis "+(b.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],
["second",[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},b);"xAxis"===this.coll&&(n(b.linkedTo)&&!n(b.tickPixelInterval)&&(e.tickPixelInterval=350),n(b.tickPixelInterval)||!n(b.linkedTo)||n(b.tickPositioner)||n(b.tickInterval)||(e.tickPositioner=function(b,g){var a=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(a){var m,c=e.units;for(m=0;m<c.length;m++)if(c[m][0]===a.unitName){var d=m;break}if(c[d+1]){var h=
c[d+1][0];var f=(c[d+1][1]||[1])[0]}else"year"===a.unitName&&(h="year",f=10*a.count);a=w[h];this.tickInterval=a*f;return this.getTimeTicks({unitRange:a,count:f,unitName:h},b,g,this.options.startOfWeek)}}));D(!0,this.options,e);this.horiz&&(g.minPadding=v(b.minPadding,0),g.maxPadding=v(b.maxPadding,0));d(g.grid.borderWidth)&&(g.tickWidth=g.lineWidth=a.borderWidth)}};a.onAfterSetOptions2=function(b){b=(b=b.userOptions)&&b.grid||{};var a=b.columns;b.enabled&&a&&D(!0,this.options,a[a.length-1])};a.onAfterSetScale=
function(){(this.grid.columns||[]).forEach(function(b){b.setScale()})};a.onAfterTickSize=function(b){var a=f.defaultLeftAxisOptions,e=this.horiz,c=this.maxLabelDimensions,d=this.options.grid;d=void 0===d?{}:d;d.enabled&&c&&(a=2*Math.abs(a.labels.x),e=e?d.cellHeight||a+c.height:a+c.width,l(b.tickSize)?b.tickSize[0]=e:b.tickSize=[e])};a.onDestroy=function(b){var a=this.grid;(a.columns||[]).forEach(function(a){a.destroy(b.keepEvents)});a.columns=void 0};a.onInit=function(a){a=a.userOptions||{};var b=
a.grid||{};b.enabled&&n(b.borderColor)&&(a.tickColor=a.lineColor=b.borderColor);this.grid||(this.grid=new h(this))};a.onTrimTicks=function(){var a=this.options,e=this.categories,c=this.tickPositions,d=c[0],h=c[c.length-1],f=this.linkedParent&&this.linkedParent.min||this.min,p=this.linkedParent&&this.linkedParent.max||this.max,m=this.tickInterval;!0!==(a.grid||{}).enabled||e||!this.horiz&&!this.isLinked||(d<f&&d+m>f&&!a.startOnTick&&(c[0]=f),h>p&&h-m<p&&!a.endOnTick&&(c[c.length-1]=p))};a.wrapUnsquish=
function(a){var b=this.options.grid;return!0===(void 0===b?{}:b).enabled&&this.categories?this.tickInterval:a.apply(this,Array.prototype.slice.call(arguments,1))};return a}();(function(a){a=a.Side||(a.Side={});a[a.top=0]="top";a[a.right=1]="right";a[a.bottom=2]="bottom";a[a.left=3]="left"})(t||(t={}));t.compose(f);return t});A(f,"modules/broken-axis.src.js",[f["parts/Axis.js"],f["parts/Globals.js"],f["parts/Utilities.js"],f["parts/Stacking.js"]],function(f,u,z,x){var c=z.addEvent,n=z.find,B=z.fireEvent,
C=z.isArray,l=z.isNumber,d=z.pick,D=u.Series,v=function(){function c(c){this.hasBreaks=!1;this.axis=c}c.isInBreak=function(c,d){var f=c.repeat||Infinity,e=c.from,h=c.to-c.from;d=d>=e?(d-e)%f:f-(e-d)%f;return c.inclusive?d<=h:d<h&&0!==d};c.lin2Val=function(d){var f=this.brokenAxis;f=f&&f.breakArray;if(!f)return d;var k;for(k=0;k<f.length;k++){var e=f[k];if(e.from>=d)break;else e.to<d?d+=e.len:c.isInBreak(e,d)&&(d+=e.len)}return d};c.val2Lin=function(d){var f=this.brokenAxis;f=f&&f.breakArray;if(!f)return d;
var k=d,e;for(e=0;e<f.length;e++){var h=f[e];if(h.to<=d)k-=h.len;else if(h.from>=d)break;else if(c.isInBreak(h,d)){k-=d-h.from;break}}return k};c.prototype.findBreakAt=function(c,d){return n(d,function(d){return d.from<c&&c<d.to})};c.prototype.isInAnyBreak=function(f,l){var k=this.axis,e=k.options.breaks,h=e&&e.length,t;if(h){for(;h--;)if(c.isInBreak(e[h],f)){var a=!0;t||(t=d(e[h].showPoints,!k.isXAxis))}var b=a&&l?a&&!t:a}return b};c.prototype.setBreaks=function(l,n){var k=this,e=k.axis,h=C(l)&&
!!l.length;e.isDirty=k.hasBreaks!==h;k.hasBreaks=h;e.options.breaks=e.userOptions.breaks=l;e.forceRedraw=!0;e.series.forEach(function(e){e.isDirty=!0});h||e.val2lin!==c.val2Lin||(delete e.val2lin,delete e.lin2val);h&&(e.userOptions.ordinal=!1,e.lin2val=c.lin2Val,e.val2lin=c.val2Lin,e.setExtremes=function(e,a,b,c,d){if(k.hasBreaks){for(var g,h=this.options.breaks;g=k.findBreakAt(e,h);)e=g.to;for(;g=k.findBreakAt(a,h);)a=g.from;a<e&&(a=e)}f.prototype.setExtremes.call(this,e,a,b,c,d)},e.setAxisTranslation=
function(h){f.prototype.setAxisTranslation.call(this,h);k.unitLength=null;if(k.hasBreaks){h=e.options.breaks||[];var a=[],b=[],g=0,l,t=e.userMin||e.min,n=e.userMax||e.max,r=d(e.pointRangePadding,0),p;h.forEach(function(a){l=a.repeat||Infinity;c.isInBreak(a,t)&&(t+=a.to%l-t%l);c.isInBreak(a,n)&&(n-=n%l-a.from%l)});h.forEach(function(b){q=b.from;for(l=b.repeat||Infinity;q-l>t;)q-=l;for(;q<t;)q+=l;for(p=q;p<n;p+=l)a.push({value:p,move:"in"}),a.push({value:p+(b.to-b.from),move:"out",size:b.breakSize})});
a.sort(function(a,b){return a.value===b.value?("in"===a.move?0:1)-("in"===b.move?0:1):a.value-b.value});var m=0;var q=t;a.forEach(function(a){m+="in"===a.move?1:-1;1===m&&"in"===a.move&&(q=a.value);0===m&&(b.push({from:q,to:a.value,len:a.value-q-(a.size||0)}),g+=a.value-q-(a.size||0))});e.breakArray=k.breakArray=b;k.unitLength=n-t-g+r;B(e,"afterBreaks");e.staticScale?e.transA=e.staticScale:k.unitLength&&(e.transA*=(n-e.min+r)/k.unitLength);r&&(e.minPixelPadding=e.transA*e.minPointOffset);e.min=t;
e.max=n}});d(n,!0)&&e.chart.redraw()};return c}();u=function(){function f(){}f.compose=function(f,n){f.keepProps.push("brokenAxis");var k=D.prototype;k.drawBreaks=function(e,c){var f=this,a=f.points,b,g,h,k;if(e&&e.brokenAxis&&e.brokenAxis.hasBreaks){var n=e.brokenAxis;c.forEach(function(c){b=n&&n.breakArray||[];g=e.isXAxis?e.min:d(f.options.threshold,e.min);a.forEach(function(a){k=d(a["stack"+c.toUpperCase()],a[c]);b.forEach(function(b){if(l(g)&&l(k)){h=!1;if(g<b.from&&k>b.to||g>b.from&&k<b.from)h=
"pointBreak";else if(g<b.from&&k>b.from&&k<b.to||g>b.from&&k>b.to&&k<b.from)h="pointInBreak";h&&B(e,h,{point:a,brk:b})}})})})}};k.gappedPath=function(){var e=this.currentDataGrouping,c=e&&e.gapSize;e=this.options.gapSize;var d=this.points.slice(),a=d.length-1,b=this.yAxis,g;if(e&&0<a)for("value"!==this.options.gapUnit&&(e*=this.basePointRange),c&&c>e&&c>=this.basePointRange&&(e=c),g=void 0;a--;)g&&!1!==g.visible||(g=d[a+1]),c=d[a],!1!==g.visible&&!1!==c.visible&&(g.x-c.x>e&&(g=(c.x+g.x)/2,d.splice(a+
1,0,{isNull:!0,x:g}),b.stacking&&this.options.stacking&&(g=b.stacking.stacks[this.stackKey][g]=new x(b,b.options.stackLabels,!1,g,this.stack),g.total=0)),g=c);return this.getGraphPath(d)};c(f,"init",function(){this.brokenAxis||(this.brokenAxis=new v(this))});c(f,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)});c(f,"afterSetTickPositions",function(){var c=this.brokenAxis;if(c&&c.hasBreaks){var d=this.tickPositions,f=this.tickPositions.info,
a=[],b;for(b=0;b<d.length;b++)c.isInAnyBreak(d[b])||a.push(d[b]);this.tickPositions=a;this.tickPositions.info=f}});c(f,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});c(n,"afterGeneratePoints",function(){var c=this.options.connectNulls,d=this.points,f=this.xAxis,a=this.yAxis;if(this.isDirty)for(var b=d.length;b--;){var g=d[b],k=!(null===g.y&&!1===c)&&(f&&f.brokenAxis&&f.brokenAxis.isInAnyBreak(g.x,!0)||a&&a.brokenAxis&&a.brokenAxis.isInAnyBreak(g.y,
!0));g.visible=k?!1:!1!==g.options.visible}});c(n,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,d(this.pointArrayMap,["y"]))})};return f}();u.compose(f,D);return u});A(f,"parts-gantt/TreeGrid.js",[f["parts/Globals.js"],f["mixins/tree-series.js"],f["parts/Tick.js"],f["parts-gantt/Tree.js"],f["parts/Utilities.js"]],function(f,u,z,x,c){var n=c.addEvent,A=c.defined,C=c.fireEvent,l=c.extend,d=c.isNumber,D=c.isString,v=c.merge,w=c.pick,r=c.wrap,y=function(a){return Array.prototype.slice.call(a,
1)},k=c.find,e=u.getLevelOptions,h=function(a){return c.isObject(a,!0)};f=f.Axis;u=function(a,b){var c;for(c in b)if(Object.hasOwnProperty.call(b,c)){var d=b[c];r(a,c,d)}};var t=function(a,b){var c=a.collapseStart;a=a.collapseEnd;a>=b&&(c-=.5);return{from:c,to:a,showPoints:!1}},a=function(a){return Object.keys(a.mapOfPosToGridNode).reduce(function(b,c){c=+c;!(a.min<=c&&a.max>=c)||a.brokenAxis&&a.brokenAxis.isInAnyBreak(c)||b.push(c);return b},[])},b=function(a,b){var c=a.options.breaks||[],d=t(b,
a.max);return c.some(function(a){return a.from===d.from&&a.to===d.to})},g=function(a,b){var c=a.options.breaks||[];a=t(b,a.max);c.push(a);return c},B=function(a,b){var c=a.options.breaks||[],d=t(b,a.max);return c.reduce(function(a,b){b.to===d.to&&b.from===d.from||a.push(b);return a},[])},I=function(a,b){var c=a.labelIcon,e=!c,f=b.renderer,g=b.xy,m=b.options,h=m.width,k=m.height,l=g.x-h/2-m.padding;g=g.y-k/2;var p=b.collapsed?90:180,n=b.show&&d(g);e&&(a.labelIcon=c=f.path(f.symbols[m.type](m.x,m.y,
h,k)).addClass("highcharts-label-icon").add(b.group));n||c.attr({y:-9999});f.styledMode||c.attr({"stroke-width":1,fill:w(b.color,"#666666")}).css({cursor:"pointer",stroke:m.lineColor,strokeWidth:m.lineWidth});c[e?"attr":"animate"]({translateX:l,translateY:g,rotation:p})},J=function(a,b,c){var d=[],e=[],g={},f={},m=-1,l="boolean"===typeof b?b:!1;a=x.getTree(a,{after:function(a){a=f[a.pos];var b=0,c=0;a.children.forEach(function(a){c+=a.descendants+1;b=Math.max(a.height+1,b)});a.descendants=c;a.height=
b;a.collapsed&&e.push(a)},before:function(a){var b=h(a.data)?a.data:{},c=D(b.name)?b.name:"",e=g[a.parent];e=h(e)?f[e.pos]:null;var q=function(a){return a.name===c},p;l&&h(e)&&(p=k(e.children,q))?(q=p.pos,p.nodes.push(a)):q=m++;f[q]||(f[q]=p={depth:e?e.depth+1:0,name:c,nodes:[a],children:[],pos:q},-1!==q&&d.push(c),h(e)&&e.children.push(p));D(a.id)&&(g[a.id]=a);!0===b.collapsed&&(p.collapsed=!0);a.pos=q}});f=function(a,b){var c=function(a,e,d){var f=e+(-1===e?0:b-1),g=(f-e)/2,m=e+g;a.nodes.forEach(function(a){var b=
a.data;h(b)&&(b.y=e+b.seriesIndex,delete b.seriesIndex);a.pos=m});d[m]=a;a.pos=m;a.tickmarkOffset=g+.5;a.collapseStart=f+.5;a.children.forEach(function(a){c(a,f+1,d);f=a.collapseEnd-.5});a.collapseEnd=f+.5;return d};return c(a["-1"],-1,{})}(f,c);return{categories:d,mapOfIdToNode:g,mapOfPosToGridNode:f,collapsedNodes:e,tree:a}},G=function(a){a.target.axes.filter(function(a){return"treegrid"===a.options.type}).forEach(function(b){var c=b.options||{},d=c.labels,f,m=c.uniqueNames,k=0;if(!b.mapOfPosToGridNode||
b.series.some(function(a){return!a.hasRendered||a.isDirtyData||a.isDirty})){c=b.series.reduce(function(a,b){b.visible&&(b.options.data.forEach(function(b){h(b)&&(b.seriesIndex=k,a.push(b))}),!0===m&&k++);return a},[]);var l=J(c,m,!0===m?k:1);b.categories=l.categories;b.mapOfPosToGridNode=l.mapOfPosToGridNode;b.hasNames=!0;b.tree=l.tree;b.series.forEach(function(a){var b=a.options.data.map(function(a){return h(a)?v(a):a});a.visible&&a.setData(b,!1)});b.mapOptionsToLevel=e({defaults:d,from:1,levels:d.levels,
to:b.tree.height});"beforeRender"===a.type&&(f=n(b,"foundExtremes",function(){l.collapsedNodes.forEach(function(a){a=g(b,a);b.brokenAxis&&b.brokenAxis.setBreaks(a,!1)});f()}))}})};u(f.prototype,{init:function(a,b,c){var d="treegrid"===c.type;d&&(n(b,"beforeRender",G),n(b,"beforeRedraw",G),c=v({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},c,{reversed:!0,grid:{columns:void 0}}));
a.apply(this,[b,c]);d&&(this.hasNames=!0,this.options.showLastLabel=!0)},getMaxLabelDimensions:function(a){var b=this.options,c=b&&b.labels;b=c&&d(c.indentation)?b.labels.indentation:0;c=a.apply(this,y(arguments));if("treegrid"===this.options.type&&this.mapOfPosToGridNode){var e=this.mapOfPosToGridNode[-1].height;c.width+=b*(e-1)}return c},generateTick:function(a,b){var c=h(this.mapOptionsToLevel)?this.mapOptionsToLevel:{},d=this.ticks,e=d[b],f;if("treegrid"===this.options.type){var g=this.mapOfPosToGridNode[b];
(c=c[g.depth])&&(f={labels:c});e?(e.parameters.category=g.name,e.options=f,e.addLabel()):d[b]=new z(this,b,null,void 0,{category:g.name,tickmarkOffset:g.tickmarkOffset,options:f})}else a.apply(this,y(arguments))},setTickInterval:function(b){var c=this.options;"treegrid"===c.type?(this.min=w(this.userMin,c.min,this.dataMin),this.max=w(this.userMax,c.max,this.dataMax),C(this,"foundExtremes"),this.setAxisTranslation(!0),this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.mapOfPosToGridNode?
a(this):[]):b.apply(this,y(arguments))}});u(z.prototype,{getLabelPosition:function(a,b,c,e,f,g,k,l,n){var m=w(this.options&&this.options.labels,g);g=this.pos;var q=this.axis,p="treegrid"===q.options.type;a=a.apply(this,[b,c,e,f,m,k,l,n]);p&&(b=m&&h(m.symbol)?m.symbol:{},m=m&&d(m.indentation)?m.indentation:0,g=(g=(q=q.mapOfPosToGridNode)&&q[g])&&g.depth||1,a.x+=b.width+2*b.padding+(g-1)*m);return a},renderLabel:function(a){var c=this,e=c.pos,d=c.axis,f=c.label,g=d.mapOfPosToGridNode,k=d.options,l=
w(c.options&&c.options.labels,k&&k.labels),p=l&&h(l.symbol)?l.symbol:{},t=(g=g&&g[e])&&g.depth;k="treegrid"===k.type;var r=!(!f||!f.element),u=-1<d.tickPositions.indexOf(e);e=d.chart.styledMode;k&&g&&r&&f.addClass("highcharts-treegrid-node-level-"+t);a.apply(c,y(arguments));k&&g&&r&&0<g.descendants&&(d=b(d,g),I(c,{color:!e&&f.styles.color,collapsed:d,group:f.parentGroup,options:p,renderer:f.renderer,show:u,xy:f.xy}),p="highcharts-treegrid-node-"+(d?"expanded":"collapsed"),f.addClass("highcharts-treegrid-node-"+
(d?"collapsed":"expanded")).removeClass(p),e||f.css({cursor:"pointer"}),[f,c.labelIcon].forEach(function(a){a.attachedTreeGridEvents||(n(a.element,"mouseover",function(){f.addClass("highcharts-treegrid-node-active");f.renderer.styledMode||f.css({textDecoration:"underline"})}),n(a.element,"mouseout",function(){var a=A(l.style)?l.style:{};f.removeClass("highcharts-treegrid-node-active");f.renderer.styledMode||f.css({textDecoration:a.textDecoration})}),n(a.element,"click",function(){c.toggleCollapse()}),
a.attachedTreeGridEvents=!0)}))}});l(z.prototype,{collapse:function(a){var b=this.axis,c=b.brokenAxis;b=g(b,b.mapOfPosToGridNode[this.pos]);c&&c.setBreaks(b,w(a,!0))},expand:function(a){var b=this.axis,c=b.brokenAxis;b=B(b,b.mapOfPosToGridNode[this.pos]);c&&c.setBreaks(b,w(a,!0))},toggleCollapse:function(a){var c=this.axis,d=c.brokenAxis,e=c.mapOfPosToGridNode[this.pos];c=b(c,e)?B(c,e):g(c,e);d&&d.setBreaks(c,w(a,!0))}});f.prototype.utils={getNode:x.getNode}});A(f,"masters/modules/treegrid.src.js",
[],function(){})});
//# sourceMappingURL=treegrid.js.map